/* ============================================================================
   GAA_DB — central Gaelic football database
   Powers Championship 15 and all future GAA games & quizzes.

   Schema (see DATABASE.md):
     counties[name] = { province, abbr, c1, c2, tx? }      colors + province
     teams[]   = { id, county, name, years, dec, tier }    legendary county eras
                  dec:  60/80/90 = classic · 0/10/20 = modern (decade key)
                  tier: 1 all-time great · 2 contender · 3 underdog
     players[] = { team, name, line, rating, club, allIrelands, allStars }
                  line: GK | DEF | MID | FWD · rating 0–99
                  club / allIrelands / allStars: null = not yet researched
============================================================================ */
window.GAA_DB = (() => {

/* sam = senior football All-Irelands (through 2025) · ground = county home venue */
const counties = {
  "Kerry":     {province:"Munster",  abbr:"KER", c1:"#046A38", c2:"#FFB81C", nickname:"The Kingdom",        ground:"Fitzgerald Stadium, Killarney",      sam:39},
  "Cork":      {province:"Munster",  abbr:"COR", c1:"#DA291C", c2:"#FFFFFF", nickname:"The Rebels",         ground:"Páirc Uí Chaoimh",                   sam:7},
  "Clare":     {province:"Munster",  abbr:"CLA", c1:"#FFB81C", c2:"#0057B8", nickname:"The Banner County",  ground:"Cusack Park, Ennis",                 sam:1},
  "Limerick":  {province:"Munster",  abbr:"LIM", c1:"#009A44", c2:"#FFFFFF", nickname:"The Treaty County",  ground:"TUS Gaelic Grounds",                 sam:2},
  "Tipperary": {province:"Munster",  abbr:"TIP", c1:"#0033A0", c2:"#FFB81C", nickname:"The Premier County", ground:"FBD Semple Stadium, Thurles",        sam:4},
  "Waterford": {province:"Munster",  abbr:"WAT", c1:"#FFFFFF", c2:"#0033A0", tx:"#10243a", nickname:"The Déise", ground:"Fraher Field, Dungarvan",       sam:0},
  "Dublin":    {province:"Leinster", abbr:"DUB", c1:"#6CACE4", c2:"#0C2340", nickname:"The Dubs",           ground:"Parnell Park",                       sam:31},
  "Meath":     {province:"Leinster", abbr:"MEA", c1:"#00843D", c2:"#FFCD00", nickname:"The Royal County",   ground:"Páirc Tailteann, Navan",             sam:7},
  "Kildare":   {province:"Leinster", abbr:"KIL", c1:"#E6E9EC", c2:"#B9C4CE", tx:"#2b3a45", nickname:"The Lilywhites", ground:"St Conleth's Park, Newbridge", sam:4},
  "Laois":     {province:"Leinster", abbr:"LAO", c1:"#0072CE", c2:"#FFFFFF", nickname:"The O'Moore County", ground:"O'Moore Park, Portlaoise",           sam:0},
  "Westmeath": {province:"Leinster", abbr:"WES", c1:"#6F263D", c2:"#FFFFFF", nickname:"The Lake County",    ground:"TEG Cusack Park, Mullingar",         sam:0},
  "Offaly":    {province:"Leinster", abbr:"OFF", c1:"#00843D", c2:"#FFCD00", nickname:"The Faithful County",ground:"Glenisk O'Connor Park, Tullamore",   sam:3},
  "Louth":     {province:"Leinster", abbr:"LOU", c1:"#DA291C", c2:"#FFFFFF", nickname:"The Wee County",     ground:null,                                 sam:3},
  "Wexford":   {province:"Leinster", abbr:"WEX", c1:"#6F263D", c2:"#FFB81C", nickname:"The Model County",   ground:"Chadwicks Wexford Park",             sam:5},
  "Carlow":    {province:"Leinster", abbr:"CAR", c1:"#DA291C", c2:"#009A44", nickname:"The Barrowsiders",   ground:"Netwatch Cullen Park",               sam:0},
  "Wicklow":   {province:"Leinster", abbr:"WIC", c1:"#0033A0", c2:"#FFB81C", nickname:"The Garden County",  ground:"Echelon Park, Aughrim",              sam:0},
  "Longford":  {province:"Leinster", abbr:"LON", c1:"#0033A0", c2:"#FFCD00", nickname:null,                 ground:"Glennon Brothers Pearse Park",       sam:0},
  "Tyrone":    {province:"Ulster",   abbr:"TYR", c1:"#CE1126", c2:"#FFFFFF", nickname:"The Red Hands",      ground:"O'Neills Healy Park, Omagh",         sam:4},
  "Armagh":    {province:"Ulster",   abbr:"ARM", c1:"#FF8200", c2:"#FFFFFF", nickname:"The Orchard County", ground:"BOX-IT Athletic Grounds",            sam:2},
  "Derry":     {province:"Ulster",   abbr:"DER", c1:"#C8102E", c2:"#FFFFFF", nickname:"The Oak Leaf County",ground:"Celtic Park",                        sam:1},
  "Down":      {province:"Ulster",   abbr:"DOW", c1:"#DA291C", c2:"#000000", nickname:"The Mourne County",  ground:"Páirc Esler, Newry",                 sam:5},
  "Donegal":   {province:"Ulster",   abbr:"DON", c1:"#F7C200", c2:"#007A33", nickname:"The Hills",          ground:"MacCumhaill Park, Ballybofey",       sam:2},
  "Cavan":     {province:"Ulster",   abbr:"CAV", c1:"#0033A0", c2:"#FFFFFF", nickname:"The Breffni County", ground:"Kingspan Breffni",                   sam:5},
  "Monaghan":  {province:"Ulster",   abbr:"MON", c1:"#0033A0", c2:"#FFFFFF", nickname:"The Farney County",  ground:"St Tiernach's Park, Clones",         sam:0},
  "Fermanagh": {province:"Ulster",   abbr:"FER", c1:"#009A44", c2:"#FFFFFF", nickname:"The Erne County",    ground:"Brewster Park, Enniskillen",         sam:0},
  "Antrim":    {province:"Ulster",   abbr:"ANT", c1:"#F7C200", c2:"#FFFFFF", nickname:"The Saffrons",       ground:"Corrigan Park, Belfast",             sam:0},
  "Galway":    {province:"Connacht", abbr:"GAL", c1:"#6F263D", c2:"#FFFFFF", nickname:"The Tribesmen",      ground:"Pearse Stadium, Salthill",           sam:9},
  "Mayo":      {province:"Connacht", abbr:"MAY", c1:"#046A38", c2:"#C8102E", nickname:"The Green and Red",  ground:"Hastings Insurance MacHale Park",    sam:3},
  "Roscommon": {province:"Connacht", abbr:"ROS", c1:"#F6EB61", c2:"#0033A0", tx:"#1c2c50", nickname:"The Rossies", ground:"Dr Hyde Park",                sam:2},
  "Sligo":     {province:"Connacht", abbr:"SLI", c1:"#000000", c2:"#FFFFFF", nickname:"The Yeats County",   ground:"Markievicz Park",                    sam:0},
  "Leitrim":   {province:"Connacht", abbr:"LEI", c1:"#009A44", c2:"#FFB81C", nickname:"The Ridge County",   ground:"Páirc Seán Mac Diarmada",            sam:0},
  "New York":  {province:"Connacht", abbr:"NYK", c1:"#0033A0", c2:"#DA291C", nickname:"The Exiles",         ground:"Gaelic Park, New York",              sam:0},
  "London":    {province:"Connacht", abbr:"LDN", c1:"#009A44", c2:"#FFFFFF", nickname:"The Exiles",         ground:"McGovern Park, Ruislip",             sam:0}
};

const teams = [
  {id:"kerry-golden",  county:"Kerry",     name:"The Golden Years",          years:"1975–1986", dec:80, tier:1},
  {id:"kerry-00s",     county:"Kerry",     name:"The Noughties",             years:"2000–2009", dec:0,  tier:1},
  {id:"kerry-20s",     county:"Kerry",     name:"Clifford's Kingdom",        years:"2019–today",dec:20, tier:1},
  {id:"dublin-70s",    county:"Dublin",    name:"Heffo's Army",              years:"1974–1979", dec:80, tier:1},
  {id:"dublin-90s",    county:"Dublin",    name:"The Jacks of '95",          years:"1991–1995", dec:90, tier:2},
  {id:"dublin-10s",    county:"Dublin",    name:"Six in a Row",              years:"2011–2020", dec:10, tier:1},
  {id:"tyrone-00s",    county:"Tyrone",    name:"Mickey Harte's Heroes",     years:"2003–2008", dec:0,  tier:1},
  {id:"tyrone-20s",    county:"Tyrone",    name:"Class of 2021",             years:"2018–today",dec:20, tier:2},
  {id:"mayo-10s",      county:"Mayo",      name:"The Nearly Men",            years:"2011–2021", dec:10, tier:2},
  {id:"donegal-90s",   county:"Donegal",   name:"Sam's First Trip North-West",years:"1990–1993",dec:90, tier:2},
  {id:"donegal-10s",   county:"Donegal",   name:"Jimmy's Winning Matches",   years:"2011–2014", dec:10, tier:1},
  {id:"armagh-00s",    county:"Armagh",    name:"The Orchard's First Sam",   years:"1999–2005", dec:0,  tier:1},
  {id:"armagh-20s",    county:"Armagh",    name:"Geezer's 2024 Champions",   years:"2022–today",dec:20, tier:2},
  {id:"meath-boylan",  county:"Meath",     name:"Boylan's Royals",           years:"1987–1999", dec:90, tier:1},
  {id:"galway-98",     county:"Galway",    name:"The Stylish West",          years:"1998–2001", dec:90, tier:1},
  {id:"galway-20s",    county:"Galway",    name:"Joyce's New Tribe",         years:"2022–today",dec:20, tier:2},
  {id:"cork-89",       county:"Cork",      name:"Back-to-Back Rebels",       years:"1989–1990", dec:90, tier:2},
  {id:"cork-10",       county:"Cork",      name:"Counihan's 2010 Rebels",    years:"2009–2012", dec:10, tier:2},
  {id:"down-60s",      county:"Down",      name:"The Pioneers",              years:"1960–1968", dec:60, tier:1},
  {id:"down-90s",      county:"Down",      name:"The Mourne Machine",        years:"1991–1994", dec:90, tier:2},
  {id:"derry-93",      county:"Derry",     name:"The Boys of '93",           years:"1992–1995", dec:90, tier:2},
  {id:"derry-20s",     county:"Derry",     name:"The Oak Leaf Revival",      years:"2022–today",dec:20, tier:2},
  {id:"offaly-82",     county:"Offaly",    name:"Darby's Day",               years:"1980–1982", dec:80, tier:2},
  {id:"roscommon-80",  county:"Roscommon", name:"Primrose Pride",            years:"1977–1980", dec:80, tier:2},
  {id:"monaghan-15",   county:"Monaghan",  name:"Farney Defiance",           years:"2013–2019", dec:10, tier:2},
  {id:"kildare-98",    county:"Kildare",   name:"Micko's Lilywhites",        years:"1997–2000", dec:90, tier:3},
  {id:"laois-03",      county:"Laois",     name:"O'Dwyer's Last Dance",      years:"2003–2005", dec:0,  tier:3},
  {id:"westmeath-04",  county:"Westmeath", name:"Páidí's Lake County Miracle",years:"2004",     dec:0,  tier:3},
  {id:"fermanagh-04",  county:"Fermanagh", name:"The Erne Dreamers",         years:"2003–2008", dec:0,  tier:3},
  {id:"cavan-20",      county:"Cavan",     name:"Breffni Lightning",         years:"2019–2021", dec:20, tier:3},
  {id:"clare-92",      county:"Clare",     name:"The Banner Risen",          years:"1992",      dec:90, tier:3},
  {id:"louth-25",      county:"Louth",     name:"The Wee County Risen",      years:"2023–today",dec:20, tier:3},
  {id:"leitrim-94",    county:"Leitrim",   name:"Connacht Kings of '94",     years:"1994",      dec:90, tier:3},
  {id:"sligo-07",      county:"Sligo",     name:"The Yeats County Breakthrough",years:"2007",   dec:0,  tier:3}
];

/* [teamId, name, line, rating, club, allIrelands, allStars] — null = TBD */
const P = [
/* ---- Kerry, The Golden Years ---- */
["kerry-golden","Charlie Nelligan","GK",88,"Austin Stacks",7,null],
["kerry-golden","Páidí Ó Sé","DEF",93,"An Ghaeltacht",8,5],
["kerry-golden","John O'Keeffe","DEF",92,"Austin Stacks",4,3],
["kerry-golden","Tim Kennelly","DEF",89,"Listowel Emmets",5,1],
["kerry-golden","Jimmy Deenihan","DEF",88,"Finuge",5,null],
["kerry-golden","Tommy Doyle","DEF",86,null,null,null],
["kerry-golden","Mick Spillane","DEF",84,"Templenoe",null,null],
["kerry-golden","Jack O'Shea","MID",97,"St Mary's Cahersiveen",7,6],
["kerry-golden","Seán Walsh","MID",88,null,7,null],
["kerry-golden","Pat Spillane","FWD",96,"Templenoe",8,9],
["kerry-golden","Mikey Sheehy","FWD",96,"Austin Stacks",8,7],
["kerry-golden","Eoin 'Bomber' Liston","FWD",94,"Beale",7,null],
["kerry-golden","John Egan","FWD",92,"Sneem",6,null],
["kerry-golden","Ger Power","FWD",91,"Austin Stacks",8,6],
["kerry-golden","Ogie Moran","FWD",89,"Beale",8,null],
/* ---- Kerry, The Noughties ---- */
["kerry-00s","Diarmuid Murphy","GK",86,null,4,1],
["kerry-00s","Séamus Moynihan","DEF",94,"Glenflesk",4,2],
["kerry-00s","Tomás Ó Sé","DEF",93,"An Ghaeltacht",5,5],
["kerry-00s","Marc Ó Sé","DEF",91,"An Ghaeltacht",5,3],
["kerry-00s","Tom O'Sullivan","DEF",88,null,5,null],
["kerry-00s","Mike McCarthy","DEF",88,"Kilcummin",4,3],
["kerry-00s","Aidan O'Mahony","DEF",87,"Rathmore",5,2],
["kerry-00s","Darragh Ó Sé","MID",95,"An Ghaeltacht",6,4],
["kerry-00s","William Kirby","MID",84,null,3,null],
["kerry-00s","Colm 'Gooch' Cooper","FWD",97,"Dr Crokes",5,8],
["kerry-00s","Declan O'Sullivan","FWD",91,"Dromid Pearses",5,2],
["kerry-00s","Kieran Donaghy","FWD",90,"Austin Stacks",4,3],
["kerry-00s","Paul Galvin","FWD",90,"Finuge",4,3],
["kerry-00s","Mike Frank Russell","FWD",87,"Laune Rangers",3,null],
["kerry-00s","Dara Ó Cinnéide","FWD",87,"An Ghaeltacht",3,null],
/* ---- Kerry, Clifford's Kingdom ---- */
["kerry-20s","Shane Ryan","GK",88,"Rathmore",1,1],
["kerry-20s","Tom O'Sullivan","DEF",89,"Dingle",1,1],
["kerry-20s","Gavin White","DEF",89,"Dr Crokes",1,1],
["kerry-20s","Jason Foley","DEF",88,"Ballydonoghue",1,1],
["kerry-20s","Tadhg Morley","DEF",87,"Templenoe",1,null],
["kerry-20s","Brian Ó Beaglaoich","DEF",85,"An Ghaeltacht",1,null],
["kerry-20s","Graham O'Sullivan","DEF",84,"Dromid Pearses",1,null],
["kerry-20s","Diarmuid O'Connor","MID",87,"Na Gaeil",1,null],
["kerry-20s","Joe O'Connor","MID",86,"Austin Stacks",1,1],
["kerry-20s","David Clifford","FWD",99,"Fossa",1,5],
["kerry-20s","Seán O'Shea","FWD",93,"Kenmare Shamrocks",1,2],
["kerry-20s","Paudie Clifford","FWD",91,"Fossa",1,2],
["kerry-20s","Paul Geaney","FWD",87,"Dingle",2,1],
["kerry-20s","Tony Brosnan","FWD",83,"Dr Crokes",1,null],
/* ---- Dublin, Heffo's Army ---- */
["dublin-70s","Paddy Cullen","GK",89,null,3,3],
["dublin-70s","Kevin Moran","DEF",91,"Good Counsel",2,null],
["dublin-70s","Tommy Drumm","DEF",87,"Whitehall Colmcille",3,null],
["dublin-70s","Robbie Kelleher","DEF",86,"Scoil Uí Chonaill",3,null],
["dublin-70s","Seán Doherty","DEF",86,null,3,null],
["dublin-70s","Gay O'Driscoll","DEF",85,"St Vincent's",3,null],
["dublin-70s","Brian Mullins","MID",95,"St Vincent's",4,null],
["dublin-70s","Bernard Brogan Snr","MID",85,"St Oliver Plunketts",3,null],
["dublin-70s","Jimmy Keaveney","FWD",93,"St Vincent's",3,3],
["dublin-70s","Anton O'Toole","FWD",89,"Synge Street",4,null],
["dublin-70s","David Hickey","FWD",88,"Raheny",3,null],
["dublin-70s","Tony Hanahoe","FWD",88,"St Vincent's",3,null],
["dublin-70s","Bobby Doyle","FWD",86,"St Vincent's",3,null],
["dublin-70s","John McCarthy","FWD",84,"Na Fianna",3,null],
/* ---- Dublin, The Jacks of '95 ---- */
["dublin-90s","John O'Leary","GK",90,"O'Dwyers",2,2],
["dublin-90s","Paul Curran","DEF",90,"Thomas Davis",1,2],
["dublin-90s","Keith Barr","DEF",89,"Erin's Isle",1,null],
["dublin-90s","Eamonn Heery","DEF",85,null,1,null],
["dublin-90s","Mick Deegan","DEF",84,"Erin's Isle",1,null],
["dublin-90s","Ciarán Walsh","DEF",83,null,1,null],
["dublin-90s","Brian Stynes","MID",85,"Ballyboden St Enda's",1,null],
["dublin-90s","Paul Bealin","MID",85,null,1,null],
["dublin-90s","Jack Sheedy","MID",84,"Lucan Sarsfields",null,null],
["dublin-90s","Charlie Redmond","FWD",88,"Erin's Isle",1,null],
["dublin-90s","Dessie Farrell","FWD",87,"Na Fianna",1,1],
["dublin-90s","Jason Sherlock","FWD",87,null,1,1],
["dublin-90s","Mick Galvin","FWD",84,null,1,null],
["dublin-90s","Vinnie Murphy","FWD",83,null,null,null],
/* ---- Dublin, Six in a Row ---- */
["dublin-10s","Stephen Cluxton","GK",97,"Parnells",9,2],
["dublin-10s","Jack McCaffrey","DEF",95,"Clontarf",6,3],
["dublin-10s","James McCarthy","DEF",94,"Ballymun Kickhams",9,4],
["dublin-10s","Cian O'Sullivan","DEF",90,"Kilmacud Crokes",8,2],
["dublin-10s","Philly McMahon","DEF",89,"Ballymun Kickhams",8,2],
["dublin-10s","Jonny Cooper","DEF",88,"Na Fianna",7,null],
["dublin-10s","Mick Fitzsimons","DEF",88,"Cuala",9,1],
["dublin-10s","Brian Fenton","MID",97,"Raheny",7,5],
["dublin-10s","Michael Darragh Macauley","MID",89,"Ballyboden St Enda's",8,1],
["dublin-10s","Con O'Callaghan","FWD",95,"Cuala",6,3],
["dublin-10s","Ciarán Kilkenny","FWD",94,"Castleknock",8,4],
["dublin-10s","Diarmuid Connolly","FWD",94,"St Vincent's",6,2],
["dublin-10s","Bernard Brogan","FWD",93,"St Oliver Plunketts ER",7,4],
["dublin-10s","Paul Mannion","FWD",90,"Kilmacud Crokes",6,2],
["dublin-10s","Paul Flynn","FWD",90,"Fingallians",6,4],
["dublin-10s","Dean Rock","FWD",89,"Ballymun Kickhams",7,1],
["dublin-10s","Kevin McManamon","FWD",86,"St Jude's",8,null],
/* ---- Tyrone, Mickey Harte's Heroes ---- */
["tyrone-00s","Pascal McConnell","GK",84,"Newtownstewart",3,null],
["tyrone-00s","Conor Gormley","DEF",90,"Carrickmore",3,3],
["tyrone-00s","Philip Jordan","DEF",90,"Moy",3,3],
["tyrone-00s","Ryan McMenamin","DEF",88,"Dromore",3,2],
["tyrone-00s","Davy Harte","DEF",84,null,3,null],
["tyrone-00s","Joe McMahon","DEF",84,"Omagh St Enda's",3,null],
["tyrone-00s","Ciarán Gourley","DEF",83,null,3,null],
["tyrone-00s","Seán Cavanagh","MID",95,"Moy",3,5],
["tyrone-00s","Enda McGinley","MID",86,"Errigal Ciarán",3,1],
["tyrone-00s","Kevin Hughes","MID",86,"Killeeshil",3,null],
["tyrone-00s","Peter Canavan","FWD",97,"Errigal Ciarán",2,6],
["tyrone-00s","Stephen O'Neill","FWD",93,"Clann na nGael",3,2],
["tyrone-00s","Brian Dooher","FWD",91,null,3,3],
["tyrone-00s","Brian McGuigan","FWD",90,"Ardboe",3,1],
["tyrone-00s","Owen Mulligan","FWD",89,"Cookstown Fr Rock's",3,1],
/* ---- Tyrone, Class of 2021 ---- */
["tyrone-20s","Niall Morgan","GK",90,"Edendork",1,1],
["tyrone-20s","Pádraig Hampsey","DEF",88,"Coalisland",1,1],
["tyrone-20s","Peter Harte","DEF",88,"Errigal Ciarán",1,null],
["tyrone-20s","Kieran McGeary","DEF",88,"Pomeroy",1,1],
["tyrone-20s","Conor Meyler","DEF",88,"Omagh St Enda's",1,1],
["tyrone-20s","Ronan McNamee","DEF",86,"Aghyaran",1,null],
["tyrone-20s","Michael McKernan","DEF",84,"Coalisland",1,null],
["tyrone-20s","Conn Kilpatrick","MID",84,"Edendork",1,null],
["tyrone-20s","Brian Kennedy","MID",83,"Dungannon",1,null],
["tyrone-20s","Darragh Canavan","FWD",91,"Errigal Ciarán",1,1],
["tyrone-20s","Mattie Donnelly","FWD",88,"Trillick",1,null],
["tyrone-20s","Darren McCurry","FWD",87,"Edendork",1,1],
["tyrone-20s","Cathal McShane","FWD",86,"Owen Roe O'Neills",1,1],
["tyrone-20s","Niall Sludden","FWD",83,"Dromore",1,null],
/* ---- Mayo, The Nearly Men ---- */
["mayo-10s","David Clarke","GK",89,"Ballina Stephenites",0,2],
["mayo-10s","Lee Keegan","DEF",95,"Westport",0,5],
["mayo-10s","Keith Higgins","DEF",90,"Ballyhaunis",0,4],
["mayo-10s","Colm Boyle","DEF",89,"Davitts",0,3],
["mayo-10s","Paddy Durcan","DEF",89,"Castlebar Mitchels",0,2],
["mayo-10s","Chris Barrett","DEF",87,"Belmullet",0,2],
["mayo-10s","Brendan Harrison","DEF",84,"Aghamore",0,1],
["mayo-10s","Aidan O'Shea","MID",91,"Breaffy",0,3],
["mayo-10s","Séamus O'Shea","MID",85,"Breaffy",0,null],
["mayo-10s","Tom Parsons","MID",85,"Charlestown",0,null],
["mayo-10s","Cillian O'Connor","FWD",92,"Ballintubber",0,3],
["mayo-10s","Andy Moran","FWD",90,"Ballaghaderreen",0,2],
["mayo-10s","Diarmuid O'Connor","FWD",87,"Ballintubber",0,1],
["mayo-10s","Kevin McLoughlin","FWD",86,"Knockmore",0,null],
["mayo-10s","Jason Doherty","FWD",84,"Burrishoole",0,null],
/* ---- Donegal, Sam's First Trip North-West ---- */
["donegal-90s","Gary Walsh","GK",86,"Aodh Ruadh",1,null],
["donegal-90s","Martin Gavigan","DEF",85,null,1,1],
["donegal-90s","Matt Gallagher","DEF",84,null,1,null],
["donegal-90s","John Joe Doherty","DEF",83,null,1,null],
["donegal-90s","Donal Reid","DEF",82,null,1,null],
["donegal-90s","Noel Hegarty","DEF",82,null,1,null],
["donegal-90s","Anthony Molloy","MID",90,"Ardara",1,1],
["donegal-90s","Brian Murray","MID",84,null,1,null],
["donegal-90s","Martin McHugh","FWD",92,"Kilcar",1,2],
["donegal-90s","Tony Boyle","FWD",89,"Dungloe",1,1],
["donegal-90s","Manus Boyle","FWD",86,"Killybegs",1,null],
["donegal-90s","Declan Bonner","FWD",85,"Na Rossa",1,null],
["donegal-90s","Joyce McMullan","FWD",83,null,1,null],
["donegal-90s","James McHugh","FWD",83,"Kilcar",1,null],
/* ---- Donegal, Jimmy's Winning Matches ---- */
["donegal-10s","Paul Durcan","GK",88,"Four Masters",1,1],
["donegal-10s","Karl Lacey","DEF",93,"Four Masters",1,4],
["donegal-10s","Neil McGee","DEF",90,"Gaoth Dobhair",1,2],
["donegal-10s","Frank McGlynn","DEF",88,"Glenfin",1,1],
["donegal-10s","Mark McHugh","DEF",86,"Kilcar",1,1],
["donegal-10s","Eamon McGee","DEF",85,"Gaoth Dobhair",1,null],
["donegal-10s","Anthony Thompson","DEF",85,"Naomh Conaill",1,null],
["donegal-10s","Neil Gallagher","MID",88,"Glenswilly",1,1],
["donegal-10s","Rory Kavanagh","MID",85,"St Eunan's",1,null],
["donegal-10s","Michael Murphy","FWD",96,"Glenswilly",1,3],
["donegal-10s","Colm McFadden","FWD",90,"St Michael's",1,2],
["donegal-10s","Ryan McHugh","FWD",90,"Kilcar",0,2],
["donegal-10s","Patrick McBrearty","FWD",89,"Kilcar",1,1],
["donegal-10s","Leo McLoone","FWD",83,"Naomh Conaill",1,null],
/* ---- Armagh, The Orchard's First Sam ---- */
["armagh-00s","Benny Tierney","GK",84,"Mullaghbawn",1,null],
["armagh-00s","Kieran McGeeney","DEF",95,"Mullaghbawn",1,3],
["armagh-00s","Enda McNulty","DEF",87,"Mullaghbawn",1,1],
["armagh-00s","Francie Bellew","DEF",87,"Crossmaglen Rangers",1,1],
["armagh-00s","Justin McNulty","DEF",85,"Mullaghbawn",1,null],
["armagh-00s","Aidan O'Rourke","DEF",85,"Dromintee",1,null],
["armagh-00s","Andy McCann","DEF",83,null,1,null],
["armagh-00s","Paul McGrane","MID",89,"Ballyhegan",1,1],
["armagh-00s","John Toal","MID",84,"Keady",1,null],
["armagh-00s","Oisín McConville","FWD",92,"Crossmaglen Rangers",1,1],
["armagh-00s","Stevie McDonnell","FWD",92,"Killeavy",1,3],
["armagh-00s","Ronan Clarke","FWD",88,"Pearse Óg",1,1],
["armagh-00s","Diarmaid Marsden","FWD",87,"Clan na Gael",1,1],
["armagh-00s","John McEntee","FWD",85,"Crossmaglen Rangers",1,null],
["armagh-00s","Paddy McKeever","FWD",83,"Ballyhegan",1,null],
/* ---- Armagh, Geezer's 2024 Champions ---- */
["armagh-20s","Ethan Rafferty","GK",87,"Grange",1,null],
["armagh-20s","Barry McCambridge","DEF",86,"Clan na Gael",1,1],
["armagh-20s","Aidan Forker","DEF",86,"Maghery",1,null],
["armagh-20s","Aaron McKay","DEF",85,"Dromintee",1,null],
["armagh-20s","Paddy Burns","DEF",84,"Burren",1,null],
["armagh-20s","Joe McElroy","DEF",82,"Armagh Harps",1,null],
["armagh-20s","Ben Crealey","MID",84,"Maghery",1,null],
["armagh-20s","Jarly Óg Burns","MID",84,"Silverbridge",1,null],
["armagh-20s","Niall Grimley","MID",83,"Madden",1,null],
["armagh-20s","Rian O'Neill","FWD",92,"Crossmaglen Rangers",1,null],
["armagh-20s","Oisín Conaty","FWD",87,"Tír na nÓg",1,1],
["armagh-20s","Conor Turbitt","FWD",86,"Clann Éireann",1,null],
["armagh-20s","Rory Grugan","FWD",85,"Ballymacnab",1,null],
["armagh-20s","Andrew Murnin","FWD",84,"St Paul's",1,null],
["armagh-20s","Stefan Campbell","FWD",84,"Clan na Gael",1,null],
/* ---- Meath, Boylan's Royals ---- */
["meath-boylan","Michael McQuillan","GK",84,null,2,null],
["meath-boylan","Martin O'Connell","DEF",92,"St Michael's",3,3],
["meath-boylan","Mick Lyons","DEF",92,"Summerhill",2,2],
["meath-boylan","Darren Fay","DEF",91,"Trim",2,2],
["meath-boylan","Robbie O'Malley","DEF",90,"St Michael's",3,2],
["meath-boylan","Mark O'Reilly","DEF",87,"Summerhill",2,1],
["meath-boylan","Kevin Foley","DEF",84,"Trim",2,null],
["meath-boylan","John McDermott","MID",92,null,2,2],
["meath-boylan","Liam Hayes","MID",88,"Skryne",2,1],
["meath-boylan","Gerry McEntee","MID",86,null,2,null],
["meath-boylan","Trevor Giles","FWD",94,"Skryne",2,3],
["meath-boylan","Graham Geraghty","FWD",93,"Seneschalstown",2,3],
["meath-boylan","Colm O'Rourke","FWD",92,"Skryne",2,2],
["meath-boylan","Bernard Flynn","FWD",89,null,2,2],
["meath-boylan","Tommy Dowd","FWD",89,null,2,1],
["meath-boylan","Ollie Murphy","FWD",87,"Carnaross",1,1],
/* ---- Galway, The Stylish West ---- */
["galway-98","Martin McNamara","GK",85,"Corofin",2,null],
["galway-98","Seán Óg de Paor","DEF",90,"An Cheathrú Rua",2,2],
["galway-98","Tomás Mannion","DEF",86,null,2,null],
["galway-98","Gary Fahey","DEF",86,"Killannin",2,null],
["galway-98","Ray Silke","DEF",84,"Corofin",2,null],
["galway-98","John Divilly","DEF",83,null,2,null],
["galway-98","Kevin Walsh","MID",89,"Killannin",2,1],
["galway-98","Seán Ó Domhnaill","MID",86,"An Cheathrú Rua",2,1],
["galway-98","Pádraic Joyce","FWD",95,"Killererin",2,2],
["galway-98","Michael Donnellan","FWD",94,"Dunmore MacHales",2,2],
["galway-98","Ja Fallon","FWD",92,"Tuam Stars",2,2],
["galway-98","Derek Savage","FWD",85,"Cortoon Shamrocks",2,null],
["galway-98","Paul Clancy","FWD",84,null,2,null],
["galway-98","Niall Finnegan","FWD",83,"Salthill",2,null],
/* ---- Galway, Joyce's New Tribe ---- */
["galway-20s","Connor Gleeson","GK",84,"Dunmore MacHales",0,null],
["galway-20s","Seán Kelly","DEF",88,"Moycullen",0,1],
["galway-20s","Dylan McHugh","DEF",87,"Corofin",0,1],
["galway-20s","Liam Silke","DEF",86,"Corofin",0,null],
["galway-20s","John Daly","DEF",85,"Mountbellew-Moylough",0,null],
["galway-20s","Jack Glynn","DEF",84,"Claregalway",0,null],
["galway-20s","Paul Conroy","MID",89,"St James'",0,1],
["galway-20s","Cillian McDaid","MID",87,"Monivea-Abbey",0,1],
["galway-20s","John Maher","MID",85,"Salthill-Knocknacarra",0,null],
["galway-20s","Shane Walsh","FWD",93,"Kilkerrin-Clonberne",0,1],
["galway-20s","Damien Comer","FWD",91,"Annaghdown",0,2],
["galway-20s","Rob Finnerty","FWD",86,"Salthill-Knocknacarra",0,null],
["galway-20s","Matthew Tierney","FWD",84,"Oughterard",0,null],
["galway-20s","Johnny Heaney","FWD",83,"Killannin",0,null],
/* ---- Cork, Back-to-Back Rebels ---- */
["cork-89","John Kerins","GK",87,"St Finbarr's",2,1],
["cork-89","Niall Cahalane","DEF",89,"Castlehaven",2,1],
["cork-89","Stephen O'Brien","DEF",87,"Nemo Rangers",2,1],
["cork-89","Conor Counihan","DEF",86,"Aghada",2,1],
["cork-89","Tony Davis","DEF",85,"Castlehaven",2,1],
["cork-89","Jimmy Kerrigan","DEF",84,"Nemo Rangers",1,null],
["cork-89","Shea Fahy","MID",89,"Nemo Rangers",2,1],
["cork-89","Teddy McCarthy","MID",87,"Sarsfields",2,1],
["cork-89","Danny Culloty","MID",84,null,2,null],
["cork-89","Larry Tompkins","FWD",94,"Castlehaven",2,3],
["cork-89","Colm O'Neill","FWD",86,null,2,null],
["cork-89","Dave Barry","FWD",85,"St Finbarr's",2,1],
["cork-89","John Cleary","FWD",85,"Castlehaven",1,null],
["cork-89","Paul McGrath","FWD",84,null,2,null],
/* ---- Cork, Counihan's 2010 Rebels ---- */
["cork-10","Alan Quirke","GK",84,"Valley Rovers",1,null],
["cork-10","Graham Canty","DEF",90,"Bantry Blues",1,2],
["cork-10","Michael Shields","DEF",86,"St Finbarr's",1,1],
["cork-10","John Miskella","DEF",85,"Ballincollig",1,1],
["cork-10","Eoin Cadogan","DEF",84,"Douglas",1,null],
["cork-10","Noel O'Leary","DEF",84,"Cill na Martra",1,null],
["cork-10","Aidan Walsh","MID",86,"Kanturk",1,1],
["cork-10","Nicholas Murphy","MID",85,"Carrigaline",1,null],
["cork-10","Alan O'Connor","MID",84,"St Colum's",1,null],
["cork-10","Daniel Goulding","FWD",88,"Éire Óg",1,1],
["cork-10","Donncha O'Connor","FWD",87,"Ballydesmond",1,1],
["cork-10","Colm O'Neill","FWD",87,"Ballyclough",1,1],
["cork-10","Paul Kerrigan","FWD",85,"Nemo Rangers",1,null],
["cork-10","Pearse O'Neill","FWD",84,"Aghada",1,null],
["cork-10","Ciarán Sheehan","FWD",84,"Éire Óg",1,null],
/* ---- Down, The Pioneers ---- */
["down-60s","Eamonn McKay","GK",82,null,3,null],
["down-60s","Leo Murphy","DEF",84,null,2,null],
["down-60s","Dan McCartan","DEF",87,null,3,null],
["down-60s","Tom O'Hare","DEF",84,null,1,null],
["down-60s","George Lavery","DEF",83,null,2,null],
["down-60s","Joe Lennon","MID",86,null,3,null],
["down-60s","Colm McAlarney","MID",88,null,1,null],
["down-60s","Jarlath Carey","MID",82,null,2,null],
["down-60s","Seán O'Neill","FWD",95,null,3,null],
["down-60s","Paddy Doherty","FWD",93,"Ballykinlar",3,null],
["down-60s","James McCartan Snr","FWD",89,null,3,null],
["down-60s","Patsy O'Hagan","FWD",83,null,2,null],
["down-60s","Brian Johnston","FWD",82,null,2,null],
/* ---- Down, The Mourne Machine ---- */
["down-90s","Neil Collins","GK",84,null,2,null],
["down-90s","Conor Deegan","DEF",87,"Burren",2,1],
["down-90s","DJ Kane","DEF",85,null,2,null],
["down-90s","Barry Breen","DEF",84,null,2,null],
["down-90s","Paul Higgins","DEF",83,null,2,null],
["down-90s","John Kelly","DEF",82,null,1,null],
["down-90s","Gregory McCartan","MID",84,"Tullylish",1,null],
["down-90s","Eamonn Burns","MID",83,null,2,null],
["down-90s","Mickey Linden","FWD",93,"Mayobridge",2,1],
["down-90s","Greg Blaney","FWD",91,null,2,2],
["down-90s","James McCartan","FWD",91,"Tullylish",2,2],
["down-90s","Ross Carr","FWD",89,"Clonduff",2,1],
["down-90s","Peter Withnell","FWD",84,null,1,null],
["down-90s","Gary Mason","FWD",83,null,1,null],
/* ---- Derry, The Boys of '93 ---- */
["derry-93","Damien McCusker","GK",84,"Glen",1,null],
["derry-93","Henry Downey","DEF",91,"Lavey",1,2],
["derry-93","Tony Scullion","DEF",90,"Ballinascreen",1,3],
["derry-93","Kieran McKeever","DEF",87,"Dungiven",1,1],
["derry-93","Johnny McGurk","DEF",85,"Lavey",1,1],
["derry-93","Gary Coleman","DEF",84,null,1,null],
["derry-93","Anthony Tohill","MID",95,"Swatragh",1,3],
["derry-93","Brian McGilligan","MID",90,"Dungiven",1,1],
["derry-93","Joe Brolly","FWD",88,"Dungiven",1,1],
["derry-93","Enda Gormley","FWD",88,"Glen",1,1],
["derry-93","Damian Cassidy","FWD",84,"Bellaghy",1,null],
["derry-93","Damian Barton","FWD",84,null,1,null],
["derry-93","Seamus Downey","FWD",84,"Lavey",1,null],
["derry-93","Dermot Heaney","FWD",83,null,1,null],
/* ---- Derry, The Oak Leaf Revival ---- */
["derry-20s","Odhrán Lynch","GK",83,"Magherafelt",0,null],
["derry-20s","Chrissy McKaigue","DEF",89,"Slaughtneil",0,1],
["derry-20s","Brendan Rogers","DEF",89,"Slaughtneil",0,1],
["derry-20s","Eoin McEvoy","DEF",86,"Magherafelt",0,1],
["derry-20s","Gareth McKinless","DEF",86,"Ballinderry",0,null],
["derry-20s","Conor McCluskey","DEF",85,"Magherafelt",0,null],
["derry-20s","Conor Glass","MID",92,"Glen",0,1],
["derry-20s","Emmett Bradley","MID",82,"Glen",0,null],
["derry-20s","Shane McGuigan","FWD",91,"Slaughtneil",0,1],
["derry-20s","Ethan Doherty","FWD",85,"Glen",0,null],
["derry-20s","Paul Cassidy","FWD",84,"Bellaghy",0,null],
["derry-20s","Lachlan Murray","FWD",83,"Desertmartin",0,null],
["derry-20s","Niall Loughlin","FWD",82,"Greenlough",0,null],
/* ---- Offaly, Darby's Day ---- */
["offaly-82","Martin Furlong","GK",88,"Tullamore",3,1],
["offaly-82","Seán Lowry","DEF",85,"Ferbane",3,null],
["offaly-82","Mick Fitzgerald","DEF",83,null,1,null],
["offaly-82","Pat Fitzgerald","DEF",82,null,1,null],
["offaly-82","Liam O'Connor","DEF",82,"Walsh Island",1,null],
["offaly-82","Liam Currams","DEF",85,null,1,1],
["offaly-82","Richie Connor","MID",85,"Walsh Island",1,null],
["offaly-82","Pádraic Dunne","MID",83,null,1,null],
["offaly-82","Tomás O'Connor","MID",82,"Walsh Island",1,null],
["offaly-82","Matt Connor","FWD",95,"Walsh Island",1,3],
["offaly-82","Brendan Lowry","FWD",84,"Ferbane",1,1],
["offaly-82","Johnny Mooney","FWD",84,null,1,1],
["offaly-82","Gerry Carroll","FWD",81,null,1,null],
["offaly-82","Seamus Darby","FWD",83,"Rhode",1,null],
/* ---- Roscommon, Primrose Pride ---- */
["roscommon-80","Gay Sheerin","GK",81,null,0,null],
["roscommon-80","Harry Keegan","DEF",86,"Castlerea St Kevin's",0,3],
["roscommon-80","Pat Lindsay","DEF",84,null,0,1],
["roscommon-80","Tom Heneghan","DEF",83,null,0,1],
["roscommon-80","Danny Murray","DEF",84,null,0,2],
["roscommon-80","Gerry Fitzmaurice","DEF",81,null,0,null],
["roscommon-80","Dermot Earley","MID",92,"Michael Glaveys",0,2],
["roscommon-80","Seamus Hayden","MID",81,null,0,null],
["roscommon-80","Tony McManus","FWD",88,"Clann na nGael",0,1],
["roscommon-80","Michael Finneran","FWD",83,null,0,1],
["roscommon-80","John O'Connor","FWD",80,null,0,null],
["roscommon-80","Eamonn McManus","FWD",80,null,0,null],
/* ---- Monaghan, Farney Defiance ---- */
["monaghan-15","Rory Beggan","GK",91,"Scotstown",0,1],
["monaghan-15","Drew Wylie","DEF",84,"Ballybay",0,null],
["monaghan-15","Ryan Wylie","DEF",83,"Ballybay",0,null],
["monaghan-15","Colin Walshe","DEF",84,"Doohamlet",0,1],
["monaghan-15","Vinny Corey","DEF",85,"Clontibret",0,null],
["monaghan-15","Karl O'Connell","DEF",85,"Tyholland",0,1],
["monaghan-15","Dessie Mone","DEF",81,"Clontibret",0,null],
["monaghan-15","Darren Hughes","MID",86,"Scotstown",0,null],
["monaghan-15","Fintan Kelly","MID",82,null,0,null],
["monaghan-15","Conor McManus","FWD",94,"Clontibret",0,3],
["monaghan-15","Kieran Hughes","FWD",85,"Scotstown",0,null],
["monaghan-15","Jack McCarron","FWD",84,"Currin",0,null],
["monaghan-15","Conor McCarthy","FWD",82,"Scotstown",0,null],
["monaghan-15","Shane Carey","FWD",80,null,0,null],
/* ---- Kildare, Micko's Lilywhites ---- */
["kildare-98","Christy Byrne","GK",79,null,0,null],
["kildare-98","Glenn Ryan","DEF",86,"Round Towers",0,1],
["kildare-98","Anthony Rainbow","DEF",83,"Suncroft",0,1],
["kildare-98","Brian Lacey","DEF",82,null,0,1],
["kildare-98","John Finn","DEF",78,null,0,null],
["kildare-98","Ken Doyle","DEF",77,null,0,null],
["kildare-98","Niall Buckley","MID",85,"Sarsfields",0,1],
["kildare-98","Willie McCreery","MID",81,null,0,null],
["kildare-98","Dermot Earley Jnr","MID",84,"Sarsfields",0,1],
["kildare-98","Martin Lynch","FWD",81,null,0,null],
["kildare-98","Karl O'Dwyer","FWD",79,null,0,null],
["kildare-98","Eddie McCormack","FWD",78,null,0,null],
["kildare-98","Brian Murphy","FWD",79,null,0,null],
/* ---- Laois, O'Dwyer's Last Dance ---- */
["laois-03","Fergal Byron","GK",81,null,0,1],
["laois-03","Joe Higgins","DEF",82,null,0,1],
["laois-03","Tom Kelly","DEF",83,null,0,1],
["laois-03","Aidan Fennelly","DEF",78,null,0,null],
["laois-03","Darren Rooney","DEF",77,null,0,null],
["laois-03","Pádraig Clancy","MID",82,"Timahoe",0,null],
["laois-03","Noel Garvan","MID",79,null,0,null],
["laois-03","Colm Parkinson","MID",78,"Portlaoise",0,null],
["laois-03","Ross Munnelly","FWD",85,"Arles-Kilcruise",0,null],
["laois-03","Brian 'Beano' McDonald","FWD",82,"Portlaoise",0,null],
["laois-03","Chris Conway","FWD",79,"Arles-Kilcruise",0,null],
["laois-03","Ian Fitzgerald","FWD",79,null,0,null],
["laois-03","Billy Sheehan","FWD",78,null,0,null],
/* ---- Westmeath, Páidí's Lake County Miracle ---- */
["westmeath-04","Gary Connaughton","GK",82,"Tubberclair",0,1],
["westmeath-04","John Keane","DEF",84,null,0,1],
["westmeath-04","Michael Ennis","DEF",78,null,0,null],
["westmeath-04","Fergal Wilson","DEF",78,null,0,null],
["westmeath-04","Damien Gavin","DEF",77,null,0,null],
["westmeath-04","Brian Morley","DEF",76,null,0,null],
["westmeath-04","Rory O'Connell","MID",81,null,0,null],
["westmeath-04","David O'Shaughnessy","MID",79,null,0,null],
["westmeath-04","Dessie Dolan","FWD",86,"Garrycastle",0,null],
["westmeath-04","Denis Glennon","FWD",80,null,0,null],
["westmeath-04","Alan Mangan","FWD",79,null,0,null],
["westmeath-04","Martin Flanagan","FWD",77,null,0,null],
/* ---- Fermanagh, The Erne Dreamers ---- */
["fermanagh-04","Ronan Gallagher","GK",76,null,0,null],
["fermanagh-04","Barry Owens","DEF",84,"Teemore Shamrocks",0,2],
["fermanagh-04","Ryan McCluskey","DEF",79,null,0,null],
["fermanagh-04","Shane McDermott","DEF",77,null,0,null],
["fermanagh-04","Niall Bogue","DEF",76,null,0,null],
["fermanagh-04","Marty McGrath","MID",83,"Ederney",0,1],
["fermanagh-04","James Sherry","MID",77,null,0,null],
["fermanagh-04","Liam McBarron","MID",77,null,0,null],
["fermanagh-04","Tom Brewster","FWD",80,null,0,null],
["fermanagh-04","Stephen Maguire","FWD",79,null,0,null],
["fermanagh-04","Mark Little","FWD",78,null,0,null],
["fermanagh-04","Eamon Maguire","FWD",77,null,0,null],
/* ---- Cavan, Breffni Lightning ---- */
["cavan-20","Raymond Galligan","GK",83,"Lacken",0,null],
["cavan-20","Padraig Faulkner","DEF",83,"Kingscourt Stars",0,1],
["cavan-20","Ciaran Brady","DEF",78,"Gowna",0,null],
["cavan-20","Jason McLoughlin","DEF",77,null,0,null],
["cavan-20","Killian Clarke","DEF",78,"Shercock",0,null],
["cavan-20","Thomas Galligan","MID",83,"Lacken",0,1],
["cavan-20","Gearoid McKiernan","MID",83,"Swanlinbar",0,null],
["cavan-20","James Smith","MID",79,"Killygarry",0,null],
["cavan-20","Martin Reilly","FWD",81,"Killygarry",0,null],
["cavan-20","Dara McVeety","FWD",81,"Crosserlough",0,null],
["cavan-20","Conor Madden","FWD",78,"Gowna",0,null],
["cavan-20","Oisín Kiernan","FWD",77,"Castlerahan",0,null],
["cavan-20","Gerard Smith","FWD",76,null,0,null],
/* ---- Louth, The Wee County Risen ---- */
["louth-25","Niall McDonnell","GK",76,null,0,null],
["louth-25","Dan Corcoran","DEF",79,null,0,null],
["louth-25","Donal McKenny","DEF",79,null,0,null],
["louth-25","Peter Lynch","DEF",80,null,0,null],
["louth-25","Dermot Campbell","DEF",77,null,0,null],
["louth-25","Craig Lennon","MID",84,null,0,null],
["louth-25","Tommy Durnin","MID",82,null,0,null],
["louth-25","Bevan Duffy","MID",79,null,0,null],
["louth-25","Niall Sharkey","MID",77,null,0,null],
["louth-25","Sam Mulroy","FWD",86,"Naomh Máirtín",0,null],
["louth-25","Ciarán Downey","FWD",81,null,0,null],
["louth-25","Ryan Burns","FWD",80,null,0,null],
["louth-25","Conor Grimes","FWD",80,null,0,null],
["louth-25","Conall McKeever","FWD",79,null,0,null],
/* ---- Leitrim, Connacht Kings of '94 ---- */
["leitrim-94","Martin McHugh","GK",76,null,0,null],
["leitrim-94","Declan Darcy","DEF",84,"Aughawillan",0,null],
["leitrim-94","Seamus Quinn","DEF",82,null,0,1],
["leitrim-94","Fergal Reynolds","DEF",76,null,0,null],
["leitrim-94","Joe Honeyman","DEF",75,null,0,null],
["leitrim-94","Mickey Quinn","MID",81,"Aughawillan",0,null],
["leitrim-94","Paul Kieran","MID",76,null,0,null],
["leitrim-94","Aidan Rooney","FWD",79,null,0,null],
["leitrim-94","Padraig Kenny","FWD",78,null,0,null],
["leitrim-94","Colin McGlynn","FWD",77,null,0,null],
["leitrim-94","George Dugdale","FWD",76,null,0,null],
["leitrim-94","Liam Conlon","FWD",76,null,0,null],
/* ---- Sligo, The Yeats County Breakthrough ---- */
["sligo-07","Philip Greene","GK",75,null,0,null],
["sligo-07","Charlie Harrison","DEF",82,null,0,1],
["sligo-07","Ross Donovan","DEF",78,null,0,null],
["sligo-07","Noel McGuire","DEF",76,null,0,null],
["sligo-07","Michael McNamara","DEF",75,null,0,null],
["sligo-07","Eamonn O'Hara","MID",85,"Tourlestrane",0,null],
["sligo-07","Sean Davey","MID",77,null,0,null],
["sligo-07","David Kelly","FWD",81,null,0,null],
["sligo-07","Mark Breheny","FWD",80,null,0,null],
["sligo-07","Brendan Egan","FWD",77,null,0,null],
["sligo-07","Johnny Davey","FWD",76,null,0,null],
["sligo-07","Eugene Mullen","FWD",75,null,0,null],
/* ---- Clare, The Banner Risen ---- */
["clare-92","James Hanrahan","GK",75,null,0,null],
["clare-92","Seamus Clancy","DEF",83,null,0,1],
["clare-92","Noel Roche","DEF",79,null,0,null],
["clare-92","Aidan Moloney","DEF",77,null,0,null],
["clare-92","John Enright","DEF",75,null,0,null],
["clare-92","Tom Morrissey","MID",78,null,0,null],
["clare-92","Pádraig Conway","MID",77,null,0,null],
["clare-92","Francis McInerney","FWD",84,null,0,null],
["clare-92","Martin Daly","FWD",81,null,0,null],
["clare-92","Gerry Killeen","FWD",79,null,0,null],
["clare-92","Colm Clancy","FWD",77,null,0,null]
];

/* ----------------------------------------------------------------------
   X — player extras, keyed "teamId|Name".
   nickname · born (year) · poty (Footballer of the Year awards) ·
   dual ("hurling"/"soccer"/…) · family (relation note) · captain (lifted Sam)
---------------------------------------------------------------------- */
const X = {
 "kerry-00s|Colm 'Gooch' Cooper":{nickname:"Gooch",born:1983},
 "kerry-golden|Eoin 'Bomber' Liston":{nickname:"The Bomber",born:1957},
 "kerry-golden|Jack O'Shea":{nickname:"Jacko",born:1957,poty:1},
 "kerry-golden|Pat Spillane":{born:1955,poty:1,family:"brother of Mick & Tom Spillane"},
 "kerry-golden|Mick Spillane":{family:"brother of Pat & Tom Spillane"},
 "kerry-golden|Páidí Ó Sé":{born:1955,family:"uncle of Darragh, Tomás & Marc Ó Sé"},
 "kerry-golden|Mikey Sheehy":{born:1954},
 "kerry-00s|Darragh Ó Sé":{born:1975,family:"brother of Tomás & Marc, nephew of Páidí"},
 "kerry-00s|Tomás Ó Sé":{born:1978,family:"brother of Darragh & Marc, nephew of Páidí"},
 "kerry-00s|Marc Ó Sé":{born:1980,family:"brother of Darragh & Tomás, nephew of Páidí"},
 "kerry-00s|Kieran Donaghy":{nickname:"Star",born:1983},
 "kerry-00s|Séamus Moynihan":{born:1973,poty:1},
 "kerry-00s|Declan O'Sullivan":{captain:true},
 "kerry-20s|David Clifford":{born:1999,poty:2,family:"brother of Paudie Clifford"},
 "kerry-20s|Paudie Clifford":{born:1997,family:"brother of David Clifford"},
 "kerry-20s|Seán O'Shea":{born:1998},
 "dublin-70s|Kevin Moran":{born:1956,dual:"soccer — Manchester United & Ireland",family:null},
 "dublin-70s|Jimmy Keaveney":{born:1945},
 "dublin-70s|Tony Hanahoe":{captain:true},
 "dublin-70s|Bernard Brogan Snr":{family:"father of Bernard & Alan Brogan"},
 "dublin-90s|Jason Sherlock":{nickname:"Jayo",born:1976},
 "dublin-90s|John O'Leary":{captain:true},
 "dublin-10s|Stephen Cluxton":{born:1981,captain:true},
 "dublin-10s|Bernard Brogan":{born:1984,poty:1,family:"son of Bernard Snr, brother of Alan"},
 "dublin-10s|Brian Fenton":{born:1993,poty:2},
 "dublin-10s|Jack McCaffrey":{born:1993,poty:1},
 "dublin-10s|Ciarán Kilkenny":{born:1993},
 "dublin-10s|Michael Darragh Macauley":{poty:1},
 "dublin-10s|Con O'Callaghan":{born:1996},
 "tyrone-00s|Peter Canavan":{nickname:"Peter the Great",born:1971,captain:true,family:"father of Darragh Canavan"},
 "tyrone-00s|Seán Cavanagh":{born:1983,poty:1},
 "tyrone-00s|Stephen O'Neill":{poty:1},
 "tyrone-00s|Owen Mulligan":{nickname:"Mugsy",born:1981},
 "tyrone-00s|Ryan McMenamin":{nickname:"Ricey"},
 "tyrone-00s|Brian Dooher":{captain:true},
 "tyrone-20s|Kieran McGeary":{poty:1},
 "tyrone-20s|Pádraig Hampsey":{captain:true},
 "tyrone-20s|Darragh Canavan":{born:2001,family:"son of Peter Canavan"},
 "mayo-10s|Lee Keegan":{born:1989,poty:1},
 "mayo-10s|Andy Moran":{born:1983,poty:1},
 "mayo-10s|Aidan O'Shea":{born:1990,family:"brother of Séamus O'Shea"},
 "mayo-10s|Séamus O'Shea":{family:"brother of Aidan O'Shea"},
 "mayo-10s|Cillian O'Connor":{born:1992,captain:false,family:"brother of Diarmuid O'Connor (Mayo)"},
 "mayo-10s|Diarmuid O'Connor":{family:"brother of Cillian O'Connor"},
 "donegal-90s|Anthony Molloy":{captain:true},
 "donegal-90s|Martin McHugh":{nickname:"The Wee Man",family:"father of Mark & Ryan McHugh, brother of James"},
 "donegal-90s|James McHugh":{family:"brother of Martin McHugh"},
 "donegal-10s|Michael Murphy":{born:1989,captain:true},
 "donegal-10s|Karl Lacey":{poty:1},
 "donegal-10s|Mark McHugh":{family:"son of Martin McHugh, brother of Ryan"},
 "donegal-10s|Ryan McHugh":{family:"son of Martin McHugh, brother of Mark"},
 "donegal-10s|Neil McGee":{family:"brother of Eamon McGee"},
 "donegal-10s|Eamon McGee":{family:"brother of Neil McGee"},
 "armagh-00s|Kieran McGeeney":{nickname:"Geezer",born:1971,captain:true,poty:1},
 "armagh-00s|Oisín McConville":{born:1975},
 "armagh-20s|Aidan Forker":{captain:true},
 "armagh-20s|Jarly Óg Burns":{family:"son of Jarlath Burns (GAA President)"},
 "meath-boylan|Trevor Giles":{born:1974,poty:2},
 "meath-boylan|Colm O'Rourke":{poty:1},
 "meath-boylan|Liam Hayes":{captain:true},
 "galway-98|Pádraic Joyce":{born:1977,poty:1},
 "galway-98|Michael Donnellan":{poty:1,family:"son of Pat & nephew of John Donnellan, both Galway greats"},
 "galway-98|Ja Fallon":{poty:1},
 "galway-98|Ray Silke":{captain:true},
 "galway-20s|Seán Kelly":{captain:true},
 "galway-20s|Shane Walsh":{born:1993},
 "cork-89|Larry Tompkins":{captain:true,poty:1,family:null,dual:null},
 "cork-89|Teddy McCarthy":{dual:"hurling — only man to win football & hurling All-Irelands in the same year (1990)"},
 "cork-89|Shea Fahy":{poty:1},
 "cork-89|Dave Barry":{dual:"soccer — League of Ireland with Cork City"},
 "cork-10|Graham Canty":{captain:true},
 "down-60s|Seán O'Neill":{poty:1},
 "down-60s|Paddy Doherty":{captain:true},
 "down-60s|Dan McCartan":{family:"brother of James McCartan Snr"},
 "down-60s|James McCartan Snr":{family:"father of James McCartan Jnr, brother of Dan"},
 "down-90s|James McCartan":{family:"son of James McCartan Snr"},
 "down-90s|Paddy O'Rourke":{captain:true},
 "down-90s|DJ Kane":{captain:true},
 "derry-93|Henry Downey":{captain:true,poty:1},
 "derry-93|Anthony Tohill":{born:1971},
 "derry-93|Joe Brolly":{nickname:"Brolly"},
 "derry-20s|Chrissy McKaigue":{captain:true},
 "offaly-82|Matt Connor":{born:1959,family:"brother of Richie Connor"},
 "offaly-82|Richie Connor":{captain:true,family:"brother of Matt Connor"},
 "offaly-82|Liam Currams":{dual:"hurling — won the 1981 hurling All-Ireland with Offaly"},
 "offaly-82|Seamus Darby":{nickname:"the man who stopped five-in-a-row"},
 "roscommon-80|Dermot Earley":{family:"father of Dermot Earley Jnr"},
 "kildare-98|Dermot Earley Jnr":{family:"son of Dermot Earley (Roscommon)"},
 "kildare-98|Glenn Ryan":{captain:true},
 "laois-03|Brian 'Beano' McDonald":{nickname:"Beano"},
 "monaghan-15|Conor McManus":{born:1987},
 "monaghan-15|Rory Beggan":{born:1992},
 "monaghan-15|Darren Hughes":{family:"brother of Kieran Hughes"},
 "monaghan-15|Kieran Hughes":{family:"brother of Darren Hughes"},
 "monaghan-15|Drew Wylie":{family:"brother of Ryan Wylie"},
 "monaghan-15|Ryan Wylie":{family:"brother of Drew Wylie"},
 "cavan-20|Raymond Galligan":{captain:true},
 "westmeath-04|Dessie Dolan":{family:"brother of Gary Dolan; father Dessie Snr also played for Westmeath"}
};

/* ----------------------------------------------------------------------
   matches — classic All-Ireland finals (Missing XI, score quizzes).
   lineups: null = to be researched (use era squads as fallback).
---------------------------------------------------------------------- */
const matches = [
 {id:"final-1982", year:1982, comp:"All-Ireland Final", winner:"Offaly", loser:"Kerry", score:"1-15 to 0-17", venue:"Croke Park",
  note:"Seamus Darby's late goal denies Kerry the five-in-a-row.", lineups:null},
 {id:"final-1991", year:1991, comp:"All-Ireland Final", winner:"Down", loser:"Meath", score:"1-16 to 1-14", venue:"Croke Park",
  note:"Down become the first Ulster champions since 1968.", lineups:null},
 {id:"final-1993", year:1993, comp:"All-Ireland Final", winner:"Derry", loser:"Cork", score:"1-14 to 2-8", venue:"Croke Park",
  note:"Derry's first and only Sam Maguire.", lineups:null},
 {id:"final-1998", year:1998, comp:"All-Ireland Final", winner:"Galway", loser:"Kildare", score:"1-14 to 1-10", venue:"Croke Park",
  note:"Galway's first title since 1966 — Ja Fallon and Donnellan run riot.", lineups:null},
 {id:"final-2002", year:2002, comp:"All-Ireland Final", winner:"Armagh", loser:"Kerry", score:"1-12 to 0-14", venue:"Croke Park",
  note:"Oisín McConville's goal seals Armagh's first ever Sam.", lineups:null},
 {id:"final-2011", year:2011, comp:"All-Ireland Final", winner:"Dublin", loser:"Kerry", score:"1-12 to 1-11", venue:"Croke Park",
  note:"Cluxton's last-minute free ends Dublin's 16-year wait.", lineups:null},
 {id:"final-2020", year:2020, comp:"All-Ireland Final", winner:"Dublin", loser:"Mayo", score:"2-14 to 0-15", venue:"Croke Park",
  note:"Six in a row, behind closed doors.", lineups:null},
 {id:"final-2024", year:2024, comp:"All-Ireland Final", winner:"Armagh", loser:"Galway", score:"1-11 to 0-13", venue:"Croke Park",
  note:"Geezer's Armagh land their second Sam.", lineups:null}
];

/* ----------------------------------------------------------------------
   lists — curated answers for TenaBall / GoalLess / Lista-style games.
   answers ordered best-first; value null = ordinal only (verify before use).
---------------------------------------------------------------------- */
const lists = [
 {id:"counties-most-sams", title:"Counties with the most All-Ireland football titles",
  answers:[["Kerry",39],["Dublin",31],["Galway",9],["Meath",7],["Cork",7],["Cavan",5],["Down",5],["Wexford",5],["Tyrone",4],["Kildare",4]]},
 {id:"players-most-all-irelands", title:"Players with the most All-Ireland medals",
  answers:[["Stephen Cluxton",9],["James McCarthy",9],["Mick Fitzsimons",9],["Ciarán Kilkenny",8],["Kevin McManamon",8],["Pat Spillane",8],["Páidí Ó Sé",8],["Mikey Sheehy",8],["Ger Power",8],["Ogie Moran",8]]},
 {id:"players-most-all-stars", title:"Players with the most football All-Stars",
  answers:[["Pat Spillane",9],["Colm Cooper",8],["Mikey Sheehy",7],["Jack O'Shea",6],["Peter Canavan",6],["Ger Power",6],["David Clifford",5],["Lee Keegan",5],["Tomás Ó Sé",5],["Brian Fenton",5]]},
 {id:"famous-nicknames", title:"Match the nickname to the player",
  answers:[["Gooch — Colm Cooper",null],["The Bomber — Eoin Liston",null],["Jacko — Jack O'Shea",null],["Mugsy — Owen Mulligan",null],["Jayo — Jason Sherlock",null],["Geezer — Kieran McGeeney",null],["Star — Kieran Donaghy",null],["Ricey — Ryan McMenamin",null],["Beano — Brian McDonald",null]]},
 {id:"dual-stars", title:"Played more than one code at the top level",
  answers:[["Teddy McCarthy — football & hurling All-Irelands in 1990",null],["Liam Currams — Offaly football & hurling All-Irelands",null],["Kevin Moran — Dublin GAA & Manchester United",null],["Dave Barry — Cork GAA & League of Ireland",null],["Jack Lynch — Cork dual star & Taoiseach",null],["Des Foley — Dublin dual star",null]]},
 {id:"famous-captains", title:"Captains who lifted Sam Maguire",
  answers:[["Stephen Cluxton (Dublin ×6)",null],["Kieran McGeeney (Armagh 2002)",null],["Anthony Molloy (Donegal 1992)",null],["Henry Downey (Derry 1993)",null],["Peter Canavan (Tyrone 2003)",null],["Declan O'Sullivan (Kerry)",null],["Michael Murphy (Donegal 2012)",null],["Ray Silke (Galway 1998)",null]]}
];

/* ----------------------------------------------------------------------
   groups — seed puzzles for a GAA Connections game (4 groups of 4).
   Members are display names; they may reference players outside the era squads.
---------------------------------------------------------------------- */
const groups = [
 {id:"connections-1", groups:[
   {link:"Kilcar clubmen",            members:["Martin McHugh","Mark McHugh","Ryan McHugh","Patrick McBrearty"]},
   {link:"Austin Stacks clubmen",     members:["Mikey Sheehy","Ger Power","Charlie Nelligan","Kieran Donaghy"]},
   {link:"Scotstown clubmen",         members:["Rory Beggan","Darren Hughes","Kieran Hughes","Conor McCarthy"]},
   {link:"An Ghaeltacht clubmen",     members:["Páidí Ó Sé","Darragh Ó Sé","Tomás Ó Sé","Marc Ó Sé"]}]},
 {id:"connections-2", groups:[
   {link:"Captains who lifted Sam",   members:["Anthony Molloy","Henry Downey","Kieran McGeeney","Ray Silke"]},
   {link:"Footballer of the Year winners", members:["Lee Keegan","Trevor Giles","Pádraic Joyce","Seán Cavanagh"]},
   {link:"Goalkeepers",               members:["Stephen Cluxton","Rory Beggan","Niall Morgan","Gary Connaughton"]},
   {link:"Played another code",       members:["Teddy McCarthy","Liam Currams","Kevin Moran","Dave Barry"]}]},
 {id:"connections-3", groups:[
   {link:"Sons of county greats",     members:["Darragh Canavan","James McCartan","Dermot Earley Jnr","Bernard Brogan"]},
   {link:"Scored iconic championship goals", members:["Seamus Darby","Oisín McConville","Kevin Foley","Tommy Dowd"]},
   {link:"Brothers of teammates",     members:["Aidan O'Shea","Paudie Clifford","Neil McGee","Drew Wylie"]},
   {link:"Underdog-era legends",      members:["Matt Connor","Dessie Dolan","Ross Munnelly","Conor McManus"]}]}
];

return {
  meta:{version:2, updated:"2026-06-11", sport:"gaelic-football",
        note:"Ratings are editorial. Honours, scores and facts are best-effort from memory — verify before quoting as gospel. null = not yet researched, never zero."},
  counties,
  teams,
  players: P.map(p=>{
    const x = X[p[0]+"|"+p[1]] || {};
    return {
      id:(p[0]+"-"+p[1]).toLowerCase().replace(/[^a-z0-9]+/g,"-"),
      team:p[0], name:p[1], line:p[2], rating:p[3], club:p[4],
      allIrelands:p[5], allStars:p[6],
      nickname:x.nickname||null, born:x.born||null, poty:x.poty||0,
      dual:x.dual||null, family:x.family||null, captain:x.captain||false
    };
  }),
  matches, lists, groups
};
})();
