/* ============================================================================
   GAA_DB — central Gaelic football database
   Powers Championship 15 and all future GAA games & quizzes.

   Schema (see DATABASE.md):
     counties[name] = { province, abbr, c1, c2, tx? }      colors + province
     teams[]   = { id, county, name, years, dec, tier }    legendary county eras
                  dec:  60/80/90 = classic · 0/10/20 = modern (decade key)
                  tier: 1 all-time great · 2 contender · 3 underdog
     players[] = { team, name, line, rating, club, allIrelands, allStars }
                  line: GK | DEF | MID | FWD · rating 0–99
                  club / allIrelands / allStars: null = not yet researched
============================================================================ */
window.GAA_DB = (() => {

/* sam = senior football All-Irelands (through 2025) · ground = county home venue */
const counties = {
  "Kerry":     {province:"Munster",  abbr:"KER", c1:"#046A38", c2:"#FFB81C", nickname:"The Kingdom",        ground:"Fitzgerald Stadium, Killarney",      sam:39},
  "Cork":      {province:"Munster",  abbr:"COR", c1:"#DA291C", c2:"#FFFFFF", nickname:"The Rebels",         ground:"Páirc Uí Chaoimh",                   sam:7},
  "Clare":     {province:"Munster",  abbr:"CLA", c1:"#FFB81C", c2:"#0057B8", nickname:"The Banner County",  ground:"Cusack Park, Ennis",                 sam:1},
  "Limerick":  {province:"Munster",  abbr:"LIM", c1:"#009A44", c2:"#FFFFFF", nickname:"The Treaty County",  ground:"TUS Gaelic Grounds",                 sam:2},
  "Tipperary": {province:"Munster",  abbr:"TIP", c1:"#0033A0", c2:"#FFB81C", nickname:"The Premier County", ground:"FBD Semple Stadium, Thurles",        sam:4},
  "Waterford": {province:"Munster",  abbr:"WAT", c1:"#FFFFFF", c2:"#0033A0", tx:"#10243a", nickname:"The Déise", ground:"Fraher Field, Dungarvan",       sam:0},
  "Dublin":    {province:"Leinster", abbr:"DUB", c1:"#6CACE4", c2:"#0C2340", nickname:"The Dubs",           ground:"Parnell Park",                       sam:31},
  "Meath":     {province:"Leinster", abbr:"MEA", c1:"#00843D", c2:"#FFCD00", nickname:"The Royal County",   ground:"Páirc Tailteann, Navan",             sam:7},
  "Kildare":   {province:"Leinster", abbr:"KIL", c1:"#E6E9EC", c2:"#B9C4CE", tx:"#2b3a45", nickname:"The Lilywhites", ground:"St Conleth's Park, Newbridge", sam:4},
  "Laois":     {province:"Leinster", abbr:"LAO", c1:"#0072CE", c2:"#FFFFFF", nickname:"The O'Moore County", ground:"O'Moore Park, Portlaoise",           sam:0},
  "Westmeath": {province:"Leinster", abbr:"WES", c1:"#6F263D", c2:"#FFFFFF", nickname:"The Lake County",    ground:"TEG Cusack Park, Mullingar",         sam:0},
  "Offaly":    {province:"Leinster", abbr:"OFF", c1:"#00843D", c2:"#FFCD00", nickname:"The Faithful County",ground:"Glenisk O'Connor Park, Tullamore",   sam:3},
  "Louth":     {province:"Leinster", abbr:"LOU", c1:"#DA291C", c2:"#FFFFFF", nickname:"The Wee County",     ground:null,                                 sam:3},
  "Wexford":   {province:"Leinster", abbr:"WEX", c1:"#6F263D", c2:"#FFB81C", nickname:"The Model County",   ground:"Chadwicks Wexford Park",             sam:5},
  "Carlow":    {province:"Leinster", abbr:"CAR", c1:"#DA291C", c2:"#009A44", nickname:"The Barrowsiders",   ground:"Netwatch Cullen Park",               sam:0},
  "Wicklow":   {province:"Leinster", abbr:"WIC", c1:"#0033A0", c2:"#FFB81C", nickname:"The Garden County",  ground:"Echelon Park, Aughrim",              sam:0},
  "Longford":  {province:"Leinster", abbr:"LON", c1:"#0033A0", c2:"#FFCD00", nickname:null,                 ground:"Glennon Brothers Pearse Park",       sam:0},
  "Tyrone":    {province:"Ulster",   abbr:"TYR", c1:"#CE1126", c2:"#FFFFFF", nickname:"The Red Hands",      ground:"O'Neills Healy Park, Omagh",         sam:4},
  "Armagh":    {province:"Ulster",   abbr:"ARM", c1:"#FF8200", c2:"#FFFFFF", nickname:"The Orchard County", ground:"BOX-IT Athletic Grounds",            sam:2},
  "Derry":     {province:"Ulster",   abbr:"DER", c1:"#C8102E", c2:"#FFFFFF", nickname:"The Oak Leaf County",ground:"Celtic Park",                        sam:1},
  "Down":      {province:"Ulster",   abbr:"DOW", c1:"#DA291C", c2:"#000000", nickname:"The Mourne County",  ground:"Páirc Esler, Newry",                 sam:5},
  "Donegal":   {province:"Ulster",   abbr:"DON", c1:"#F7C200", c2:"#007A33", nickname:"The Hills",          ground:"MacCumhaill Park, Ballybofey",       sam:2},
  "Cavan":     {province:"Ulster",   abbr:"CAV", c1:"#0033A0", c2:"#FFFFFF", nickname:"The Breffni County", ground:"Kingspan Breffni",                   sam:5},
  "Monaghan":  {province:"Ulster",   abbr:"MON", c1:"#0033A0", c2:"#FFFFFF", nickname:"The Farney County",  ground:"St Tiernach's Park, Clones",         sam:0},
  "Fermanagh": {province:"Ulster",   abbr:"FER", c1:"#009A44", c2:"#FFFFFF", nickname:"The Erne County",    ground:"Brewster Park, Enniskillen",         sam:0},
  "Antrim":    {province:"Ulster",   abbr:"ANT", c1:"#F7C200", c2:"#FFFFFF", nickname:"The Saffrons",       ground:"Corrigan Park, Belfast",             sam:0},
  "Galway":    {province:"Connacht", abbr:"GAL", c1:"#6F263D", c2:"#FFFFFF", nickname:"The Tribesmen",      ground:"Pearse Stadium, Salthill",           sam:9},
  "Mayo":      {province:"Connacht", abbr:"MAY", c1:"#046A38", c2:"#C8102E", nickname:"The Green and Red",  ground:"Hastings Insurance MacHale Park",    sam:3},
  "Roscommon": {province:"Connacht", abbr:"ROS", c1:"#F6EB61", c2:"#0033A0", tx:"#1c2c50", nickname:"The Rossies", ground:"Dr Hyde Park",                sam:2},
  "Sligo":     {province:"Connacht", abbr:"SLI", c1:"#000000", c2:"#FFFFFF", nickname:"The Yeats County",   ground:"Markievicz Park",                    sam:0},
  "Leitrim":   {province:"Connacht", abbr:"LEI", c1:"#009A44", c2:"#FFB81C", nickname:"The Ridge County",   ground:"Páirc Seán Mac Diarmada",            sam:0},
  "New York":  {province:"Connacht", abbr:"NYK", c1:"#0033A0", c2:"#DA291C", nickname:"The Exiles",         ground:"Gaelic Park, New York",              sam:0},
  "London":    {province:"Connacht", abbr:"LDN", c1:"#009A44", c2:"#FFFFFF", nickname:"The Exiles",         ground:"McGovern Park, Ruislip",             sam:0}
};

const teams = [
  {id:"kerry-golden",  county:"Kerry",     name:"The Golden Years",          years:"1975–1986", dec:80, tier:1},
  {id:"kerry-00s",     county:"Kerry",     name:"The Noughties",             years:"2000–2009", dec:0,  tier:1},
  {id:"kerry-20s",     county:"Kerry",     name:"Clifford's Kingdom",        years:"2019–today",dec:20, tier:1},
  {id:"dublin-70s",    county:"Dublin",    name:"Heffo's Army",              years:"1974–1979", dec:80, tier:1},
  {id:"dublin-90s",    county:"Dublin",    name:"The Jacks of '95",          years:"1991–1995", dec:90, tier:2},
  {id:"dublin-10s",    county:"Dublin",    name:"Six in a Row",              years:"2011–2020", dec:10, tier:1},
  {id:"tyrone-00s",    county:"Tyrone",    name:"Mickey Harte's Heroes",     years:"2003–2008", dec:0,  tier:1},
  {id:"tyrone-20s",    county:"Tyrone",    name:"Class of 2021",             years:"2018–today",dec:20, tier:2},
  {id:"mayo-10s",      county:"Mayo",      name:"The Nearly Men",            years:"2011–2021", dec:10, tier:1},
  {id:"donegal-90s",   county:"Donegal",   name:"Sam's First Trip North-West",years:"1990–1993",dec:90, tier:2},
  {id:"donegal-10s",   county:"Donegal",   name:"Jimmy's Winning Matches",   years:"2011–2014", dec:10, tier:1},
  {id:"armagh-00s",    county:"Armagh",    name:"The Orchard's First Sam",   years:"1999–2005", dec:0,  tier:1},
  {id:"armagh-20s",    county:"Armagh",    name:"Geezer's 2024 Champions",   years:"2022–today",dec:20, tier:2},
  {id:"meath-boylan",  county:"Meath",     name:"Boylan's Royals",           years:"1987–1999", dec:90, tier:1},
  {id:"galway-98",     county:"Galway",    name:"The Stylish West",          years:"1998–2001", dec:90, tier:1},
  {id:"galway-20s",    county:"Galway",    name:"Joyce's New Tribe",         years:"2022–today",dec:20, tier:2},
  {id:"cork-89",       county:"Cork",      name:"Back-to-Back Rebels",       years:"1989–1990", dec:90, tier:2},
  {id:"cork-10",       county:"Cork",      name:"Counihan's 2010 Rebels",    years:"2009–2012", dec:10, tier:2},
  {id:"down-60s",      county:"Down",      name:"The Pioneers",              years:"1960–1968", dec:60, tier:1},
  {id:"down-90s",      county:"Down",      name:"The Mourne Machine",        years:"1991–1994", dec:90, tier:2},
  {id:"derry-93",      county:"Derry",     name:"The Boys of '93",           years:"1992–1995", dec:90, tier:2},
  {id:"derry-20s",     county:"Derry",     name:"The Oak Leaf Revival",      years:"2022–today",dec:20, tier:2},
  {id:"offaly-82",     county:"Offaly",    name:"Darby's Day",               years:"1980–1982", dec:80, tier:2},
  {id:"roscommon-80",  county:"Roscommon", name:"Primrose Pride",            years:"1977–1980", dec:80, tier:2},
  {id:"monaghan-15",   county:"Monaghan",  name:"Farney Defiance",           years:"2013–2019", dec:10, tier:2},
  {id:"kildare-98",    county:"Kildare",   name:"Micko's Lilywhites",        years:"1997–2000", dec:90, tier:3},
  {id:"laois-03",      county:"Laois",     name:"O'Dwyer's Last Dance",      years:"2003–2005", dec:0,  tier:3},
  {id:"westmeath-04",  county:"Westmeath", name:"Páidí's Lake County Miracle",years:"2004",     dec:0,  tier:3},
  {id:"fermanagh-04",  county:"Fermanagh", name:"The Erne Dreamers",         years:"2003–2008", dec:0,  tier:3},
  {id:"cavan-20",      county:"Cavan",     name:"Breffni Lightning",         years:"2019–2021", dec:20, tier:3},
  {id:"clare-92",      county:"Clare",     name:"The Banner Risen",          years:"1992",      dec:90, tier:3},
  {id:"louth-25",      county:"Louth",     name:"The Wee County Risen",      years:"2023–today",dec:20, tier:3},
  {id:"leitrim-94",    county:"Leitrim",   name:"Connacht Kings of '94",     years:"1994",      dec:90, tier:3},
  {id:"sligo-07",      county:"Sligo",     name:"The Yeats County Breakthrough",years:"2007",   dec:0,  tier:3},
  {id:"dublin-00s",    county:"Dublin",    name:"The Nearly Men of the Noughties",years:"2002–2009",dec:0,tier:2},
  {id:"derry-00s",     county:"Derry",     name:"Bradley's Oak Leafers",     years:"2004–2008", dec:0,  tier:2},
  {id:"down-10",       county:"Down",      name:"The 2010 Final Run",        years:"2008–2012", dec:10, tier:2},
  {id:"galway-10",     county:"Galway",    name:"Meehan's Maroon Years",     years:"2008–2013", dec:10, tier:2},
  {id:"kildare-10",    county:"Kildare",   name:"McGeeney's White Heat",     years:"2008–2012", dec:10, tier:2},
  {id:"tipperary-20",  county:"Tipperary", name:"The 2020 Breakthrough",     years:"2016–2020", dec:20, tier:3},
  {id:"monaghan-80s",  county:"Monaghan",  name:"Nudie's Farneymen",         years:"1985–1988", dec:80, tier:2},
  {id:"wexford-08",    county:"Wexford",   name:"Forde's Model Men",         years:"2004–2008", dec:0,  tier:3},
  {id:"antrim-09",     county:"Antrim",    name:"The Saffron Surge",         years:"2008–2010", dec:0,  tier:3},
  {id:"carlow-18",     county:"Carlow",    name:"Turlough's Tribe",          years:"2017–2019", dec:20, tier:3},
  {id:"limerick-04",   county:"Limerick",  name:"The Treaty Risers",         years:"2000–2004", dec:0,  tier:3},
  {id:"roscommon-17",  county:"Roscommon", name:"Smith's Rossies",           years:"2017–2019", dec:20, tier:3}
];

/* [teamId, name, line, rating, club, allIrelands, allStars] — null = TBD */
const P = [
/* ---- Kerry, The Golden Years ---- */
["kerry-golden","Charlie Nelligan","GK",84,"Austin Stacks",7,null],
["kerry-golden","Páidí Ó Sé","DEF",92,"An Ghaeltacht",8,5],
["kerry-golden","John O'Keeffe","DEF",86,"Austin Stacks",4,3],
["kerry-golden","Tim Kennelly","DEF",84,"Listowel Emmets",5,1],
["kerry-golden","Jimmy Deenihan","DEF",84,"Finuge",5,null],
["kerry-golden","Tommy Doyle","DEF",83,null,null,null],
["kerry-golden","Mick Spillane","DEF",81,"Templenoe",null,null],
["kerry-golden","Jack O'Shea","MID",95,"St Mary's Cahersiveen",7,6],
["kerry-golden","Seán Walsh","MID",84,null,7,null],
["kerry-golden","Pat Spillane","FWD",95,"Templenoe",8,9],
["kerry-golden","Mikey Sheehy","FWD",95,"Austin Stacks",8,7],
["kerry-golden","Eoin 'Bomber' Liston","FWD",87,"Beale",7,null],
["kerry-golden","John Egan","FWD",85,"Sneem",6,null],
["kerry-golden","Ger Power","FWD",87,"Austin Stacks",8,6],
["kerry-golden","Ogie Moran","FWD",85,"Beale",8,null],
/* ---- Kerry, The Noughties ---- */
["kerry-00s","Diarmuid Murphy","GK",83,null,4,1],
["kerry-00s","Séamus Moynihan","DEF",87,"Glenflesk",4,2],
["kerry-00s","Tomás Ó Sé","DEF",88,"An Ghaeltacht",5,5],
["kerry-00s","Marc Ó Sé","DEF",87,"An Ghaeltacht",5,3],
["kerry-00s","Tom O'Sullivan","DEF",84,null,5,null],
["kerry-00s","Mike McCarthy","DEF",84,"Kilcummin",4,3],
["kerry-00s","Aidan O'Mahony","DEF",83,"Rathmore",5,2],
["kerry-00s","Darragh Ó Sé","MID",89,"An Ghaeltacht",6,4],
["kerry-00s","William Kirby","MID",81,null,3,null],
["kerry-00s","Colm 'Gooch' Cooper","FWD",95,"Dr Crokes",5,8],
["kerry-00s","Declan O'Sullivan","FWD",87,"Dromid Pearses",5,2],
["kerry-00s","Kieran Donaghy","FWD",86,"Austin Stacks",4,3],
["kerry-00s","Paul Galvin","FWD",86,"Finuge",4,3],
["kerry-00s","Mike Frank Russell","FWD",83,"Laune Rangers",3,null],
["kerry-00s","Dara Ó Cinnéide","FWD",83,"An Ghaeltacht",3,null],
/* ---- Kerry, Clifford's Kingdom ---- */
["kerry-20s","Shane Ryan","GK",84,"Rathmore",1,1],
["kerry-20s","Tom O'Sullivan","DEF",85,"Dingle",1,1],
["kerry-20s","Gavin White","DEF",85,"Dr Crokes",1,1],
["kerry-20s","Jason Foley","DEF",84,"Ballydonoghue",1,1],
["kerry-20s","Tadhg Morley","DEF",83,"Templenoe",1,null],
["kerry-20s","Brian Ó Beaglaoich","DEF",82,"An Ghaeltacht",1,null],
["kerry-20s","Graham O'Sullivan","DEF",81,"Dromid Pearses",1,null],
["kerry-20s","Diarmuid O'Connor","MID",83,"Na Gaeil",1,null],
["kerry-20s","Joe O'Connor","MID",83,"Austin Stacks",1,1],
["kerry-20s","David Clifford","FWD",95,"Fossa",1,5],
["kerry-20s","Seán O'Shea","FWD",88,"Kenmare Shamrocks",1,2],
["kerry-20s","Paudie Clifford","FWD",87,"Fossa",1,2],
["kerry-20s","Paul Geaney","FWD",83,"Dingle",2,1],
["kerry-20s","Tony Brosnan","FWD",80,"Dr Crokes",1,null],
/* ---- Dublin, Heffo's Army ---- */
["dublin-70s","Paddy Cullen","GK",85,null,3,3],
["dublin-70s","Kevin Moran","DEF",87,"Good Counsel",2,null],
["dublin-70s","Tommy Drumm","DEF",83,"Whitehall Colmcille",3,null],
["dublin-70s","Robbie Kelleher","DEF",83,"Scoil Uí Chonaill",3,null],
["dublin-70s","Seán Doherty","DEF",83,null,3,null],
["dublin-70s","Gay O'Driscoll","DEF",82,"St Vincent's",3,null],
["dublin-70s","Brian Mullins","MID",89,"St Vincent's",4,null],
["dublin-70s","Bernard Brogan Snr","MID",82,"St Oliver Plunketts",3,null],
["dublin-70s","Jimmy Keaveney","FWD",88,"St Vincent's",3,3],
["dublin-70s","Anton O'Toole","FWD",85,"Synge Street",4,null],
["dublin-70s","David Hickey","FWD",84,"Raheny",3,null],
["dublin-70s","Tony Hanahoe","FWD",84,"St Vincent's",3,null],
["dublin-70s","Bobby Doyle","FWD",83,"St Vincent's",3,null],
["dublin-70s","John McCarthy","FWD",81,"Na Fianna",3,null],
/* ---- Dublin, The Jacks of '95 ---- */
["dublin-90s","John O'Leary","GK",86,"O'Dwyers",2,2],
["dublin-90s","Paul Curran","DEF",86,"Thomas Davis",1,2],
["dublin-90s","Keith Barr","DEF",85,"Erin's Isle",1,null],
["dublin-90s","Eamonn Heery","DEF",82,null,1,null],
["dublin-90s","Mick Deegan","DEF",81,"Erin's Isle",1,null],
["dublin-90s","Ciarán Walsh","DEF",80,null,1,null],
["dublin-90s","Brian Stynes","MID",82,"Ballyboden St Enda's",1,null],
["dublin-90s","Paul Bealin","MID",82,null,1,null],
["dublin-90s","Jack Sheedy","MID",81,"Lucan Sarsfields",null,null],
["dublin-90s","Charlie Redmond","FWD",84,"Erin's Isle",1,null],
["dublin-90s","Dessie Farrell","FWD",83,"Na Fianna",1,1],
["dublin-90s","Jason Sherlock","FWD",83,null,1,1],
["dublin-90s","Mick Galvin","FWD",81,null,1,null],
["dublin-90s","Vinnie Murphy","FWD",80,null,null,null],
/* ---- Dublin, Six in a Row ---- */
["dublin-10s","Stephen Cluxton","GK",95,"Parnells",9,2],
["dublin-10s","Jack McCaffrey","DEF",90,"Clontarf",6,3],
["dublin-10s","James McCarthy","DEF",87,"Ballymun Kickhams",9,4],
["dublin-10s","Cian O'Sullivan","DEF",86,"Kilmacud Crokes",8,2],
["dublin-10s","Philly McMahon","DEF",85,"Ballymun Kickhams",8,2],
["dublin-10s","Jonny Cooper","DEF",84,"Na Fianna",7,null],
["dublin-10s","Mick Fitzsimons","DEF",84,"Cuala",9,1],
["dublin-10s","Brian Fenton","MID",91,"Raheny",7,5],
["dublin-10s","Michael Darragh Macauley","MID",85,"Ballyboden St Enda's",8,1],
["dublin-10s","Con O'Callaghan","FWD",88,"Cuala",6,3],
["dublin-10s","Ciarán Kilkenny","FWD",87,"Castleknock",8,4],
["dublin-10s","Diarmuid Connolly","FWD",92,"St Vincent's",6,2],
["dublin-10s","Bernard Brogan","FWD",87,"St Oliver Plunketts ER",7,4],
["dublin-10s","Paul Mannion","FWD",86,"Kilmacud Crokes",6,2],
["dublin-10s","Paul Flynn","FWD",86,"Fingallians",6,4],
["dublin-10s","Dean Rock","FWD",85,"Ballymun Kickhams",7,1],
["dublin-10s","Kevin McManamon","FWD",83,"St Jude's",8,null],
/* ---- Tyrone, Mickey Harte's Heroes ---- */
["tyrone-00s","Pascal McConnell","GK",81,"Newtownstewart",3,null],
["tyrone-00s","Conor Gormley","DEF",86,"Carrickmore",3,3],
["tyrone-00s","Philip Jordan","DEF",86,"Moy",3,3],
["tyrone-00s","Ryan McMenamin","DEF",84,"Dromore",3,2],
["tyrone-00s","Davy Harte","DEF",81,null,3,null],
["tyrone-00s","Joe McMahon","DEF",81,"Omagh St Enda's",3,null],
["tyrone-00s","Ciarán Gourley","DEF",80,null,3,null],
["tyrone-00s","Seán Cavanagh","MID",89,"Moy",3,5],
["tyrone-00s","Enda McGinley","MID",83,"Errigal Ciarán",3,1],
["tyrone-00s","Kevin Hughes","MID",83,"Killeeshil",3,null],
["tyrone-00s","Peter Canavan","FWD",95,"Errigal Ciarán",2,6],
["tyrone-00s","Stephen O'Neill","FWD",88,"Clann na nGael",3,2],
["tyrone-00s","Brian Dooher","FWD",87,null,3,3],
["tyrone-00s","Brian McGuigan","FWD",86,"Ardboe",3,1],
["tyrone-00s","Owen Mulligan","FWD",85,"Cookstown Fr Rock's",3,1],
/* ---- Tyrone, Class of 2021 ---- */
["tyrone-20s","Niall Morgan","GK",86,"Edendork",1,1],
["tyrone-20s","Pádraig Hampsey","DEF",84,"Coalisland",1,1],
["tyrone-20s","Peter Harte","DEF",84,"Errigal Ciarán",1,null],
["tyrone-20s","Kieran McGeary","DEF",84,"Pomeroy",1,1],
["tyrone-20s","Conor Meyler","DEF",84,"Omagh St Enda's",1,1],
["tyrone-20s","Ronan McNamee","DEF",83,"Aghyaran",1,null],
["tyrone-20s","Michael McKernan","DEF",81,"Coalisland",1,null],
["tyrone-20s","Conn Kilpatrick","MID",80,"Edendork",1,null],
["tyrone-20s","Brian Kennedy","MID",79,"Dungannon",1,null],
["tyrone-20s","Darragh Canavan","FWD",87,"Errigal Ciarán",1,1],
["tyrone-20s","Mattie Donnelly","FWD",84,"Trillick",1,null],
["tyrone-20s","Darren McCurry","FWD",83,"Edendork",1,1],
["tyrone-20s","Cathal McShane","FWD",83,"Owen Roe O'Neills",1,1],
["tyrone-20s","Niall Sludden","FWD",80,"Dromore",1,null],
/* ---- Mayo, The Nearly Men ---- */
["mayo-10s","David Clarke","GK",85,"Ballina Stephenites",0,2],
["mayo-10s","Lee Keegan","DEF",90,"Westport",0,5],
["mayo-10s","Keith Higgins","DEF",86,"Ballyhaunis",0,4],
["mayo-10s","Colm Boyle","DEF",85,"Davitts",0,3],
["mayo-10s","Paddy Durcan","DEF",85,"Castlebar Mitchels",0,2],
["mayo-10s","Chris Barrett","DEF",83,"Belmullet",0,2],
["mayo-10s","Brendan Harrison","DEF",81,"Aghamore",0,1],
["mayo-10s","Aidan O'Shea","MID",87,"Breaffy",0,3],
["mayo-10s","Séamus O'Shea","MID",82,"Breaffy",0,null],
["mayo-10s","Tom Parsons","MID",82,"Charlestown",0,null],
["mayo-10s","Cillian O'Connor","FWD",88,"Ballintubber",0,3],
["mayo-10s","Andy Moran","FWD",86,"Ballaghaderreen",0,2],
["mayo-10s","Diarmuid O'Connor","FWD",83,"Ballintubber",0,1],
["mayo-10s","Kevin McLoughlin","FWD",83,"Knockmore",0,null],
["mayo-10s","Jason Doherty","FWD",81,"Burrishoole",0,null],
/* ---- Donegal, Sam's First Trip North-West ---- */
["donegal-90s","Gary Walsh","GK",83,"Aodh Ruadh",1,null],
["donegal-90s","Martin Gavigan","DEF",82,null,1,1],
["donegal-90s","Matt Gallagher","DEF",81,null,1,null],
["donegal-90s","John Joe Doherty","DEF",80,null,1,null],
["donegal-90s","Donal Reid","DEF",79,null,1,null],
["donegal-90s","Noel Hegarty","DEF",79,null,1,null],
["donegal-90s","Anthony Molloy","MID",86,"Ardara",1,1],
["donegal-90s","Brian Murray","MID",81,null,1,null],
["donegal-90s","Martin McHugh","FWD",88,"Kilcar",1,2],
["donegal-90s","Tony Boyle","FWD",85,"Dungloe",1,1],
["donegal-90s","Manus Boyle","FWD",83,"Killybegs",1,null],
["donegal-90s","Declan Bonner","FWD",82,"Na Rossa",1,null],
["donegal-90s","Joyce McMullan","FWD",80,null,1,null],
["donegal-90s","James McHugh","FWD",80,"Kilcar",1,null],
/* ---- Donegal, Jimmy's Winning Matches ---- */
["donegal-10s","Paul Durcan","GK",84,"Four Masters",1,1],
["donegal-10s","Karl Lacey","DEF",88,"Four Masters",1,4],
["donegal-10s","Neil McGee","DEF",86,"Gaoth Dobhair",1,2],
["donegal-10s","Frank McGlynn","DEF",84,"Glenfin",1,1],
["donegal-10s","Mark McHugh","DEF",83,"Kilcar",1,1],
["donegal-10s","Eamon McGee","DEF",82,"Gaoth Dobhair",1,null],
["donegal-10s","Anthony Thompson","DEF",82,"Naomh Conaill",1,null],
["donegal-10s","Neil Gallagher","MID",84,"Glenswilly",1,1],
["donegal-10s","Rory Kavanagh","MID",82,"St Eunan's",1,null],
["donegal-10s","Michael Murphy","FWD",91,"Glenswilly",1,3],
["donegal-10s","Colm McFadden","FWD",86,"St Michael's",1,2],
["donegal-10s","Ryan McHugh","FWD",86,"Kilcar",0,2],
["donegal-10s","Patrick McBrearty","FWD",85,"Kilcar",1,1],
["donegal-10s","Leo McLoone","FWD",80,"Naomh Conaill",1,null],
/* ---- Armagh, The Orchard's First Sam ---- */
["armagh-00s","Benny Tierney","GK",81,"Mullaghbawn",1,null],
["armagh-00s","Kieran McGeeney","DEF",89,"Mullaghbawn",1,3],
["armagh-00s","Enda McNulty","DEF",83,"Mullaghbawn",1,1],
["armagh-00s","Francie Bellew","DEF",83,"Crossmaglen Rangers",1,1],
["armagh-00s","Justin McNulty","DEF",82,"Mullaghbawn",1,null],
["armagh-00s","Aidan O'Rourke","DEF",82,"Dromintee",1,null],
["armagh-00s","Andy McCann","DEF",80,null,1,null],
["armagh-00s","Paul McGrane","MID",85,"Ballyhegan",1,1],
["armagh-00s","John Toal","MID",81,"Keady",1,null],
["armagh-00s","Oisín McConville","FWD",88,"Crossmaglen Rangers",1,1],
["armagh-00s","Stevie McDonnell","FWD",88,"Killeavy",1,3],
["armagh-00s","Ronan Clarke","FWD",84,"Pearse Óg",1,1],
["armagh-00s","Diarmaid Marsden","FWD",83,"Clan na Gael",1,1],
["armagh-00s","John McEntee","FWD",82,"Crossmaglen Rangers",1,null],
["armagh-00s","Paddy McKeever","FWD",80,"Ballyhegan",1,null],
/* ---- Armagh, Geezer's 2024 Champions ---- */
["armagh-20s","Ethan Rafferty","GK",83,"Grange",1,null],
["armagh-20s","Barry McCambridge","DEF",83,"Clan na Gael",1,1],
["armagh-20s","Aidan Forker","DEF",83,"Maghery",1,null],
["armagh-20s","Aaron McKay","DEF",82,"Dromintee",1,null],
["armagh-20s","Paddy Burns","DEF",81,"Burren",1,null],
["armagh-20s","Joe McElroy","DEF",79,"Armagh Harps",1,null],
["armagh-20s","Ben Crealey","MID",81,"Maghery",1,null],
["armagh-20s","Jarly Óg Burns","MID",81,"Silverbridge",1,null],
["armagh-20s","Niall Grimley","MID",80,"Madden",1,null],
["armagh-20s","Rian O'Neill","FWD",88,"Crossmaglen Rangers",1,null],
["armagh-20s","Oisín Conaty","FWD",83,"Tír na nÓg",1,1],
["armagh-20s","Conor Turbitt","FWD",83,"Clann Éireann",1,null],
["armagh-20s","Rory Grugan","FWD",82,"Ballymacnab",1,null],
["armagh-20s","Andrew Murnin","FWD",81,"St Paul's",1,null],
["armagh-20s","Stefan Campbell","FWD",81,"Clan na Gael",1,null],
/* ---- Meath, Boylan's Royals ---- */
["meath-boylan","Michael McQuillan","GK",81,null,2,null],
["meath-boylan","Martin O'Connell","DEF",87,"St Michael's",3,3],
["meath-boylan","Mick Lyons","DEF",87,"Summerhill",2,2],
["meath-boylan","Darren Fay","DEF",87,"Trim",2,2],
["meath-boylan","Robbie O'Malley","DEF",86,"St Michael's",3,2],
["meath-boylan","Mark O'Reilly","DEF",83,"Summerhill",2,1],
["meath-boylan","Kevin Foley","DEF",81,"Trim",2,null],
["meath-boylan","John McDermott","MID",86,null,2,2],
["meath-boylan","Liam Hayes","MID",84,"Skryne",2,1],
["meath-boylan","Gerry McEntee","MID",83,null,2,null],
["meath-boylan","Trevor Giles","FWD",90,"Skryne",2,3],
["meath-boylan","Graham Geraghty","FWD",88,"Seneschalstown",2,3],
["meath-boylan","Colm O'Rourke","FWD",87,"Skryne",2,2],
["meath-boylan","Bernard Flynn","FWD",85,null,2,2],
["meath-boylan","Tommy Dowd","FWD",85,null,2,1],
["meath-boylan","Ollie Murphy","FWD",83,"Carnaross",1,1],
/* ---- Galway, The Stylish West ---- */
["galway-98","Martin McNamara","GK",82,"Corofin",2,null],
["galway-98","Seán Óg de Paor","DEF",86,"An Cheathrú Rua",2,2],
["galway-98","Tomás Mannion","DEF",83,null,2,null],
["galway-98","Gary Fahey","DEF",83,"Killannin",2,null],
["galway-98","Ray Silke","DEF",81,"Corofin",2,null],
["galway-98","John Divilly","DEF",80,null,2,null],
["galway-98","Kevin Walsh","MID",85,"Killannin",2,1],
["galway-98","Seán Ó Domhnaill","MID",83,"An Cheathrú Rua",2,1],
["galway-98","Pádraic Joyce","FWD",89,"Killererin",2,2],
["galway-98","Michael Donnellan","FWD",89,"Dunmore MacHales",2,2],
["galway-98","Ja Fallon","FWD",88,"Tuam Stars",2,2],
["galway-98","Derek Savage","FWD",82,"Cortoon Shamrocks",2,null],
["galway-98","Paul Clancy","FWD",81,null,2,null],
["galway-98","Niall Finnegan","FWD",80,"Salthill",2,null],
/* ---- Galway, Joyce's New Tribe ---- */
["galway-20s","Connor Gleeson","GK",80,"Dunmore MacHales",0,null],
["galway-20s","Seán Kelly","DEF",84,"Moycullen",0,1],
["galway-20s","Dylan McHugh","DEF",83,"Corofin",0,1],
["galway-20s","Liam Silke","DEF",83,"Corofin",0,null],
["galway-20s","John Daly","DEF",82,"Mountbellew-Moylough",0,null],
["galway-20s","Jack Glynn","DEF",81,"Claregalway",0,null],
["galway-20s","Paul Conroy","MID",85,"St James'",0,1],
["galway-20s","Cillian McDaid","MID",83,"Monivea-Abbey",0,1],
["galway-20s","John Maher","MID",81,"Salthill-Knocknacarra",0,null],
["galway-20s","Shane Walsh","FWD",88,"Kilkerrin-Clonberne",0,1],
["galway-20s","Damien Comer","FWD",87,"Annaghdown",0,2],
["galway-20s","Rob Finnerty","FWD",83,"Salthill-Knocknacarra",0,null],
["galway-20s","Matthew Tierney","FWD",81,"Oughterard",0,null],
["galway-20s","Johnny Heaney","FWD",80,"Killannin",0,null],
/* ---- Cork, Back-to-Back Rebels ---- */
["cork-89","John Kerins","GK",83,"St Finbarr's",2,1],
["cork-89","Niall Cahalane","DEF",85,"Castlehaven",2,1],
["cork-89","Stephen O'Brien","DEF",83,"Nemo Rangers",2,1],
["cork-89","Conor Counihan","DEF",83,"Aghada",2,1],
["cork-89","Tony Davis","DEF",82,"Castlehaven",2,1],
["cork-89","Jimmy Kerrigan","DEF",81,"Nemo Rangers",1,null],
["cork-89","Shea Fahy","MID",85,"Nemo Rangers",2,1],
["cork-89","Teddy McCarthy","MID",83,"Sarsfields",2,1],
["cork-89","Danny Culloty","MID",80,null,2,null],
["cork-89","Larry Tompkins","FWD",89,"Castlehaven",2,3],
["cork-89","Colm O'Neill","FWD",83,null,2,null],
["cork-89","Dave Barry","FWD",82,"St Finbarr's",2,1],
["cork-89","John Cleary","FWD",82,"Castlehaven",1,null],
["cork-89","Paul McGrath","FWD",80,null,2,null],
/* ---- Cork, Counihan's 2010 Rebels ---- */
["cork-10","Alan Quirke","GK",81,"Valley Rovers",1,null],
["cork-10","Graham Canty","DEF",86,"Bantry Blues",1,2],
["cork-10","Michael Shields","DEF",83,"St Finbarr's",1,1],
["cork-10","John Miskella","DEF",82,"Ballincollig",1,1],
["cork-10","Eoin Cadogan","DEF",81,"Douglas",1,null],
["cork-10","Noel O'Leary","DEF",81,"Cill na Martra",1,null],
["cork-10","Aidan Walsh","MID",83,"Kanturk",1,1],
["cork-10","Nicholas Murphy","MID",82,"Carrigaline",1,null],
["cork-10","Alan O'Connor","MID",81,"St Colum's",1,null],
["cork-10","Daniel Goulding","FWD",84,"Éire Óg",1,1],
["cork-10","Donncha O'Connor","FWD",83,"Ballydesmond",1,1],
["cork-10","Colm O'Neill","FWD",83,"Ballyclough",1,1],
["cork-10","Paul Kerrigan","FWD",82,"Nemo Rangers",1,null],
["cork-10","Pearse O'Neill","FWD",81,"Aghada",1,null],
["cork-10","Ciarán Sheehan","FWD",81,"Éire Óg",1,null],
/* ---- Down, The Pioneers ---- */
["down-60s","Eamonn McKay","GK",79,null,3,null],
["down-60s","Leo Murphy","DEF",81,null,2,null],
["down-60s","Dan McCartan","DEF",83,null,3,null],
["down-60s","Tom O'Hare","DEF",81,null,1,null],
["down-60s","George Lavery","DEF",80,null,2,null],
["down-60s","Joe Lennon","MID",83,null,3,null],
["down-60s","Colm McAlarney","MID",84,null,1,null],
["down-60s","Jarlath Carey","MID",79,null,2,null],
["down-60s","Seán O'Neill","FWD",90,null,3,null],
["down-60s","Paddy Doherty","FWD",88,"Ballykinlar",3,null],
["down-60s","James McCartan Snr","FWD",85,null,3,null],
["down-60s","Patsy O'Hagan","FWD",80,null,2,null],
["down-60s","Brian Johnston","FWD",79,null,2,null],
/* ---- Down, The Mourne Machine ---- */
["down-90s","Neil Collins","GK",81,null,2,null],
["down-90s","Conor Deegan","DEF",83,"Burren",2,1],
["down-90s","DJ Kane","DEF",82,null,2,null],
["down-90s","Barry Breen","DEF",81,null,2,null],
["down-90s","Paul Higgins","DEF",80,null,2,null],
["down-90s","John Kelly","DEF",79,null,1,null],
["down-90s","Gregory McCartan","MID",81,"Tullylish",1,null],
["down-90s","Eamonn Burns","MID",80,null,2,null],
["down-90s","Mickey Linden","FWD",88,"Mayobridge",2,1],
["down-90s","Greg Blaney","FWD",87,null,2,2],
["down-90s","James McCartan","FWD",87,"Tullylish",2,2],
["down-90s","Ross Carr","FWD",85,"Clonduff",2,1],
["down-90s","Peter Withnell","FWD",81,null,1,null],
["down-90s","Gary Mason","FWD",80,null,1,null],
/* ---- Derry, The Boys of '93 ---- */
["derry-93","Damien McCusker","GK",80,"Glen",1,null],
["derry-93","Henry Downey","DEF",87,"Lavey",1,2],
["derry-93","Tony Scullion","DEF",86,"Ballinascreen",1,3],
["derry-93","Kieran McKeever","DEF",83,"Dungiven",1,1],
["derry-93","Johnny McGurk","DEF",82,"Lavey",1,1],
["derry-93","Gary Coleman","DEF",80,null,1,null],
["derry-93","Anthony Tohill","MID",90,"Swatragh",1,3],
["derry-93","Brian McGilligan","MID",86,"Dungiven",1,1],
["derry-93","Joe Brolly","FWD",84,"Dungiven",1,1],
["derry-93","Enda Gormley","FWD",84,"Glen",1,1],
["derry-93","Damian Cassidy","FWD",80,"Bellaghy",1,null],
["derry-93","Damian Barton","FWD",80,null,1,null],
["derry-93","Seamus Downey","FWD",80,"Lavey",1,null],
["derry-93","Dermot Heaney","FWD",79,null,1,null],
/* ---- Derry, The Oak Leaf Revival ---- */
["derry-20s","Odhrán Lynch","GK",80,"Magherafelt",0,null],
["derry-20s","Chrissy McKaigue","DEF",85,"Slaughtneil",0,1],
["derry-20s","Brendan Rogers","DEF",85,"Slaughtneil",0,1],
["derry-20s","Eoin McEvoy","DEF",83,"Magherafelt",0,1],
["derry-20s","Gareth McKinless","DEF",83,"Ballinderry",0,null],
["derry-20s","Conor McCluskey","DEF",82,"Magherafelt",0,null],
["derry-20s","Conor Glass","MID",88,"Glen",0,1],
["derry-20s","Emmett Bradley","MID",79,"Glen",0,null],
["derry-20s","Shane McGuigan","FWD",87,"Slaughtneil",0,1],
["derry-20s","Ethan Doherty","FWD",82,"Glen",0,null],
["derry-20s","Paul Cassidy","FWD",81,"Bellaghy",0,null],
["derry-20s","Lachlan Murray","FWD",80,"Desertmartin",0,null],
["derry-20s","Niall Loughlin","FWD",79,"Greenlough",0,null],
/* ---- Offaly, Darby's Day ---- */
["offaly-82","Martin Furlong","GK",84,"Tullamore",3,1],
["offaly-82","Seán Lowry","DEF",82,"Ferbane",3,null],
["offaly-82","Mick Fitzgerald","DEF",80,null,1,null],
["offaly-82","Pat Fitzgerald","DEF",79,null,1,null],
["offaly-82","Liam O'Connor","DEF",79,"Walsh Island",1,null],
["offaly-82","Liam Currams","DEF",82,null,1,1],
["offaly-82","Richie Connor","MID",82,"Walsh Island",1,null],
["offaly-82","Pádraic Dunne","MID",80,null,1,null],
["offaly-82","Tomás O'Connor","MID",79,"Walsh Island",1,null],
["offaly-82","Matt Connor","FWD",90,"Walsh Island",1,3],
["offaly-82","Brendan Lowry","FWD",81,"Ferbane",1,1],
["offaly-82","Johnny Mooney","FWD",81,null,1,1],
["offaly-82","Gerry Carroll","FWD",78,null,1,null],
["offaly-82","Seamus Darby","FWD",80,"Rhode",1,null],
/* ---- Roscommon, Primrose Pride ---- */
["roscommon-80","Gay Sheerin","GK",78,null,0,null],
["roscommon-80","Harry Keegan","DEF",83,"Castlerea St Kevin's",0,3],
["roscommon-80","Pat Lindsay","DEF",81,null,0,1],
["roscommon-80","Tom Heneghan","DEF",80,null,0,1],
["roscommon-80","Danny Murray","DEF",81,null,0,2],
["roscommon-80","Gerry Fitzmaurice","DEF",78,null,0,null],
["roscommon-80","Dermot Earley","MID",88,"Michael Glaveys",0,2],
["roscommon-80","Seamus Hayden","MID",78,null,0,null],
["roscommon-80","Tony McManus","FWD",84,"Clann na nGael",0,1],
["roscommon-80","Michael Finneran","FWD",80,null,0,1],
["roscommon-80","John O'Connor","FWD",77,null,0,null],
["roscommon-80","Eamonn McManus","FWD",77,null,0,null],
/* ---- Monaghan, Farney Defiance ---- */
["monaghan-15","Rory Beggan","GK",87,"Scotstown",0,1],
["monaghan-15","Drew Wylie","DEF",81,"Ballybay",0,null],
["monaghan-15","Ryan Wylie","DEF",80,"Ballybay",0,null],
["monaghan-15","Colin Walshe","DEF",81,"Doohamlet",0,1],
["monaghan-15","Vinny Corey","DEF",82,"Clontibret",0,null],
["monaghan-15","Karl O'Connell","DEF",82,"Tyholland",0,1],
["monaghan-15","Dessie Mone","DEF",78,"Clontibret",0,null],
["monaghan-15","Darren Hughes","MID",83,"Scotstown",0,null],
["monaghan-15","Fintan Kelly","MID",79,null,0,null],
["monaghan-15","Conor McManus","FWD",89,"Clontibret",0,3],
["monaghan-15","Kieran Hughes","FWD",82,"Scotstown",0,null],
["monaghan-15","Jack McCarron","FWD",81,"Currin",0,null],
["monaghan-15","Conor McCarthy","FWD",79,"Scotstown",0,null],
["monaghan-15","Shane Carey","FWD",77,null,0,null],
/* ---- Kildare, Micko's Lilywhites ---- */
["kildare-98","Christy Byrne","GK",76,null,0,null],
["kildare-98","Glenn Ryan","DEF",83,"Round Towers",0,1],
["kildare-98","Anthony Rainbow","DEF",80,"Suncroft",0,1],
["kildare-98","Brian Lacey","DEF",79,null,0,1],
["kildare-98","John Finn","DEF",75,null,0,null],
["kildare-98","Ken Doyle","DEF",74,null,0,null],
["kildare-98","Niall Buckley","MID",82,"Sarsfields",0,1],
["kildare-98","Willie McCreery","MID",78,null,0,null],
["kildare-98","Dermot Earley Jnr","MID",81,"Sarsfields",0,1],
["kildare-98","Martin Lynch","FWD",78,null,0,null],
["kildare-98","Karl O'Dwyer","FWD",76,null,0,null],
["kildare-98","Eddie McCormack","FWD",75,null,0,null],
["kildare-98","Brian Murphy","FWD",76,null,0,null],
/* ---- Laois, O'Dwyer's Last Dance ---- */
["laois-03","Fergal Byron","GK",78,null,0,1],
["laois-03","Joe Higgins","DEF",79,null,0,1],
["laois-03","Tom Kelly","DEF",80,null,0,1],
["laois-03","Aidan Fennelly","DEF",75,null,0,null],
["laois-03","Darren Rooney","DEF",74,null,0,null],
["laois-03","Pádraig Clancy","MID",79,"Timahoe",0,null],
["laois-03","Noel Garvan","MID",76,null,0,null],
["laois-03","Colm Parkinson","MID",75,"Portlaoise",0,null],
["laois-03","Ross Munnelly","FWD",82,"Arles-Kilcruise",0,null],
["laois-03","Brian 'Beano' McDonald","FWD",79,"Portlaoise",0,null],
["laois-03","Chris Conway","FWD",76,"Arles-Kilcruise",0,null],
["laois-03","Ian Fitzgerald","FWD",76,null,0,null],
["laois-03","Billy Sheehan","FWD",75,null,0,null],
/* ---- Westmeath, Páidí's Lake County Miracle ---- */
["westmeath-04","Gary Connaughton","GK",79,"Tubberclair",0,1],
["westmeath-04","John Keane","DEF",81,null,0,1],
["westmeath-04","Michael Ennis","DEF",75,null,0,null],
["westmeath-04","Fergal Wilson","DEF",75,null,0,null],
["westmeath-04","Damien Gavin","DEF",74,null,0,null],
["westmeath-04","Brian Morley","DEF",73,null,0,null],
["westmeath-04","Rory O'Connell","MID",78,null,0,null],
["westmeath-04","David O'Shaughnessy","MID",76,null,0,null],
["westmeath-04","Dessie Dolan","FWD",83,"Garrycastle",0,null],
["westmeath-04","Denis Glennon","FWD",77,null,0,null],
["westmeath-04","Alan Mangan","FWD",76,null,0,null],
["westmeath-04","Martin Flanagan","FWD",74,null,0,null],
/* ---- Fermanagh, The Erne Dreamers ---- */
["fermanagh-04","Ronan Gallagher","GK",73,null,0,null],
["fermanagh-04","Barry Owens","DEF",81,"Teemore Shamrocks",0,2],
["fermanagh-04","Ryan McCluskey","DEF",76,null,0,null],
["fermanagh-04","Shane McDermott","DEF",74,null,0,null],
["fermanagh-04","Niall Bogue","DEF",73,null,0,null],
["fermanagh-04","Marty McGrath","MID",80,"Ederney",0,1],
["fermanagh-04","James Sherry","MID",74,null,0,null],
["fermanagh-04","Liam McBarron","MID",74,null,0,null],
["fermanagh-04","Tom Brewster","FWD",77,null,0,null],
["fermanagh-04","Stephen Maguire","FWD",76,null,0,null],
["fermanagh-04","Mark Little","FWD",75,null,0,null],
["fermanagh-04","Eamon Maguire","FWD",74,null,0,null],
/* ---- Cavan, Breffni Lightning ---- */
["cavan-20","Raymond Galligan","GK",80,"Lacken",0,null],
["cavan-20","Padraig Faulkner","DEF",80,"Kingscourt Stars",0,1],
["cavan-20","Ciaran Brady","DEF",75,"Gowna",0,null],
["cavan-20","Jason McLoughlin","DEF",74,null,0,null],
["cavan-20","Killian Clarke","DEF",75,"Shercock",0,null],
["cavan-20","Thomas Galligan","MID",80,"Lacken",0,1],
["cavan-20","Gearoid McKiernan","MID",80,"Swanlinbar",0,null],
["cavan-20","James Smith","MID",76,"Killygarry",0,null],
["cavan-20","Martin Reilly","FWD",78,"Killygarry",0,null],
["cavan-20","Dara McVeety","FWD",78,"Crosserlough",0,null],
["cavan-20","Conor Madden","FWD",75,"Gowna",0,null],
["cavan-20","Oisín Kiernan","FWD",74,"Castlerahan",0,null],
["cavan-20","Gerard Smith","FWD",73,null,0,null],
/* ---- Louth, The Wee County Risen ---- */
["louth-25","Niall McDonnell","GK",73,null,0,null],
["louth-25","Dan Corcoran","DEF",76,null,0,null],
["louth-25","Donal McKenny","DEF",76,null,0,null],
["louth-25","Peter Lynch","DEF",77,null,0,null],
["louth-25","Dermot Campbell","DEF",74,null,0,null],
["louth-25","Craig Lennon","MID",81,null,0,null],
["louth-25","Tommy Durnin","MID",79,null,0,null],
["louth-25","Bevan Duffy","MID",76,null,0,null],
["louth-25","Niall Sharkey","MID",74,null,0,null],
["louth-25","Sam Mulroy","FWD",83,"Naomh Máirtín",0,null],
["louth-25","Ciarán Downey","FWD",78,null,0,null],
["louth-25","Ryan Burns","FWD",77,null,0,null],
["louth-25","Conor Grimes","FWD",77,null,0,null],
["louth-25","Conall McKeever","FWD",76,null,0,null],
/* ---- Leitrim, Connacht Kings of '94 ---- */
["leitrim-94","Martin McHugh","GK",73,null,0,null],
["leitrim-94","Declan Darcy","DEF",81,"Aughawillan",0,null],
["leitrim-94","Seamus Quinn","DEF",79,null,0,1],
["leitrim-94","Fergal Reynolds","DEF",73,null,0,null],
["leitrim-94","Joe Honeyman","DEF",72,null,0,null],
["leitrim-94","Mickey Quinn","MID",78,"Aughawillan",0,null],
["leitrim-94","Paul Kieran","MID",73,null,0,null],
["leitrim-94","Aidan Rooney","FWD",76,null,0,null],
["leitrim-94","Padraig Kenny","FWD",75,null,0,null],
["leitrim-94","Colin McGlynn","FWD",74,null,0,null],
["leitrim-94","George Dugdale","FWD",73,null,0,null],
["leitrim-94","Liam Conlon","FWD",73,null,0,null],
/* ---- Sligo, The Yeats County Breakthrough ---- */
["sligo-07","Philip Greene","GK",72,null,0,null],
["sligo-07","Charlie Harrison","DEF",79,null,0,1],
["sligo-07","Ross Donovan","DEF",75,null,0,null],
["sligo-07","Noel McGuire","DEF",73,null,0,null],
["sligo-07","Michael McNamara","DEF",72,null,0,null],
["sligo-07","Eamonn O'Hara","MID",82,"Tourlestrane",0,null],
["sligo-07","Sean Davey","MID",74,null,0,null],
["sligo-07","David Kelly","FWD",78,null,0,null],
["sligo-07","Mark Breheny","FWD",77,null,0,null],
["sligo-07","Brendan Egan","FWD",74,null,0,null],
["sligo-07","Johnny Davey","FWD",73,null,0,null],
["sligo-07","Eugene Mullen","FWD",72,null,0,null],
/* ---- Clare, The Banner Risen ---- */
["clare-92","James Hanrahan","GK",72,null,0,null],
["clare-92","Seamus Clancy","DEF",80,null,0,1],
["clare-92","Noel Roche","DEF",76,null,0,null],
["clare-92","Aidan Moloney","DEF",74,null,0,null],
["clare-92","John Enright","DEF",72,null,0,null],
["clare-92","Tom Morrissey","MID",75,null,0,null],
["clare-92","Pádraig Conway","MID",74,null,0,null],
["clare-92","Francis McInerney","FWD",81,null,0,null],
["clare-92","Martin Daly","FWD",78,null,0,null],
["clare-92","Gerry Killeen","FWD",76,null,0,null],
["clare-92","Colm Clancy","FWD",74,null,0,null],
/* ---- Dublin, The Nearly Men of the Noughties ---- */
["dublin-00s","Stephen Cluxton","GK",84,"Parnells",9,2],
["dublin-00s","Paddy Christie","DEF",81,"Ballymun Kickhams",0,null],
["dublin-00s","Coman Goggins","DEF",78,"Ballinteer St John's",0,null],
["dublin-00s","Barry Cahill","DEF",79,"St Brigid's",1,null],
["dublin-00s","Paul Casey","DEF",77,"Lucan Sarsfields",0,null],
["dublin-00s","Peadar Andrews","DEF",76,"St Brigid's",0,null],
["dublin-00s","Bryan Cullen","DEF",79,"Skerries Harps",1,null],
["dublin-00s","Ciarán Whelan","MID",86,"Raheny",0,null],
["dublin-00s","Shane Ryan","MID",79,"Naomh Mearnóg",0,null],
["dublin-00s","Alan Brogan","FWD",85,"St Oliver Plunketts ER",3,3],
["dublin-00s","Conal Keaney","FWD",80,"Ballyboden St Enda's",0,null],
["dublin-00s","Jason Sherlock","FWD",81,"Na Fianna",1,1],
["dublin-00s","Tomás 'Mossy' Quinn","FWD",78,"St Vincent's",1,null],
["dublin-00s","Collie Moran","FWD",78,"Ballyboden St Enda's",0,null],
/* ---- Derry, Bradley's Oak Leafers ---- */
["derry-00s","Sean Marty Lockhart","DEF",82,"Banagher",0,1],
["derry-00s","Kevin McCloy","DEF",80,"Lavey",0,null],
["derry-00s","Kevin McGuckin","DEF",77,"Ballinderry",0,null],
["derry-00s","Niall McCusker","DEF",76,"Ballinderry",0,null],
["derry-00s","Fergal Doherty","MID",81,"Bellaghy",0,null],
["derry-00s","Patsy Bradley","MID",78,"Slaughtneil",0,null],
["derry-00s","James Conway","MID",76,null,0,null],
["derry-00s","Enda Muldoon","FWD",83,"Ballinderry",0,null],
["derry-00s","Paddy Bradley","FWD",84,"Glenullin",0,null],
["derry-00s","Eoin Bradley","FWD",79,"Glenullin",0,null],
["derry-00s","Conleith Gilligan","FWD",79,"Ballinderry",0,null],
["derry-00s","Mark Lynch","FWD",79,"Banagher",0,null],
/* ---- Down, The 2010 Final Run ---- */
["down-10","Brendan McVeigh","GK",79,null,0,null],
["down-10","Dan Gordon","DEF",77,null,0,null],
["down-10","Conor Garvey","DEF",76,null,0,null],
["down-10","Damien Rafferty","DEF",75,null,0,null],
["down-10","Kalum King","MID",76,null,0,null],
["down-10","Peter Fitzpatrick","MID",77,null,0,null],
["down-10","Ambrose Rodgers","MID",78,null,0,null],
["down-10","Marty Clarke","FWD",84,"An Ríocht",0,1],
["down-10","Danny Hughes","FWD",80,null,0,null],
["down-10","Mark Poland","FWD",80,"Longstone",0,null],
["down-10","Benny Coulter","FWD",83,"Mayobridge",0,null],
["down-10","Brendan Coulter","FWD",77,"Mayobridge",0,null],
["down-10","John Clarke","FWD",77,null,0,null],
/* ---- Galway, Meehan's Maroon Years ---- */
["galway-10","Finian Hanley","DEF",79,"Salthill-Knocknacarra",0,null],
["galway-10","Gareth Bradshaw","DEF",78,"Moycullen",0,null],
["galway-10","Gary O'Donnell","DEF",77,"Tuam Stars",0,null],
["galway-10","Greg Higgins","MID",77,null,0,null],
["galway-10","Barry Cullinane","MID",75,"Claregalway",0,null],
["galway-10","Paul Conroy","MID",79,"St James'",0,null],
["galway-10","Joe Bergin","MID",78,"Mountbellew-Moylough",0,null],
["galway-10","Michael Meehan","FWD",85,"Caltra",0,null],
["galway-10","Seán Armstrong","FWD",80,"Salthill-Knocknacarra",0,null],
["galway-10","Pádraic Joyce","FWD",84,"Killererin",2,2],
["galway-10","Cormac Bane","FWD",76,null,0,null],
["galway-10","Niall Coleman","FWD",75,null,0,null],
/* ---- Kildare, McGeeney's White Heat ---- */
["kildare-10","Shane Connolly","GK",76,null,0,null],
["kildare-10","Peter Kelly","DEF",79,"Two Mile House",0,1],
["kildare-10","Emmet Bolton","DEF",78,"Eadestown",0,null],
["kildare-10","Andriú Mac Lochlainn","DEF",77,null,0,null],
["kildare-10","Hugh McGrillen","DEF",76,null,0,null],
["kildare-10","Dermot Earley Jnr","MID",82,"Sarsfields",0,1],
["kildare-10","Daryl Flynn","MID",78,"Moorefield",0,null],
["kildare-10","Gary White","MID",77,null,0,null],
["kildare-10","Johnny Doyle","FWD",84,"Allenwood",0,null],
["kildare-10","Eamonn Callaghan","FWD",79,"Naas",0,null],
["kildare-10","James Kavanagh","FWD",78,null,0,null],
["kildare-10","Alan Smith","FWD",78,null,0,null],
["kildare-10","Mikey Conway","FWD",76,null,0,null],
/* ---- Tipperary, The 2020 Breakthrough ---- */
["tipperary-20","Evan Comerford","GK",78,"Kilsheelan-Kilcash",0,null],
["tipperary-20","Alan Campbell","DEF",76,"Moyle Rovers",0,null],
["tipperary-20","Jimmy Feehan","DEF",77,"Killenaule",0,null],
["tipperary-20","Kevin Fahey","DEF",76,"Clonmel Commercials",0,null],
["tipperary-20","Bill Maher","DEF",77,"Kilsheelan-Kilcash",0,null],
["tipperary-20","Robbie Kiely","DEF",77,null,0,null],
["tipperary-20","Colin O'Riordan","MID",80,"JK Brackens",0,null],
["tipperary-20","Steven O'Brien","MID",79,"Ballina",0,null],
["tipperary-20","Liam Casey","MID",77,"Cahir",0,null],
["tipperary-20","Conor Sweeney","FWD",84,"Ballyporeen",0,1],
["tipperary-20","Michael Quinlivan","FWD",83,"Clonmel Commercials",0,1],
["tipperary-20","Brian Fox","FWD",77,"Éire Óg Annacarty",0,null],
["tipperary-20","Liam McGrath","FWD",75,"Loughmore-Castleiney",0,null],
["tipperary-20","Jack Kennedy","FWD",76,"Clonmel Commercials",0,null],
/* ---- Monaghan, Nudie's Farneymen ---- */
["monaghan-80s","Paddy Linden","GK",80,"Castleblayney",0,null],
["monaghan-80s","Gerry McCarville","DEF",79,null,0,null],
["monaghan-80s","Fergus Caulfield","DEF",76,null,0,null],
["monaghan-80s","Ciarán Murray","DEF",79,null,0,null],
["monaghan-80s","Bernie Murray","MID",77,null,0,null],
["monaghan-80s","Gene Sherry","MID",76,null,0,null],
["monaghan-80s","Eamonn McEneaney","FWD",81,"Castleblayney",0,null],
["monaghan-80s","Eugene 'Nudie' Hughes","FWD",85,"Castleblayney",0,3],
["monaghan-80s","Ray McCarron","FWD",80,null,0,null],
["monaghan-80s","Declan Flanagan","FWD",75,null,0,null],
/* ---- Wexford, Forde's Model Men ---- */
["wexford-08","Anthony Masterson","GK",75,null,0,null],
["wexford-08","Graeme Molloy","DEF",75,null,0,null],
["wexford-08","David Murphy","DEF",77,null,0,null],
["wexford-08","Colm Morris","DEF",77,null,0,null],
["wexford-08","Diarmuid Kinsella","MID",76,null,0,null],
["wexford-08","Nicky Lambert","MID",75,null,0,null],
["wexford-08","Mattie Forde","FWD",84,"Kilanerin",0,1],
["wexford-08","Redmond Barry","FWD",79,null,0,null],
["wexford-08","PJ Banville","FWD",77,null,0,null],
["wexford-08","Ciarán Lyng","FWD",77,null,0,null],
/* ---- Antrim, The Saffron Surge ---- */
["antrim-09","Kevin O'Boyle","DEF",76,"Cargin",0,null],
["antrim-09","Justin Crozier","DEF",76,null,0,null],
["antrim-09","Andy McClean","DEF",75,null,0,null],
["antrim-09","Michael McCann","MID",78,"Cargin",0,null],
["antrim-09","Aodhán Gallagher","MID",76,null,0,null],
["antrim-09","Niall McKeever","MID",77,null,0,null],
["antrim-09","Paddy Cunningham","FWD",81,"Lámh Dhearg",0,null],
["antrim-09","Tomás McCann","FWD",79,"Cargin",0,null],
["antrim-09","Kevin Niblock","FWD",78,"St Gall's",0,null],
/* ---- Carlow, Turlough's Tribe ---- */
["carlow-18","Robert Sansom","GK",75,null,0,null],
["carlow-18","Daniel St Ledger","DEF",78,null,0,null],
["carlow-18","Sean Murphy","DEF",80,null,0,null],
["carlow-18","Ciaran Moran","DEF",75,null,0,null],
["carlow-18","Brendan Murphy","MID",81,"Rathvilly",0,null],
["carlow-18","Darragh Foley","MID",78,null,0,null],
["carlow-18","Jordan Morrissey","MID",75,null,0,null],
["carlow-18","Paul Broderick","FWD",81,"Tinryland",0,null],
["carlow-18","John Murphy","FWD",76,null,0,null],
/* ---- Limerick, The Treaty Risers ---- */
["limerick-04","Seamus O'Donnell","GK",74,null,0,null],
["limerick-04","Mark O'Riordan","DEF",75,null,0,null],
["limerick-04","John Galvin","MID",82,null,0,null],
["limerick-04","John Quane","MID",79,null,0,null],
["limerick-04","Muiris Gavin","FWD",79,null,0,null],
["limerick-04","Jason Stokes","FWD",79,null,0,null],
["limerick-04","Stephen Kelly","FWD",77,null,0,null],
["limerick-04","Conor Fitzgerald","FWD",77,null,0,null],
["limerick-04","Micheál Reidy","FWD",76,null,0,null],
/* ---- Roscommon, Smith's Rossies ---- */
["roscommon-17","Darren O'Malley","GK",76,null,0,null],
["roscommon-17","Conor Daly","DEF",76,"Pádraig Pearses",0,null],
["roscommon-17","Sean Mullooly","DEF",76,null,0,null],
["roscommon-17","Niall Daly","DEF",77,"Pádraig Pearses",0,null],
["roscommon-17","Ultan Harney","DEF",75,null,0,null],
["roscommon-17","Enda Smith","MID",81,"Boyle",0,null],
["roscommon-17","Tadhg O'Rourke","MID",77,"Tulsk",0,null],
["roscommon-17","Conor Cox","FWD",80,"Listowel Emmets",0,null],
["roscommon-17","Diarmuid Murtagh","FWD",80,"St Faithleach's",0,null],
["roscommon-17","Ciaráin Murtagh","FWD",78,"St Faithleach's",0,null],
["roscommon-17","Donie Smith","FWD",78,"Boyle",0,null],
["roscommon-17","Cathal Cregg","FWD",77,"Western Gaels",0,null]
];

/* ----------------------------------------------------------------------
   X — player extras, keyed "teamId|Name".
   nickname · born (year) · poty (Footballer of the Year awards) ·
   dual ("hurling"/"soccer"/…) · family (relation note) · captain (lifted Sam)
---------------------------------------------------------------------- */
const X = {
 "kerry-00s|Colm 'Gooch' Cooper":{nickname:"Gooch",born:1983},
 "kerry-golden|Eoin 'Bomber' Liston":{nickname:"The Bomber",born:1957},
 "kerry-golden|Jack O'Shea":{nickname:"Jacko",born:1957,poty:1},
 "kerry-golden|Pat Spillane":{born:1955,poty:1,family:"brother of Mick & Tom Spillane"},
 "kerry-golden|Mick Spillane":{family:"brother of Pat & Tom Spillane"},
 "kerry-golden|Páidí Ó Sé":{born:1955,family:"uncle of Darragh, Tomás & Marc Ó Sé"},
 "kerry-golden|Mikey Sheehy":{born:1954},
 "kerry-00s|Darragh Ó Sé":{born:1975,family:"brother of Tomás & Marc, nephew of Páidí"},
 "kerry-00s|Tomás Ó Sé":{born:1978,family:"brother of Darragh & Marc, nephew of Páidí"},
 "kerry-00s|Marc Ó Sé":{born:1980,family:"brother of Darragh & Tomás, nephew of Páidí"},
 "kerry-00s|Kieran Donaghy":{nickname:"Star",born:1983},
 "kerry-00s|Séamus Moynihan":{born:1973,poty:1},
 "kerry-00s|Declan O'Sullivan":{captain:true},
 "kerry-20s|David Clifford":{born:1999,poty:2,family:"brother of Paudie Clifford"},
 "kerry-20s|Paudie Clifford":{born:1997,family:"brother of David Clifford"},
 "kerry-20s|Seán O'Shea":{born:1998},
 "dublin-70s|Kevin Moran":{born:1956,dual:"soccer — Manchester United & Ireland",family:null},
 "dublin-70s|Jimmy Keaveney":{born:1945},
 "dublin-70s|Tony Hanahoe":{captain:true},
 "dublin-70s|Bernard Brogan Snr":{family:"father of Bernard & Alan Brogan"},
 "dublin-90s|Jason Sherlock":{nickname:"Jayo",born:1976},
 "dublin-90s|John O'Leary":{captain:true},
 "dublin-10s|Stephen Cluxton":{born:1981,captain:true},
 "dublin-10s|Bernard Brogan":{born:1984,poty:1,family:"son of Bernard Snr, brother of Alan"},
 "dublin-10s|Brian Fenton":{born:1993,poty:2},
 "dublin-10s|Jack McCaffrey":{born:1993,poty:1},
 "dublin-10s|Ciarán Kilkenny":{born:1993},
 "dublin-10s|Michael Darragh Macauley":{poty:1},
 "dublin-10s|Con O'Callaghan":{born:1996},
 "tyrone-00s|Peter Canavan":{nickname:"Peter the Great",born:1971,captain:true,family:"father of Darragh Canavan"},
 "tyrone-00s|Seán Cavanagh":{born:1983,poty:1},
 "tyrone-00s|Stephen O'Neill":{poty:1},
 "tyrone-00s|Owen Mulligan":{nickname:"Mugsy",born:1981},
 "tyrone-00s|Ryan McMenamin":{nickname:"Ricey"},
 "tyrone-00s|Brian Dooher":{captain:true},
 "tyrone-20s|Kieran McGeary":{poty:1},
 "tyrone-20s|Pádraig Hampsey":{captain:true},
 "tyrone-20s|Darragh Canavan":{born:2001,family:"son of Peter Canavan"},
 "mayo-10s|Lee Keegan":{born:1989,poty:1},
 "mayo-10s|Andy Moran":{born:1983,poty:1},
 "mayo-10s|Aidan O'Shea":{born:1990,family:"brother of Séamus O'Shea"},
 "mayo-10s|Séamus O'Shea":{family:"brother of Aidan O'Shea"},
 "mayo-10s|Cillian O'Connor":{born:1992,captain:false,family:"brother of Diarmuid O'Connor (Mayo)"},
 "mayo-10s|Diarmuid O'Connor":{family:"brother of Cillian O'Connor"},
 "donegal-90s|Anthony Molloy":{captain:true},
 "donegal-90s|Martin McHugh":{nickname:"The Wee Man",family:"father of Mark & Ryan McHugh, brother of James"},
 "donegal-90s|James McHugh":{family:"brother of Martin McHugh"},
 "donegal-10s|Michael Murphy":{born:1989,captain:true},
 "donegal-10s|Karl Lacey":{poty:1},
 "donegal-10s|Mark McHugh":{family:"son of Martin McHugh, brother of Ryan"},
 "donegal-10s|Ryan McHugh":{family:"son of Martin McHugh, brother of Mark"},
 "donegal-10s|Neil McGee":{family:"brother of Eamon McGee"},
 "donegal-10s|Eamon McGee":{family:"brother of Neil McGee"},
 "armagh-00s|Kieran McGeeney":{nickname:"Geezer",born:1971,captain:true,poty:1},
 "armagh-00s|Oisín McConville":{born:1975},
 "armagh-20s|Aidan Forker":{captain:true},
 "armagh-20s|Jarly Óg Burns":{family:"son of Jarlath Burns (GAA President)"},
 "meath-boylan|Trevor Giles":{born:1974,poty:2},
 "meath-boylan|Colm O'Rourke":{poty:1},
 "meath-boylan|Liam Hayes":{captain:true},
 "galway-98|Pádraic Joyce":{born:1977,poty:1},
 "galway-98|Michael Donnellan":{poty:1,family:"son of Pat & nephew of John Donnellan, both Galway greats"},
 "galway-98|Ja Fallon":{poty:1},
 "galway-98|Ray Silke":{captain:true},
 "galway-20s|Seán Kelly":{captain:true},
 "galway-20s|Shane Walsh":{born:1993},
 "cork-89|Larry Tompkins":{captain:true,poty:1,family:null,dual:null},
 "cork-89|Teddy McCarthy":{dual:"hurling — only man to win football & hurling All-Irelands in the same year (1990)"},
 "cork-89|Shea Fahy":{poty:1},
 "cork-89|Dave Barry":{dual:"soccer — League of Ireland with Cork City"},
 "cork-10|Graham Canty":{captain:true},
 "down-60s|Seán O'Neill":{poty:1},
 "down-60s|Paddy Doherty":{captain:true},
 "down-60s|Dan McCartan":{family:"brother of James McCartan Snr"},
 "down-60s|James McCartan Snr":{family:"father of James McCartan Jnr, brother of Dan"},
 "down-90s|James McCartan":{family:"son of James McCartan Snr"},
 "down-90s|Paddy O'Rourke":{captain:true},
 "down-90s|DJ Kane":{captain:true},
 "derry-93|Henry Downey":{captain:true,poty:1},
 "derry-93|Anthony Tohill":{born:1971},
 "derry-93|Joe Brolly":{nickname:"Brolly"},
 "derry-20s|Chrissy McKaigue":{captain:true},
 "offaly-82|Matt Connor":{born:1959,family:"brother of Richie Connor"},
 "offaly-82|Richie Connor":{captain:true,family:"brother of Matt Connor"},
 "offaly-82|Liam Currams":{dual:"hurling — won the 1981 hurling All-Ireland with Offaly"},
 "offaly-82|Seamus Darby":{nickname:"the man who stopped five-in-a-row"},
 "roscommon-80|Dermot Earley":{family:"father of Dermot Earley Jnr"},
 "kildare-98|Dermot Earley Jnr":{family:"son of Dermot Earley (Roscommon)"},
 "kildare-98|Glenn Ryan":{captain:true},
 "laois-03|Brian 'Beano' McDonald":{nickname:"Beano"},
 "monaghan-15|Conor McManus":{born:1987},
 "monaghan-15|Rory Beggan":{born:1992},
 "monaghan-15|Darren Hughes":{family:"brother of Kieran Hughes"},
 "monaghan-15|Kieran Hughes":{family:"brother of Darren Hughes"},
 "monaghan-15|Drew Wylie":{family:"brother of Ryan Wylie"},
 "monaghan-15|Ryan Wylie":{family:"brother of Drew Wylie"},
 "cavan-20|Raymond Galligan":{captain:true},
 "westmeath-04|Dessie Dolan":{family:"brother of Gary Dolan; father Dessie Snr also played for Westmeath"},
 "dublin-00s|Alan Brogan":{family:"son of Bernard Snr, brother of Bernard Jnr",poty:1},
 "dublin-00s|Ciarán Whelan":{born:1976},
 "derry-00s|Paddy Bradley":{family:"brother of Eoin Bradley"},
 "derry-00s|Eoin Bradley":{nickname:"Skinner",family:"brother of Paddy Bradley",dual:"soccer — Irish League with Coleraine"},
 "down-10|Benny Coulter":{family:"brother of Brendan Coulter"},
 "down-10|Brendan Coulter":{family:"brother of Benny Coulter"},
 "tipperary-20|Colin O'Riordan":{dual:"AFL — Sydney Swans"},
 "monaghan-80s|Eugene 'Nudie' Hughes":{nickname:"Nudie"},
 "roscommon-17|Conor Cox":{family:"Kerry native — Listowel Emmets clubman who declared for Roscommon"},
 "galway-10|Michael Meehan":{born:1984},
 "kildare-10|Johnny Doyle":{born:1978}
};

/* ----------------------------------------------------------------------
   Z — position zones, keyed "teamId|Name". Refines line to a specific zone:
   FB = full-back line (corner/full-back) · HB = half-back line
   FF = full-forward line (corner/full-forward) · HF = half-forward line
   Players not listed can be placed anywhere in their line (DEF/FWD) —
   refine over time (check starting 15s on scorebeo / GAA archives).
---------------------------------------------------------------------- */
const Z = {
 "kerry-golden|Páidí Ó Sé":"HB","kerry-golden|John O'Keeffe":"FB","kerry-golden|Tim Kennelly":"HB",
 "kerry-golden|Jimmy Deenihan":"FB","kerry-golden|Mick Spillane":"FB","kerry-golden|Pat Spillane":"HF",
 "kerry-golden|Mikey Sheehy":"FF","kerry-golden|Eoin 'Bomber' Liston":"FF","kerry-golden|John Egan":"FF",
 "kerry-golden|Ger Power":"HF","kerry-golden|Ogie Moran":"HF",
 "kerry-00s|Séamus Moynihan":"FB","kerry-00s|Tomás Ó Sé":"HB","kerry-00s|Marc Ó Sé":"FB",
 "kerry-00s|Tom O'Sullivan":"FB","kerry-00s|Mike McCarthy":"FB","kerry-00s|Aidan O'Mahony":"HB",
 "kerry-00s|Colm 'Gooch' Cooper":"FF","kerry-00s|Declan O'Sullivan":"HF","kerry-00s|Kieran Donaghy":"FF",
 "kerry-00s|Paul Galvin":"HF","kerry-00s|Mike Frank Russell":"FF","kerry-00s|Dara Ó Cinnéide":"FF",
 "kerry-20s|Tom O'Sullivan":"FB","kerry-20s|Gavin White":"HB","kerry-20s|Jason Foley":"FB",
 "kerry-20s|Tadhg Morley":"HB","kerry-20s|Brian Ó Beaglaoich":"FB","kerry-20s|Graham O'Sullivan":"HB",
 "kerry-20s|David Clifford":"FF","kerry-20s|Paudie Clifford":"HF","kerry-20s|Seán O'Shea":"HF",
 "kerry-20s|Paul Geaney":"FF","kerry-20s|Tony Brosnan":"FF",
 "dublin-70s|Kevin Moran":"HB","dublin-70s|Tommy Drumm":"HB","dublin-70s|Robbie Kelleher":"FB",
 "dublin-70s|Seán Doherty":"FB","dublin-70s|Gay O'Driscoll":"FB","dublin-70s|Jimmy Keaveney":"FF",
 "dublin-70s|Anton O'Toole":"HF","dublin-70s|David Hickey":"HF","dublin-70s|Tony Hanahoe":"HF",
 "dublin-70s|Bobby Doyle":"FF","dublin-70s|John McCarthy":"FF",
 "dublin-90s|Paul Curran":"HB","dublin-90s|Keith Barr":"HB","dublin-90s|Charlie Redmond":"FF",
 "dublin-90s|Jason Sherlock":"FF","dublin-90s|Dessie Farrell":"HF",
 "dublin-10s|Jack McCaffrey":"HB","dublin-10s|James McCarthy":"HB","dublin-10s|Cian O'Sullivan":"FB",
 "dublin-10s|Philly McMahon":"FB","dublin-10s|Jonny Cooper":"FB","dublin-10s|Mick Fitzsimons":"FB",
 "dublin-10s|Con O'Callaghan":"FF","dublin-10s|Ciarán Kilkenny":"HF","dublin-10s|Diarmuid Connolly":"HF",
 "dublin-10s|Bernard Brogan":"FF","dublin-10s|Paul Mannion":"FF","dublin-10s|Paul Flynn":"HF",
 "dublin-10s|Dean Rock":"FF","dublin-10s|Kevin McManamon":"HF",
 "tyrone-00s|Philip Jordan":"HB","tyrone-00s|Ryan McMenamin":"FB","tyrone-00s|Conor Gormley":"HB",
 "tyrone-00s|Peter Canavan":"FF","tyrone-00s|Stephen O'Neill":"FF","tyrone-00s|Brian Dooher":"HF",
 "tyrone-00s|Brian McGuigan":"HF","tyrone-00s|Owen Mulligan":"FF",
 "tyrone-20s|Pádraig Hampsey":"FB","tyrone-20s|Conor Meyler":"HB","tyrone-20s|Kieran McGeary":"HB",
 "tyrone-20s|Ronan McNamee":"FB","tyrone-20s|Peter Harte":"HB","tyrone-20s|Michael McKernan":"FB",
 "tyrone-20s|Darragh Canavan":"FF","tyrone-20s|Darren McCurry":"FF","tyrone-20s|Cathal McShane":"FF",
 "tyrone-20s|Mattie Donnelly":"HF","tyrone-20s|Niall Sludden":"HF",
 "mayo-10s|Lee Keegan":"HB","mayo-10s|Keith Higgins":"FB","mayo-10s|Colm Boyle":"HB",
 "mayo-10s|Paddy Durcan":"HB","mayo-10s|Chris Barrett":"FB","mayo-10s|Brendan Harrison":"FB",
 "mayo-10s|Cillian O'Connor":"FF","mayo-10s|Andy Moran":"FF","mayo-10s|Kevin McLoughlin":"HF",
 "mayo-10s|Jason Doherty":"HF","mayo-10s|Diarmuid O'Connor":"HF",
 "donegal-90s|Martin Gavigan":"HB","donegal-90s|Matt Gallagher":"FB","donegal-90s|Martin McHugh":"HF",
 "donegal-90s|Tony Boyle":"FF","donegal-90s|Manus Boyle":"FF","donegal-90s|Declan Bonner":"FF",
 "donegal-10s|Karl Lacey":"HB","donegal-10s|Neil McGee":"FB","donegal-10s|Frank McGlynn":"HB",
 "donegal-10s|Mark McHugh":"HB","donegal-10s|Eamon McGee":"FB","donegal-10s|Anthony Thompson":"HB",
 "donegal-10s|Michael Murphy":"FF","donegal-10s|Colm McFadden":"FF","donegal-10s|Ryan McHugh":"HF",
 "donegal-10s|Patrick McBrearty":"FF","donegal-10s|Leo McLoone":"HF",
 "armagh-00s|Kieran McGeeney":"HB","armagh-00s|Enda McNulty":"FB","armagh-00s|Francie Bellew":"FB",
 "armagh-00s|Justin McNulty":"FB","armagh-00s|Aidan O'Rourke":"HB","armagh-00s|Oisín McConville":"FF",
 "armagh-00s|Stevie McDonnell":"FF","armagh-00s|Ronan Clarke":"FF","armagh-00s|John McEntee":"HF",
 "armagh-00s|Diarmaid Marsden":"HF",
 "armagh-20s|Aidan Forker":"HB","armagh-20s|Aaron McKay":"FB","armagh-20s|Joe McElroy":"HB",
 "armagh-20s|Rian O'Neill":"FF","armagh-20s|Oisín Conaty":"HF","armagh-20s|Conor Turbitt":"FF",
 "armagh-20s|Rory Grugan":"HF","armagh-20s|Andrew Murnin":"FF","armagh-20s|Stefan Campbell":"HF",
 "meath-boylan|Martin O'Connell":"HB","meath-boylan|Mick Lyons":"FB","meath-boylan|Darren Fay":"FB",
 "meath-boylan|Robbie O'Malley":"FB","meath-boylan|Mark O'Reilly":"FB","meath-boylan|Kevin Foley":"HB",
 "meath-boylan|Trevor Giles":"HF","meath-boylan|Graham Geraghty":"FF","meath-boylan|Colm O'Rourke":"FF",
 "meath-boylan|Bernard Flynn":"FF","meath-boylan|Tommy Dowd":"HF","meath-boylan|Ollie Murphy":"FF",
 "galway-98|Seán Óg de Paor":"HB","galway-98|Gary Fahey":"FB","galway-98|Pádraic Joyce":"FF",
 "galway-98|Michael Donnellan":"HF","galway-98|Ja Fallon":"HF","galway-98|Derek Savage":"FF",
 "galway-98|Niall Finnegan":"FF",
 "galway-20s|Dylan McHugh":"HB","galway-20s|Liam Silke":"FB","galway-20s|John Daly":"HB",
 "galway-20s|Jack Glynn":"FB","galway-20s|Seán Kelly":"HB","galway-20s|Shane Walsh":"HF",
 "galway-20s|Damien Comer":"FF","galway-20s|Rob Finnerty":"FF","galway-20s|Matthew Tierney":"HF",
 "galway-20s|Johnny Heaney":"HF",
 "cork-89|Conor Counihan":"FB","cork-89|Tony Davis":"HB","cork-89|Larry Tompkins":"HF",
 "cork-89|Colm O'Neill":"FF","cork-89|John Cleary":"FF",
 "cork-10|Graham Canty":"FB","cork-10|John Miskella":"HB","cork-10|Noel O'Leary":"HB",
 "cork-10|Daniel Goulding":"FF","cork-10|Donncha O'Connor":"FF","cork-10|Colm O'Neill":"FF",
 "cork-10|Paul Kerrigan":"HF","cork-10|Pearse O'Neill":"HF",
 "down-60s|Seán O'Neill":"FF","down-60s|Paddy Doherty":"HF","down-60s|James McCartan Snr":"HF",
 "down-60s|Leo Murphy":"FB","down-60s|Tom O'Hare":"FB","down-60s|Dan McCartan":"HB",
 "down-90s|Mickey Linden":"FF","down-90s|Greg Blaney":"HF","down-90s|James McCartan":"HF",
 "down-90s|Ross Carr":"HF","down-90s|Peter Withnell":"FF","down-90s|Conor Deegan":"FB",
 "derry-93|Henry Downey":"HB","derry-93|Tony Scullion":"FB","derry-93|Kieran McKeever":"FB",
 "derry-93|Johnny McGurk":"HB","derry-93|Joe Brolly":"FF","derry-93|Enda Gormley":"FF",
 "derry-93|Seamus Downey":"FF","derry-93|Damian Cassidy":"HF",
 "derry-20s|Chrissy McKaigue":"FB","derry-20s|Brendan Rogers":"FB","derry-20s|Gareth McKinless":"HB",
 "derry-20s|Conor McCluskey":"FB","derry-20s|Eoin McEvoy":"HB","derry-20s|Shane McGuigan":"FF",
 "derry-20s|Ethan Doherty":"HF","derry-20s|Paul Cassidy":"HF",
 "offaly-82|Liam O'Connor":"FB","offaly-82|Liam Currams":"HB","offaly-82|Richie Connor":"HF",
 "offaly-82|Matt Connor":"FF","offaly-82|Brendan Lowry":"FF","offaly-82|Seamus Darby":"FF",
 "offaly-82|Gerry Carroll":"HF",
 "roscommon-80|Harry Keegan":"FB","roscommon-80|Pat Lindsay":"FB","roscommon-80|Danny Murray":"HB",
 "roscommon-80|Tony McManus":"FF",
 "monaghan-15|Drew Wylie":"FB","monaghan-15|Ryan Wylie":"FB","monaghan-15|Karl O'Connell":"HB",
 "monaghan-15|Conor McManus":"FF","monaghan-15|Kieran Hughes":"FF","monaghan-15|Jack McCarron":"FF",
 "monaghan-15|Conor McCarthy":"HF","monaghan-15|Shane Carey":"HF",
 "kildare-98|Glenn Ryan":"HB","kildare-98|Anthony Rainbow":"HB","kildare-98|Martin Lynch":"HF",
 "laois-03|Ross Munnelly":"FF","laois-03|Tom Kelly":"HB","laois-03|Joe Higgins":"FB",
 "laois-03|Brian 'Beano' McDonald":"FF",
 "westmeath-04|Dessie Dolan":"FF","westmeath-04|John Keane":"HB","westmeath-04|Alan Mangan":"HF",
 "fermanagh-04|Barry Owens":"FB","fermanagh-04|Tom Brewster":"HF","fermanagh-04|Stephen Maguire":"FF",
 "cavan-20|Padraig Faulkner":"FB","cavan-20|Martin Reilly":"HF","cavan-20|Dara McVeety":"HF",
 "cavan-20|Conor Madden":"FF",
 "clare-92|Seamus Clancy":"HB","clare-92|Francis McInerney":"FF","clare-92|Martin Daly":"FF",
 "louth-25|Sam Mulroy":"FF","louth-25|Craig Lennon":"HF","louth-25|Ciarán Downey":"HF",
 "louth-25|Ryan Burns":"FF","louth-25|Conor Grimes":"FF","louth-25|Peter Lynch":"HB",
 "leitrim-94|Declan Darcy":"HB","leitrim-94|Seamus Quinn":"FB","leitrim-94|Aidan Rooney":"FF",
 "sligo-07|Charlie Harrison":"FB","sligo-07|David Kelly":"FF","sligo-07|Mark Breheny":"HF",
 "dublin-00s|Paddy Christie":"FB","dublin-00s|Coman Goggins":"FB","dublin-00s|Barry Cahill":"HB",
 "dublin-00s|Bryan Cullen":"HB","dublin-00s|Alan Brogan":"HF","dublin-00s|Jason Sherlock":"FF",
 "dublin-00s|Tomás 'Mossy' Quinn":"FF","dublin-00s|Conal Keaney":"HF",
 "derry-00s|Sean Marty Lockhart":"FB","derry-00s|Paddy Bradley":"FF","derry-00s|Enda Muldoon":"HF",
 "derry-00s|Eoin Bradley":"FF","derry-00s|Mark Lynch":"HF",
 "down-10|Marty Clarke":"HF","down-10|Benny Coulter":"FF","down-10|Danny Hughes":"HF",
 "down-10|Mark Poland":"HF","down-10|Dan Gordon":"FB",
 "galway-10|Michael Meehan":"FF","galway-10|Seán Armstrong":"FF","galway-10|Pádraic Joyce":"FF",
 "galway-10|Finian Hanley":"FB","galway-10|Gareth Bradshaw":"HB",
 "kildare-10|Johnny Doyle":"FF","kildare-10|Eamonn Callaghan":"HF","kildare-10|Peter Kelly":"FB",
 "kildare-10|Emmet Bolton":"HB",
 "tipperary-20|Conor Sweeney":"FF","tipperary-20|Michael Quinlivan":"FF","tipperary-20|Brian Fox":"HF",
 "tipperary-20|Bill Maher":"HB","tipperary-20|Jimmy Feehan":"FB",
 "monaghan-80s|Eugene 'Nudie' Hughes":"FF","monaghan-80s|Eamonn McEneaney":"HF",
 "monaghan-80s|Ray McCarron":"FF","monaghan-80s|Gerry McCarville":"FB",
 "wexford-08|Mattie Forde":"FF","wexford-08|Redmond Barry":"HF","wexford-08|PJ Banville":"FF",
 "antrim-09|Paddy Cunningham":"FF","antrim-09|Tomás McCann":"FF","antrim-09|Kevin Niblock":"HF",
 "carlow-18|Paul Broderick":"FF","carlow-18|Sean Murphy":"HB","carlow-18|Daniel St Ledger":"HB",
 "limerick-04|Jason Stokes":"FF","limerick-04|Muiris Gavin":"HF",
 "roscommon-17|Conor Cox":"FF","roscommon-17|Diarmuid Murtagh":"FF","roscommon-17|Donie Smith":"FF",
 "roscommon-17|Enda Smith":"MF","roscommon-17|Cathal Cregg":"HF"
};

/* ----------------------------------------------------------------------
   matches — classic All-Ireland finals (Missing XI, score quizzes).
   lineups: null = to be researched (use era squads as fallback).
---------------------------------------------------------------------- */
const matches = [
 {id:"final-1982", year:1982, comp:"All-Ireland Final", winner:"Offaly", loser:"Kerry", score:"1-15 to 0-17", venue:"Croke Park",
  note:"Seamus Darby's late goal denies Kerry the five-in-a-row.", lineups:null},
 {id:"final-1991", year:1991, comp:"All-Ireland Final", winner:"Down", loser:"Meath", score:"1-16 to 1-14", venue:"Croke Park",
  note:"Down become the first Ulster champions since 1968.", lineups:null},
 {id:"final-1993", year:1993, comp:"All-Ireland Final", winner:"Derry", loser:"Cork", score:"1-14 to 2-8", venue:"Croke Park",
  note:"Derry's first and only Sam Maguire.", lineups:null},
 {id:"final-1998", year:1998, comp:"All-Ireland Final", winner:"Galway", loser:"Kildare", score:"1-14 to 1-10", venue:"Croke Park",
  note:"Galway's first title since 1966 — Ja Fallon and Donnellan run riot.", lineups:null},
 {id:"final-2002", year:2002, comp:"All-Ireland Final", winner:"Armagh", loser:"Kerry", score:"1-12 to 0-14", venue:"Croke Park",
  note:"Oisín McConville's goal seals Armagh's first ever Sam.", lineups:null},
 {id:"final-2011", year:2011, comp:"All-Ireland Final", winner:"Dublin", loser:"Kerry", score:"1-12 to 1-11", venue:"Croke Park",
  note:"Cluxton's last-minute free ends Dublin's 16-year wait.", lineups:null},
 {id:"final-2020", year:2020, comp:"All-Ireland Final", winner:"Dublin", loser:"Mayo", score:"2-14 to 0-15", venue:"Croke Park",
  note:"Six in a row, behind closed doors.", lineups:null},
 {id:"final-2024", year:2024, comp:"All-Ireland Final", winner:"Armagh", loser:"Galway", score:"1-11 to 0-13", venue:"Croke Park",
  note:"Geezer's Armagh land their second Sam.", lineups:null}
];

/* ----------------------------------------------------------------------
   lists — curated answers for TenaBall / GoalLess / Lista-style games.
   answers ordered best-first; value null = ordinal only (verify before use).
---------------------------------------------------------------------- */
const lists = [
 {id:"counties-most-sams", title:"Counties with the most All-Ireland football titles",
  answers:[["Kerry",39],["Dublin",31],["Galway",9],["Meath",7],["Cork",7],["Cavan",5],["Down",5],["Wexford",5],["Tyrone",4],["Kildare",4]]},
 {id:"players-most-all-irelands", title:"Players with the most All-Ireland medals",
  answers:[["Stephen Cluxton",9],["James McCarthy",9],["Mick Fitzsimons",9],["Ciarán Kilkenny",8],["Kevin McManamon",8],["Pat Spillane",8],["Páidí Ó Sé",8],["Mikey Sheehy",8],["Ger Power",8],["Ogie Moran",8]]},
 {id:"players-most-all-stars", title:"Players with the most football All-Stars",
  answers:[["Pat Spillane",9],["Colm Cooper",8],["Mikey Sheehy",7],["Jack O'Shea",6],["Peter Canavan",6],["Ger Power",6],["David Clifford",5],["Lee Keegan",5],["Tomás Ó Sé",5],["Brian Fenton",5]]},
 {id:"famous-nicknames", title:"Match the nickname to the player",
  answers:[["Gooch — Colm Cooper",null],["The Bomber — Eoin Liston",null],["Jacko — Jack O'Shea",null],["Mugsy — Owen Mulligan",null],["Jayo — Jason Sherlock",null],["Geezer — Kieran McGeeney",null],["Star — Kieran Donaghy",null],["Ricey — Ryan McMenamin",null],["Beano — Brian McDonald",null]]},
 {id:"dual-stars", title:"Played more than one code at the top level",
  answers:[["Teddy McCarthy — football & hurling All-Irelands in 1990",null],["Liam Currams — Offaly football & hurling All-Irelands",null],["Kevin Moran — Dublin GAA & Manchester United",null],["Dave Barry — Cork GAA & League of Ireland",null],["Jack Lynch — Cork dual star & Taoiseach",null],["Des Foley — Dublin dual star",null]]},
 {id:"famous-captains", title:"Captains who lifted Sam Maguire",
  answers:[["Stephen Cluxton (Dublin ×6)",null],["Kieran McGeeney (Armagh 2002)",null],["Anthony Molloy (Donegal 1992)",null],["Henry Downey (Derry 1993)",null],["Peter Canavan (Tyrone 2003)",null],["Declan O'Sullivan (Kerry)",null],["Michael Murphy (Donegal 2012)",null],["Ray Silke (Galway 1998)",null]]}
];

/* ----------------------------------------------------------------------
   groups — seed puzzles for a GAA Connections game (4 groups of 4).
   Members are display names; they may reference players outside the era squads.
---------------------------------------------------------------------- */
const groups = [
 {id:"connections-1", groups:[
   {link:"Kilcar clubmen",            members:["Martin McHugh","Mark McHugh","Ryan McHugh","Patrick McBrearty"]},
   {link:"Austin Stacks clubmen",     members:["Mikey Sheehy","Ger Power","Charlie Nelligan","Kieran Donaghy"]},
   {link:"Scotstown clubmen",         members:["Rory Beggan","Darren Hughes","Kieran Hughes","Conor McCarthy"]},
   {link:"An Ghaeltacht clubmen",     members:["Páidí Ó Sé","Darragh Ó Sé","Tomás Ó Sé","Marc Ó Sé"]}]},
 {id:"connections-2", groups:[
   {link:"Captains who lifted Sam",   members:["Anthony Molloy","Henry Downey","Kieran McGeeney","Ray Silke"]},
   {link:"Footballer of the Year winners", members:["Lee Keegan","Trevor Giles","Pádraic Joyce","Seán Cavanagh"]},
   {link:"Goalkeepers",               members:["Stephen Cluxton","Rory Beggan","Niall Morgan","Gary Connaughton"]},
   {link:"Played another code",       members:["Teddy McCarthy","Liam Currams","Kevin Moran","Dave Barry"]}]},
 {id:"connections-3", groups:[
   {link:"Sons of county greats",     members:["Darragh Canavan","James McCartan","Dermot Earley Jnr","Bernard Brogan"]},
   {link:"Scored iconic championship goals", members:["Seamus Darby","Oisín McConville","Kevin Foley","Tommy Dowd"]},
   {link:"Brothers of teammates",     members:["Aidan O'Shea","Paudie Clifford","Neil McGee","Drew Wylie"]},
   {link:"Underdog-era legends",      members:["Matt Connor","Dessie Dolan","Ross Munnelly","Conor McManus"]}]}
];

return {
  meta:{version:2, updated:"2026-06-11", sport:"gaelic-football",
        note:"Ratings are editorial. Honours, scores and facts are best-effort from memory — verify before quoting as gospel. null = not yet researched, never zero."},
  counties,
  teams,
  players: P.map(p=>{
    const x = X[p[0]+"|"+p[1]] || {};
    return {
      id:(p[0]+"-"+p[1]).toLowerCase().replace(/[^a-z0-9]+/g,"-"),
      team:p[0], name:p[1], line:p[2], zone:Z[p[0]+"|"+p[1]]||null, rating:p[3], club:p[4],
      allIrelands:p[5], allStars:p[6],
      nickname:x.nickname||null, born:x.born||null, poty:x.poty||0,
      dual:x.dual||null, family:x.family||null, captain:x.captain||false
    };
  }),
  matches, lists, groups
};
})();
