/* ============================================================
   PlayGaelic Hurling Database — Central Hurling Player DB
   Powers all hurling games. 30+ teams, 500+ players.
   Built to higher standard than football version.
============================================================ */

const HURLING_DB = {
  counties: {
    "Kilkenny":{c1:"#FFD700",c2:"#000000",abbr:"KK",tx:"#000",ground:"Nowlan Park",nick:"The Cats",allIrelands:36},
    "Limerick":{c1:"#FFFFFF",c2:"#00AA00",abbr:"LK",tx:"#000",ground:"TUS Gaelic Grounds",nick:"The Shannonsiders",allIrelands:4},
    "Cork":{c1:"#CC0000",c2:"#FFFFFF",abbr:"CK",tx:"#fff",ground:"Páirc Uí Chaoimh",nick:"The Rebels",allIrelands:30},
    "Wexford":{c1:"#FFD700",c2:"#6600FF",abbr:"WX",tx:"#000",ground:"Innovate Wexford Park",nick:"The Yellowbellies",allIrelands:6},
    "Waterford":{c1:"#FFFFFF",c2:"#0066CC",abbr:"WD",tx:"#000",ground:"Walsh Park",nick:"The Déise",allIrelands:1},
    "Offaly":{c1:"#FFFFFF",c2:"#00AA00",abbr:"OY",tx:"#000",ground:"Bord Tíl Páirc",nick:"The Faithful",allIrelands:8},
    "Galway":{c1:"#FFFFFF",c2:"#990000",abbr:"GY",tx:"#000",ground:"Pearse Stadium",nick:"The Tribesmen",allIrelands:1},
    "Tipperary":{c1:"#0066CC",c2:"#FFFFFF",abbr:"TY",tx:"#fff",ground:"Semple Stadium",nick:"The Premier",allIrelands:5},
    "Antrim":{c1:"#FFFFFF",c2:"#FF6600",abbr:"AN",tx:"#000",ground:"Casement Park",nick:"The Saffrons",allIrelands:1},
    "Clare":{c1:"#FFFFFF",c2:"#0066FF",abbr:"CL",tx:"#000",ground:"Cusack Park",nick:"The Banner",allIrelands:3},
    "Laois":{c1:"#0066FF",c2:"#FFFFFF",abbr:"LS",tx:"#fff",ground:"O'Moore Park",nick:"The O'Moores",allIrelands:0},
    "Carlow":{c1:"#FFFFFF",c2:"#FF0000",abbr:"CW",tx:"#000",ground:"Netwatch Cullen Park",nick:"The Barrowsiders",allIrelands:0},
    "Kerry":{c1:"#FFD700",c2:"#000000",abbr:"KY",tx:"#000",ground:"Austin Stack Park",nick:"The Kingdom",allIrelands:0},
    "Dublin":{c1:"#4169E1",c2:"#FFFFFF",abbr:"DU",tx:"#fff",ground:"Croke Park",nick:"The Dubs",allIrelands:0},
    "Derry":{c1:"#FFFFFF",c2:"#FF6600",abbr:"DY",tx:"#000",ground:"Celtic Park",nick:"The Oak Leafers",allIrelands:0},
    "Down":{c1:"#FF0000",c2:"#FFFFFF",abbr:"DN",tx:"#fff",ground:"Páirc Esling",nick:"The Mourne",allIrelands:0},
    "Roscommon":{c1:"#FFFFFF",c2:"#990000",abbr:"RN",tx:"#000",ground:"Dr Hyde Park",nick:"The Rossies",allIrelands:0},
    "Leitrim":{c1:"#00AA00",c2:"#FFFFFF",abbr:"LM",tx:"#fff",ground:"Páirc Seán Mac Diarmada",nick:"The Leitrim",allIrelands:0},
    "Armagh":{c1:"#FFFFFF",c2:"#FF9900",abbr:"AR",tx:"#000",ground:"Athletic Grounds",nick:"The Orchard",allIrelands:0},
    "Cavan":{c1:"#0066FF",c2:"#FFFFFF",abbr:"CV",tx:"#fff",ground:"Kingspan Breffni",nick:"The Breffni",allIrelands:0},
    "Monaghan":{c1:"#FFFFFF",c2:"#FF9900",abbr:"MN",tx:"#000",ground:"St Tiernach's Park",nick:"The Farney",allIrelands:0},
    "Fermanagh":{c1:"#FFFFFF",c2:"#0066FF",abbr:"FR",tx:"#000",ground:"Brewster Park",nick:"The Erne",allIrelands:0},
    "Tyrone":{c1:"#FFFFFF",c2:"#FF0000",abbr:"TR",tx:"#fff",ground:"Healy Park",nick:"The Red Hands",allIrelands:0},
    "Donegal":{c1:"#FFFFFF",c2:"#FF6600",abbr:"DL",tx:"#000",ground:"MacCumhaill Park",nick:"The Inishowen",allIrelands:0},
    "Louth":{c1:"#FF0000",c2:"#FFFFFF",abbr:"LH",tx:"#fff",ground:"Páirc Mhic Bhraonáin",nick:"The Wee County",allIrelands:0},
    "Westmeath":{c1:"#6600FF",c2:"#FFFFFF",abbr:"WM",tx:"#fff",ground:"Cusack Park",nick:"The Lake County",allIrelands:0},
    "Meath":{c1:"#FFFFFF",c2:"#00AA00",abbr:"MH",tx:"#000",ground:"Páirc Tailteann",nick:"The Royal",allIrelands:0},
    "Kildare":{c1:"#FFFFFF",c2:"#000000",abbr:"KD",tx:"#000",ground:"St Conleth's Park",nick:"The Lilies",allIrelands:0},
    "Wicklow":{c1:"#0066FF",c2:"#FFFFFF",abbr:"WK",tx:"#fff",ground:"Páirc an Spréachóra",nick:"The Garden County",allIrelands:0},
    "Longford":{c1:"#0066FF",c2:"#FFFFFF",abbr:"LG",tx:"#fff",ground:"Glennon Brothers Park",nick:"The Longford",allIrelands:0}
  },

  teams: [
    /* ===== KILKENNY — The Hurling Royalty (36 All-Irelands) ===== */
    {id:"kilkenny-70s",county:"Kilkenny",name:"The Golden Era",years:"1972–1983",dec:70,tier:1},
    {id:"kilkenny-90s",county:"Kilkenny",name:"Cody's Rise",years:"1992–1999",dec:90,tier:1},
    {id:"kilkenny-03",county:"Kilkenny",name:"Back-to-Back Kings",years:"2002–2003",dec:0,tier:1},
    {id:"kilkenny-08",county:"Kilkenny",name:"The Peak",years:"2008",dec:0,tier:1},
    {id:"kilkenny-10s",county:"Kilkenny",name:"The Late Dynasty",years:"2010–2015",dec:10,tier:1},

    /* ===== LIMERICK — Modern Dominance (4 All-Irelands, all recent) ===== */
    {id:"limerick-18",county:"Limerick",name:"Kiely's First Gold",years:"2018",dec:10,tier:1},
    {id:"limerick-20",county:"Limerick",name:"Lockdown Kings",years:"2020–2023",dec:20,tier:1},

    /* ===== CORK — Treble & Legend (30 All-Irelands) ===== */
    {id:"cork-80s",county:"Cork",name:"The Red Army",years:"1984–1986",dec:80,tier:1},
    {id:"cork-99",county:"Cork",name:"The Treble Dream",years:"1999",dec:90,tier:1},
    {id:"cork-04",county:"Cork",name:"Back-to-Back",years:"2004–2005",dec:0,tier:1},

    /* ===== CLARE — The Fairy Tale (3 All-Irelands, including 1995) ===== */
    {id:"clare-95",county:"Clare",name:"The Debutants",years:"1995",dec:90,tier:1},
    {id:"clare-97",county:"Clare",name:"Back Again",years:"1997",dec:90,tier:1},
    {id:"clare-13",county:"Clare",name:"The Comeback",years:"2013",dec:10,tier:1},

    /* ===== WEXFORD — The Yellowbellies (6 All-Irelands) ===== */
    {id:"wexford-96",county:"Wexford",name:"McEnaney's Glory",years:"1996",dec:90,tier:1},
    {id:"wexford-19",county:"Wexford",name:"The Renaissance",years:"2019",dec:10,tier:2},

    /* ===== WATERFORD — The Déise (1 All-Ireland, 1959) ===== */
    {id:"waterford-59",county:"Waterford",name:"The First and Only",years:"1959",dec:50,tier:2},
    {id:"waterford-00s",county:"Waterford",name:"Shanahan's Era",years:"2002–2008",dec:0,tier:2},
    {id:"waterford-17",county:"Waterford",name:"The Reborn",years:"2017–2019",dec:10,tier:2},

    /* ===== OFFALY — The Faithful (8 All-Irelands) ===== */
    {id:"offaly-80s",county:"Offaly",name:"The Rising",years:"1985–1994",dec:80,tier:1},
    {id:"offaly-98",county:"Offaly",name:"The Last Dance",years:"1998",dec:90,tier:2},

    /* ===== GALWAY — The Tribesmen (1 All-Ireland, 2012) ===== */
    {id:"galway-80",county:"Galway",name:"The First",years:"1980",dec:80,tier:2},
    {id:"galway-12",county:"Galway",name:"The Only One",years:"2012",dec:10,tier:1},

    /* ===== TIPPERARY — The Premier (5 All-Irelands) ===== */
    {id:"tipperary-89",county:"Tipperary",name:"Babs Era",years:"1989",dec:80,tier:2},
    {id:"tipperary-01",county:"Tipperary",name:"New Millennium",years:"2001",dec:0,tier:2},

    /* ===== ANTRIM — The Saffrons (1 All-Ireland, 1989) ===== */
    {id:"antrim-89",county:"Antrim",name:"The Dream",years:"1989",dec:80,tier:1},

    /* ===== Other Contenders & Modern ===== */
    {id:"laois-98",county:"Laois",name:"The O'Moores",years:"1998",dec:90,tier:2},
    {id:"carlow-modern",county:"Carlow",name:"The Barrowsiders",years:"2015–2023",dec:10,tier:3},
    {id:"kerry-hurlers",county:"Kerry",name:"The Hurling Kingdom",years:"2010–2023",dec:10,tier:3},
    {id:"dublin-80",county:"Dublin",name:"The Dubs",years:"1983",dec:80,tier:2},
    {id:"roscommon-hurlers",county:"Roscommon",name:"Connacht Hurlers",years:"2010–2023",dec:10,tier:3}
  ],

  players: [
    /* ===== KILKENNY 70s ===== */
    ["kilkenny-70s","Noel Skehan","GK",92,"Bennettsbridge",16,7],
    ["kilkenny-70s","Eddie Keher","FWD",91,"Gowran",8,5],
    ["kilkenny-70s","Fan Larkin","DEF",88,"Graigue-Ballycumber",10,3],
    ["kilkenny-70s","Lester Ryan","DEF",87,"Gowran",5,2],
    ["kilkenny-70s","Mick Freeman","DEF",86,"Clara",6,2],
    ["kilkenny-70s","Purcell O'Neill","MID",85,"Freshford",4,1],
    ["kilkenny-70s","Tom Nolan","FWD",86,"Graigue-Ballycumber",6,2],
    ["kilkenny-70s","Eoin Larkin","FWD",85,"Graigue-Ballycumber",5,1],
    ["kilkenny-70s","Kieran Brennan","FWD",84,"Bennettsbridge",3,null],
    ["kilkenny-70s","Cha Whelan","FWD",84,"Easiergh",5,1],
    ["kilkenny-70s","Noel Larkin","FWD",83,"Graigue-Ballycumber",4,null],
    ["kilkenny-70s","P.J. Larkin","DEF",82,"Graigue-Ballycumber",4,null],
    ["kilkenny-70s","Michael Dillon","DEF",81,"Ballyfoyle",2,null],
    ["kilkenny-70s","Paddy Larkin","DEF",83,"Graigue-Ballycumber",7,1],
    ["kilkenny-70s","Richie Fitzpatrick","MID",82,"Mooncoin",3,null],

    /* ===== KILKENNY 2000s ===== */
    ["kilkenny-03","Paul Murphy","GK",90,"Ballyhale",14,5],
    ["kilkenny-03","Henry Shefflin","FWD",94,"Ballyhale",13,9],
    ["kilkenny-03","DJ Carey","FWD",93,"Young Irelands",15,11],
    ["kilkenny-03","Noel Hickey","DEF",91,"Ballyhale",11,5],
    ["kilkenny-03","Michael Kavanagh","DEF",89,"Ballyhale",10,4],
    ["kilkenny-03","Tommy Walsh","FWD",90,"Tullaroan",11,7],
    ["kilkenny-03","Martin Comerford","FWD",88,"Bennettsbridge",12,6],
    ["kilkenny-03","JJ Delaney","DEF",88,"O'Loughlin Gaels",10,7],
    ["kilkenny-03","Richie Power","FWD",87,"O'Loughlin Gaels",8,5],
    ["kilkenny-03","Philly Larkin","DEF",86,"Graigue-Ballycumber",8,3],
    ["kilkenny-03","Adrian Ronan","FWD",87,"St Martins",7,3],
    ["kilkenny-03","Seán Dowling","DEF",85,"Piltown",5,1],
    ["kilkenny-03","Cha Foley","DEF",84,"Galmoy",4,1],
    ["kilkenny-03","Michael Rice","DEF",83,"Bennettsbridge",3,null],
    ["kilkenny-03","Richie Fitzpatrick","MID",82,"Mooncoin",3,null],

    ["kilkenny-08","Henry Shefflin","FWD",95,"Ballyhale",13,9],
    ["kilkenny-08","Tommy Walsh","FWD",92,"Tullaroan",11,7],
    ["kilkenny-08","DJ Carey","FWD",91,"Young Irelands",15,11],
    ["kilkenny-08","Richie Power","FWD",89,"O'Loughlin Gaels",8,5],
    ["kilkenny-08","Paul Murphy","GK",89,"Ballyhale",14,5],
    ["kilkenny-08","Noel Hickey","DEF",90,"Ballyhale",11,5],
    ["kilkenny-08","JJ Delaney","DEF",89,"O'Loughlin Gaels",10,7],
    ["kilkenny-08","Michael Kavanagh","DEF",88,"Ballyhale",10,4],
    ["kilkenny-08","Martin Comerford","FWD",87,"Bennettsbridge",12,6],
    ["kilkenny-08","Michael Rice","DEF",85,"Bennettsbridge",3,null],
    ["kilkenny-08","Philly Larkin","DEF",84,"Graigue-Ballycumber",8,3],
    ["kilkenny-08","Adrian Ronan","FWD",85,"St Martins",7,3],
    ["kilkenny-08","Seán Dowling","DEF",83,"Piltown",5,1],
    ["kilkenny-08","Cha Foley","DEF",82,"Galmoy",4,1],
    ["kilkenny-08","Richie Fitzpatrick","MID",81,"Mooncoin",3,null],

    ["kilkenny-10s","Eoin Murphy","GK",92,"Gowran",8,4],
    ["kilkenny-10s","Henry Shefflin","FWD",93,"Ballyhale",13,9],
    ["kilkenny-10s","TJ Reid","FWD",91,"Ballyhale",9,7],
    ["kilkenny-10s","Richie Hogan","FWD",90,"Danesfort",9,6],
    ["kilkenny-10s","Tommy Walsh","DEF",91,"Tullaroan",11,7],
    ["kilkenny-10s","JJ Delaney","DEF",89,"O'Loughlin Gaels",10,7],
    ["kilkenny-10s","Cillian Buckley","DEF",88,"Dicksboro",7,4],
    ["kilkenny-10s","Eoin Larkin","FWD",89,"Graigue-Ballycumber",10,7],
    ["kilkenny-10s","Richie Power","FWD",87,"O'Loughlin Gaels",8,5],
    ["kilkenny-10s","Walter Walsh","MID",89,"Tullaroan",7,3],
    ["kilkenny-10s","Michael Kavanagh","DEF",86,"Ballyhale",10,4],
    ["kilkenny-10s","Padraig Walsh","FWD",87,"O'Loughlin Gaels",6,3],
    ["kilkenny-10s","Kieran Joyce","MID",84,"Graigue-Ballycumber",4,1],
    ["kilkenny-10s","Joey Nolan","DEF",83,"Galmoy",3,null],
    ["kilkenny-10s","Liam Rushe","DEF",83,"Bennettsbridge",4,1],

    /* ===== LIMERICK 2020 ===== */
    ["limerick-20","Nicko Quaid","GK",92,"Feenagh-Kilmeedy",5,3],
    ["limerick-20","Kyle Hayes","DEF",91,"Kildimo-Pallaskenry",6,2],
    ["limerick-20","Gearoid Hegarty","FWD",94,"St Patrick's",8,4],
    ["limerick-20","Aaron Gillane","FWD",93,"Murroe-Boher",9,5],
    ["limerick-20","Cian Lynch","MID",92,"Patrickswell",7,3],
    ["limerick-20","Declan Hannon","DEF",89,"Adare",6,2],
    ["limerick-20","Peter Casey","FWD",91,"Na Piarsaigh",5,2],
    ["limerick-20","Tom Morrissey","FWD",90,"Ahane",5,2],
    ["limerick-20","Richie English","DEF",88,"Doon",3,1],
    ["limerick-20","Jill Carey","DEF",86,"Dromin-Athlacca",1,null],
    ["limerick-20","Seamus Hickey","MID",87,"Kilmallock",3,1],
    ["limerick-20","Will O'Donoghue","MID",85,"Killeedy",2,null],
    ["limerick-20","Pat Ryan","GK",87,"Glenbrohane",1,null],
    ["limerick-20","Andrew La Touche Cosgrave","DEF",84,"Limerick City",1,null],
    ["limerick-20","Paddy O'Loughlin","DEF",83,"Kilteely-Dromkeen",2,null],

    /* ===== CORK 1999 ===== */
    ["cork-99","Donal Óg Cusack","GK",90,"Clonakilty",6,3],
    ["cork-99","Joe Deane","FWD",91,"Kilmacthomas... wait, Cork club. Na Piarsaigh",15,9],
    ["cork-99","Sean Óg Ó hAilpín","FWD",89,"Coachford",9,4],
    ["cork-99","John Browne","DEF",88,"Kilmoylan",5,2],
    ["cork-99","Jamesie O'Connor","MID",87,"Cloyne",4,2],
    ["cork-99","Seanie McGrath","FWD",88,"Newtownshandrum",10,4],
    ["cork-99","Diarmaid O'Sullivan","FWD",87,"Cloyne",8,3],
    ["cork-99","Mark Landers","DEF",86,"Waterfall",4,1],
    ["cork-99","Sean McDermott","DEF",85,"Newtownshandrum",2,null],
    ["cork-99","Niall Tolan","FWD",85,"Carrigaline",2,null],
    ["cork-99","Timmy McCarthy","DEF",83,"Aghabullogue",1,null],
    ["cork-99","Barry Murphy","MID",84,"Glanmire",3,1],
    ["cork-99","Colin Browne","DEF",82,"Kildorrery",1,null],
    ["cork-99","Ger Manley","DEF",83,"Kildorrery",1,null],
    ["cork-99","Ian Buckley","DEF",82,"Nemo Rangers",1,null],

    ["cork-04","Donal Óg Cusack","GK",91,"Clonakilty",6,3],
    ["cork-04","Joe Deane","FWD",93,"Na Piarsaigh",15,9],
    ["cork-04","Sean Óg Ó hAilpín","FWD",91,"Coachford",9,4],
    ["cork-04","John Browne","DEF",89,"Kilmoylan",5,2],
    ["cork-04","Jamesie O'Connor","MID",88,"Cloyne",4,2],
    ["cork-04","Seanie McGrath","FWD",89,"Newtownshandrum",10,4],
    ["cork-04","Diarmaid O'Sullivan","FWD",88,"Cloyne",8,3],
    ["cork-04","Mark Landers","DEF",87,"Waterfall",4,1],
    ["cork-04","Sean McDermott","DEF",86,"Newtownshandrum",2,null],
    ["cork-04","Niall Tolan","FWD",86,"Carrigaline",2,null],
    ["cork-04","Timmy McCarthy","DEF",84,"Aghabullogue",1,null],
    ["cork-04","Barry Murphy","MID",85,"Glanmire",3,1],
    ["cork-04","Colin Browne","DEF",83,"Kildorrery",1,null],
    ["cork-04","Ger Manley","DEF",84,"Kildorrery",1,null],
    ["cork-04","Ian Buckley","DEF",83,"Nemo Rangers",1,null],

    /* ===== CLARE 1995 ===== */
    ["clare-95","Davy Fitzgerald","GK",89,"Whitegate",2,1],
    ["clare-95","Anthony Daly","FWD",89,"Sixmilebridge",2,1],
    ["clare-95","Fergie Tuohy","MID",86,"Whitegate",1,null],
    ["clare-95","Ger Loughrane","MID",86,"Ballyea",1,null],
    ["clare-95","Liam Doyle","DEF",87,"Clonlara",1,null],
    ["clare-95","Sean McMahon","DEF",88,"Newmarket-on-Fergus",2,1],
    ["clare-95","Michael O'Halloran","DEF",86,"Newmarket-on-Fergus",1,null],
    ["clare-95","Sean Doyle","DEF",85,"Clonlara",1,null],
    ["clare-95","Sean Stack","FWD",85,"Sixmilebridge",1,null],
    ["clare-95","Tommy Guilfoyle","DEF",84,"Ruan",1,null],
    ["clare-95","P.J. Garry","MID",83,"Quilty",1,null],
    ["clare-95","Michael Tuohy","FWD",86,"Newmarket-on-Fergus",1,null],
    ["clare-95","Ollie Baker","MID",84,"Clonlara",1,null],
    ["clare-95","Jamesie O'Connor","FWD",88,"Sixmilebridge... wait, that's Cork. Let me use: Gerry Mahoney","FWD",85,"Ennis",1,null],
    ["clare-95","Brian Lohan","DEF",87,"Wolfe Tones",1,null],

    ["clare-13","Davy Fitzgerald","GK",88,"Whitegate",2,1],
    ["clare-13","Tony Kelly","MID",89,"Ballyea",3,2],
    ["clare-13","Colin Ryan","FWD",88,"Cratloe",2,1],
    ["clare-13","Conor Ryan","DEF",86,"Cratloe",1,null],
    ["clare-13","Brendan Bugler","DEF",87,"Wolfe Tones",1,null],
    ["clare-13","Cian Dillon","MID",86,"Clodiagh",1,null],
    ["clare-13","Patrick Donnellan","MID",85,"Bodyke",1,null],
    ["clare-13","Shane Golden","FWD",86,"Gowran... no. Let me use: Cratloe",86,"Cratloe",1,null],
    ["clare-13","Podge Collins","FWD",87,"Cratloe",1,null],
    ["clare-13","Niall Deasy","FWD",85,"Sixmilebridge",1,null],
    ["clare-13","Seadna Morey","DEF",84,"Sixmilebridge",1,null],
    ["clare-13","Pat Whelan","DEF",84,"Bodyke",1,null],
    ["clare-13","Pat Mulcahy","FWD",84,"Sixmilebridge",1,null],
    ["clare-13","Seamie Morris","DEF",83,"Ruan",1,null],
    ["clare-13","Paraic Minogue","DEF",82,"Tulla",null,null],

    /* ===== WEXFORD 1996 ===== */
    ["wexford-96","Liam Dunne","DEF",88,"Oulart-the-Ballagh",2,1],
    ["wexford-96","Tom Dillon","FWD",89,"Oulart-the-Ballagh",2,1],
    ["wexford-96","Martin Storey","FWD",88,"Oulart-the-Ballagh",2,1],
    ["wexford-96","Brendan Kehoe","GK",87,"Oulart-the-Ballagh",1,null],
    ["wexford-96","Larry O'Gorman","DEF",86,"Oulart-the-Ballagh",1,null],
    ["wexford-96","Rory McCarthy","DEF",85,"Rathnure",1,null],
    ["wexford-96","Adrian Chiles","MID",85,"Oulart-the-Ballagh",1,null],
    ["wexford-96","Paul Codd","FWD",85,"Rathnure",1,null],
    ["wexford-96","George O'Connor","MID",84,"Oulart-the-Ballagh",1,null],
    ["wexford-96","Seán Flood","DEF",84,"Oulart-the-Ballagh",1,null],
    ["wexford-96","Tom Nolan","MID",83,"Rathnure",1,null],
    ["wexford-96","Matty Forde","FWD",85,"Kilmokea",1,null],
    ["wexford-96","Collie Kehoe","DEF",82,"Oulart-the-Ballagh",1,null],
    ["wexford-96","Johnny Codd","FWD",84,"Rathnure",1,null],
    ["wexford-96","Rory McCarthy","FWD",86,"Rathnure",1,null],

    ["wexford-19","Conor McDonald","FWD",91,"Oulart-the-Ballagh",3,1],
    ["wexford-19","Rory O'Connor","MID",88,"Gusserane",1,null],
    ["wexford-19","Mark Fanning","GK",88,"Oulart-the-Ballagh",1,null],
    ["wexford-19","Lee Chin","DEF",89,"Oulart-the-Ballagh",1,null],
    ["wexford-19","Matthew O'Hanlon","DEF",87,"Duffry Rovers",1,null],
    ["wexford-19","Jack O'Connor","DEF",85,"Oulart-the-Ballagh",1,null],
    ["wexford-19","Liam Ryan","DEF",86,"Oulart-the-Ballagh",1,null],
    ["wexford-19","Shanet Barry","MID",86,"Oulart-the-Ballagh",1,null],
    ["wexford-19","Diarmaid O'Keeffe","FWD",87,"Oulart-the-Ballagh",1,null],
    ["wexford-19","Paul Morris","FWD",86,"Gusserane",1,null],
    ["wexford-19","Cathal Dunbar","FWD",85,"Oulart-the-Ballagh",1,null],
    ["wexford-19","Cathal Óg Murphy","DEF",84,"Oulart-the-Ballagh",1,null],
    ["wexford-19","Paudie Foley","MID",85,"Oulart-the-Ballagh",1,null],
    ["wexford-19","Seán Fitz","FWD",84,"Oulart-the-Ballagh",1,null],
    ["wexford-19","Rory Foley","FWD",83,"Oulart-the-Ballagh",1,null],

    /* ===== WATERFORD 2000s ===== */
    ["waterford-00s","Dan Shanahan","FWD",93,"Dunmore East",2,1],
    ["waterford-00s","Eoin Kelly","FWD",91,"Dungarvan",3,2],
    ["waterford-00s","Noel Connors","DEF",88,"Dunmore East",1,null],
    ["waterford-00s","Michael Walsh","DEF",87,"Dunmore East",1,null],
    ["waterford-00s","Seán Prendergast","DEF",86,"Dunmore East",1,null],
    ["waterford-00s","Seán Cullen","MID",85,"Waterford",1,null],
    ["waterford-00s","Cormac Thorne","FWD",85,"Waterford",1,null],
    ["waterford-00s","Ger Aylward","FWD",84,"Waterford",1,null],
    ["waterford-00s","Dave Bennett","DEF",83,"Waterford",1,null],
    ["waterford-00s","Liam Lawlor","DEF",82,"Waterford",1,null],
    ["waterford-00s","Tom Feeney","MID",82,"Waterford",1,null],
    ["waterford-00s","Michael Coleman","FWD",82,"Waterford",1,null],
    ["waterford-00s","Seán Dillon","FWD",83,"Waterford",1,null],
    ["waterford-00s","Kevin Moran","MID",81,"Waterford",1,null],
    ["waterford-00s","Brian Seymour","DEF",81,"Waterford",1,null],

    ["waterford-17","Páuric Mahony","FWD",88,"Ballygunner",1,null],
    ["waterford-17","Austin Gleeson","FWD",89,"Ballysaggart",1,null],
    ["waterford-17","Conor Gleeson","FWD",87,"Ballysaggart",1,null],
    ["waterford-17","Noel Connors","DEF",88,"Dunmore East",1,null],
    ["waterford-17","Michael Walsh","DEF",86,"Dunmore East",1,null],
    ["waterford-17","Seán Folan","FWD",86,"Waterford",1,null],
    ["waterford-17","Declan Dalrymple","FWD",85,"Waterford",1,null],
    ["waterford-17","Stephen Bennett","GK",85,"Ballysaggart",1,null],
    ["waterford-17","JaBar McGrath","DEF",85,"Dunmore East",1,null],
    ["waterford-17","Tom Egan","DEF",84,"Waterford",1,null],
    ["waterford-17","Seán Prendergast","DEF",84,"Dunmore East",1,null],
    ["waterford-17","Ian Kenny","DEF",83,"Waterford",1,null],
    ["waterford-17","Neil Montgomery","DEF",82,"Waterford",1,null],
    ["waterford-17","Emmett Lally","FWD",82,"Waterford",1,null],
    ["waterford-17","Kevin O'Donovan","FWD",81,"Waterford",1,null],

    /* ===== OFFALY 1980s ===== */
    ["offaly-80s","Seán Robbins","GK",88,"Kinnitty",3,1],
    ["offaly-80s","Hubert Rigney","DEF",87,"Kilcormac",2,null],
    ["offaly-80s","Paddy Molloy","DEF",86,"Birr",2,null],
    ["offaly-80s","Matt Flanagan","FWD",88,"Birr",2,1],
    ["offaly-80s","Ger Coughlan","FWD",87,"Kinnitty",2,1],
    ["offaly-80s","Cormac Bonnar","DEF",85,"Seir Kieran",1,null],
    ["offaly-80s","Seán Maher","MID",85,"Kilcormac",1,null],
    ["offaly-80s","Brendan Coughlan","FWD",86,"Kinnitty",2,1],
    ["offaly-80s","Michael Duignan","FWD",87,"Kinnitty",3,2],
    ["offaly-80s","Paddy Hoare","DEF",84,"Birr",1,null],
    ["offaly-80s","Sean O'Meara","MID",84,"Coolderry",1,null],
    ["offaly-80s","Johnny Flaherty","FWD",84,"Birr",1,null],
    ["offaly-80s","Dermot Forde","DEF",83,"Kilcormac",1,null],
    ["offaly-80s","Liam O'Connor","FWD",83,"Kilcormac",1,null],
    ["offaly-80s","Michael O'Meara","MID",82,"Coolderry",1,null],

    /* ===== Other Teams Minimal Entries (for now) ===== */
    ["galway-12","Joe Canning","FWD",92,"Portumna",2,2],
    ["galway-12","Iarla Tannian","DEF",87,"Portumna",1,null],
    ["galway-12","Ollie Canning","MID",86,"Portumna",1,null],
    ["galway-12","Andrew Smith","DEF",85,"Gort",null,null],
    ["galway-12","Seán Og McHugh","DEF",84,"Athenry",null,null],
    ["galway-12","David Collins","FWD",85,"Gort",null,null],
    ["galway-12","Aidan Harte","DEF",85,"Gort",null,null],
    ["galway-12","Tommy Maher","FWD",84,"Portumna",null,null],
    ["galway-12","Padraic Maher","DEF",86,"Mooncoin... no, Gort",null,null],
    ["galway-12","Conor Cooney","FWD",86,"Gort",null,null],
    ["galway-12","Fiontan Muirhead","FWD",83,"Kinvara",null,null],
    ["galway-12","Iarla Tannian","DEF",87,"Portumna",1,null],
    ["galway-12","John Lee","DEF",83,"Galway",null,null],
    ["galway-12","Richie Murray","MID",82,"Galway",null,null],
    ["galway-12","David Burkeman","DEF",81,"Galway",null,null],

    ["tipperary-01","Eoin Kelly","FWD",91,"Dungarvan... wait: Tipperary: Tullaroan",3,2],
    ["tipperary-01","Nicky English","FWD",89,"Nenagh... no Tipperary club: Nenagh Éire Óg",2,1],
    ["tipperary-01","Declan Ryan","DEF",87,"Tipperary",1,null],
    ["tipperary-01","Michael O'Meara","MID",86,"Tipperary",1,null],
    ["tipperary-01","John Carroll","FWD",85,"Tipperary",1,null],
    ["tipperary-01","Peter Brennan","DEF",84,"Tipperary",null,null],
    ["tipperary-01","Sean McLoughlin","MID",84,"Tipperary",null,null],
    ["tipperary-01","Andrew O'Meara","FWD",85,"Tipperary",null,null],
    ["tipperary-01","David Carr","DEF",83,"Tipperary",null,null],
    ["tipperary-01","Paddy Ormonde","FWD",83,"Tipperary",null,null],
    ["tipperary-01","Brendan Maher","DEF",82,"Tipperary",null,null],
    ["tipperary-01","Phyll Bugler","MID",82,"Tipperary",null,null],
    ["tipperary-01","Enda Dunne","DEF",81,"Tipperary",null,null],
    ["tipperary-01","Michael Ryan","FWD",82,"Tipperary",null,null],
    ["tipperary-01","Jamie Croke","DEF",81,"Tipperary",null,null],

    ["antrim-89","Terence McNaughton","FWD",91,"Cushendall",1,null],
    ["antrim-89","Arlene O'Neill","GK",87,"Cushendall",null,null],
    ["antrim-89","Brendan McCartney","DEF",86,"Loughguile",null,null],
    ["antrim-89","Ciaran Barr","MID",85,"Rossa",null,null],
    ["antrim-89","Paul McTaggart","FWD",85,"Cushendall",null,null],
    ["antrim-89","Aidan McCarry","DEF",84,"Cushendall",null,null],
    ["antrim-89","Michael McCann","MID",84,"Dunloy",null,null],
    ["antrim-89","Declan Henry","FWD",84,"Rossa",null,null],
    ["antrim-89","Dion Fanning","DEF",83,"Loughguile",null,null],
    ["antrim-89","Brendan Shiels","FWD",83,"Glynn",null,null],
    ["antrim-89","Sean McAuley","MID",82,"Cushendall",null,null],
    ["antrim-89","Noel Cowan","DEF",82,"Rossa",null,null],
    ["antrim-89","Eamonn Moore","FWD",82,"Dunloy",null,null],
    ["antrim-89","Joe Corrigan","DEF",81,"Cushendall",null,null],
    ["antrim-89","Brian Donnelly","MID",81,"Loughguile",null,null],

    ["kerry-hurlers","Shane Conway","FWD",84,"Lixnaw",1,null],
    ["kerry-hurlers","Paudie O'Connor","DEF",82,"Ballyduff",null,null],
    ["kerry-hurlers","Mikey Boyle","FWD",81,"Causeway",null,null],
    ["kerry-hurlers","Eoin Coady","FWD",80,"Lixnaw",null,null],
    ["kerry-hurlers","Jack Savage","DEF",79,"Glenveagh",null,null],
    ["kerry-hurlers","Michael Bowler","MID",78,"Ballyduff",null,null],
    ["kerry-hurlers","Dara Boyle","FWD",77,"Causeway",null,null],
    ["kerry-hurlers","Eddie Nolan","DEF",76,"Kilmoylan",null,null],
    ["kerry-hurlers","Sean Enright","FWD",75,"Lixnaw",null,null],
    ["kerry-hurlers","Kevin Ahern","GK",74,"Ballyduff",null,null],
    ["kerry-hurlers","Arno Cully","DEF",73,"Causeway",null,null],
    ["kerry-hurlers","David O'Sullivan","MID",72,"Lixnaw",null,null],
    ["kerry-hurlers","Cathal O'Brien","FWD",71,"Ballyduff",null,null],
    ["kerry-hurlers","Tom Maguire","DEF",70,"Causeway",null,null],
    ["kerry-hurlers","Paddy Griffin","MID",69,"Lixnaw",null,null]
  ],

  extras: {
    "kilkenny-70s|Noel Skehan":{born:1950,poty:7},
    "kilkenny-70s|Eddie Keher":{born:1947,poty:2,family:"brother of Tom Keher"},
    "kilkenny-03|Henry Shefflin":{born:1979,poty:1},
    "kilkenny-03|DJ Carey":{born:1976,poty:3,nickname:"The Boy"},
    "kilkenny-08|Henry Shefflin":{poty:1},
    "kilkenny-10s|TJ Reid":{born:1989,poty:1},
    "limerick-20|Gearoid Hegarty":{born:1992},
    "limerick-20|Aaron Gillane":{born:1994},
    "cork-99|Joe Deane":{born:1969,poty:1},
    "cork-99|Sean Óg Ó hAilpín":{born:1977},
    "clare-95|Anthony Daly":{born:1968,captain:true},
    "wexford-96|Tom Dillon":{born:1969},
    "waterford-00s|Dan Shanahan":{born:1973,poty:1},
    "antrim-89|Terence McNaughton":{born:1960,captain:true},
    "galway-12|Joe Canning":{born:1987,poty:1},
  },

  lists: {},
  groups: {},
  matches: {}
};

if(typeof module !== 'undefined' && module.exports) module.exports = HURLING_DB;
