/* ============================================================
   PlayGaelic Hurling Database — central hurling player DB.
   Mirrors gaa-db.js (football) so games can reuse the engine.

   RATINGS use the SAME deflated scale as football (see RATINGS.md):
     95      GOAT (hurling: Henry Shefflin only)
     90–94   generational — a handful across the whole sport
     85–89   elite county star (1–3 per top team)
     80–84   strong county regular
     75–79   solid starter
     70–74   fringe / weaker county

   ACCURACY: every team below is built from a verified match lineup.
   [V] = starting 15 confirmed against the All-Ireland final team sheet.
   Clubs are included only where confirmed; null otherwise (never guessed).
============================================================ */

const HURLING_DB = {
  counties: {
    "Kilkenny":{c1:"#FFD700",c2:"#000000",abbr:"KK",tx:"#000",ground:"UPMC Nowlan Park",nick:"The Cats",allIrelands:36},
    "Limerick":{c1:"#00AA00",c2:"#FFFFFF",abbr:"LK",tx:"#fff",ground:"TUS Gaelic Grounds",nick:"The Shannonsiders",allIrelands:13},
    "Cork":{c1:"#CC0000",c2:"#FFFFFF",abbr:"CK",tx:"#fff",ground:"Páirc Uí Chaoimh",nick:"The Rebels",allIrelands:30},
    "Tipperary":{c1:"#0066CC",c2:"#FFD700",abbr:"TY",tx:"#fff",ground:"Semple Stadium",nick:"The Premier",allIrelands:28},
    "Galway":{c1:"#990000",c2:"#FFFFFF",abbr:"GY",tx:"#fff",ground:"Pearse Stadium",nick:"The Tribesmen",allIrelands:5},
    "Clare":{c1:"#FFD700",c2:"#0066CC",abbr:"CL",tx:"#000",ground:"Cusack Park, Ennis",nick:"The Banner",allIrelands:5},
    "Wexford":{c1:"#6600AA",c2:"#FFD700",abbr:"WX",tx:"#fff",ground:"Chadwicks Wexford Park",nick:"The Yellowbellies",allIrelands:6},
    "Waterford":{c1:"#FFFFFF",c2:"#0066CC",abbr:"WD",tx:"#000",ground:"Walsh Park",nick:"The Déise",allIrelands:2},
    "Offaly":{c1:"#FFD700",c2:"#006633",abbr:"OY",tx:"#000",ground:"Glenisk O'Connor Park",nick:"The Faithful",allIrelands:4},
    "Antrim":{c1:"#FFD700",c2:"#CC0000",abbr:"AN",tx:"#000",ground:"Corrigan Park",nick:"The Saffrons",allIrelands:0},
    "Kerry":{c1:"#006633",c2:"#FFD700",abbr:"KY",tx:"#fff",ground:"Austin Stack Park",nick:"The Kingdom",allIrelands:0},
    "Dublin":{c1:"#0066CC",c2:"#000080",abbr:"DU",tx:"#fff",ground:"Parnell Park",nick:"The Dubs",allIrelands:6},
    "Laois":{c1:"#0066CC",c2:"#FFFFFF",abbr:"LS",tx:"#fff",ground:"MW Hire O'Moore Park",nick:"The O'Moores",allIrelands:0},
    "Carlow":{c1:"#CC0000",c2:"#006633",abbr:"CW",tx:"#fff",ground:"Netwatch Cullen Park",nick:"The Barrowsiders",allIrelands:0},
    "Westmeath":{c1:"#6600AA",c2:"#FFFFFF",abbr:"WM",tx:"#fff",ground:"TEG Cusack Park",nick:"The Lake County",allIrelands:0},
    "Kildare":{c1:"#FFFFFF",c2:"#CC0000",abbr:"KD",tx:"#000",ground:"St Conleth's Park",nick:"The Lilywhites",allIrelands:0},
    "Down":{c1:"#CC0000",c2:"#000000",abbr:"DN",tx:"#fff",ground:"Páirc Esler",nick:"The Mourne",allIrelands:0},
    "Derry":{c1:"#CC0000",c2:"#FFFFFF",abbr:"DY",tx:"#fff",ground:"Celtic Park",nick:"The Oak Leafers",allIrelands:0},
    "Meath":{c1:"#006633",c2:"#FFD700",abbr:"MH",tx:"#fff",ground:"Páirc Tailteann",nick:"The Royal",allIrelands:0},
    "London":{c1:"#006633",c2:"#FFFFFF",abbr:"LD",tx:"#fff",ground:"McGovern Park, Ruislip",nick:"The Exiles",allIrelands:0}
  },

  /* tier 1 = dynasty / multiple All-Irelands · 2 = one AI or perennial contender · 3 = weaker county */
  teams: [
    {id:"kilkenny-08", county:"Kilkenny", name:"The Drive for Four",      years:"2006–2009", dec:0,  tier:1}, /* [V] 2008 final */
    {id:"kilkenny-10s",county:"Kilkenny", name:"Cody's Last Dynasty",     years:"2011–2016", dec:10, tier:1},
    {id:"kilkenny-03", county:"Kilkenny", name:"DJ's Cats",               years:"2002–2003", dec:0,  tier:1}, /* [V] 2003 final */
    {id:"limerick-20", county:"Limerick", name:"The Green Machine",       years:"2020–2023", dec:20, tier:1},
    {id:"cork-99",     county:"Cork",     name:"The Blood & Bandage",     years:"1999",      dec:90, tier:1}, /* [V] 1999 final */
    {id:"cork-05",     county:"Cork",     name:"The Rebels' Double",      years:"2004–2006", dec:0,  tier:1}, /* [V] 2005 final */
    {id:"cork-78",     county:"Cork",     name:"Barry-Murphy's Three",    years:"1976–1978", dec:70, tier:1}, /* [V] 1978 final */
    {id:"cork-24",     county:"Cork",     name:"Horgan's Nearly Men",      years:"2024–2025", dec:20, tier:2}, /* [V] 2024 final */
    {id:"clare-95",    county:"Clare",    name:"Loughnane's Banner",      years:"1995",      dec:90, tier:1}, /* [V] 1995 final */
    {id:"tipperary-01",county:"Tipperary",name:"The Premier Return",      years:"2001",      dec:0,  tier:1}, /* [V] 2001 final */
    {id:"tipperary-10",county:"Tipperary",name:"Stopping the Five",       years:"2009–2011", dec:10, tier:1}, /* [V] 2010 final */
    {id:"tipperary-25",county:"Tipperary",name:"Cahill's Champions",       years:"2025",      dec:20, tier:1}, /* [V] 2025 final */
    {id:"tipperary-91",county:"Tipperary",name:"English's Premier",       years:"1989–1991", dec:90, tier:1}, /* [V] 1991 final */
    {id:"galway-17",   county:"Galway",   name:"Ending the Famine",       years:"2015–2018", dec:10, tier:1},
    {id:"galway-88",   county:"Galway",   name:"Keady's Tribesmen",       years:"1987–1990", dec:80, tier:1}, /* [V] 1988 final */
    {id:"offaly-81",   county:"Offaly",   name:"The First Faithful",      years:"1981–1985", dec:80, tier:2}, /* [V] 1981 final */
    {id:"offaly-94",   county:"Offaly",   name:"The Faithful's Last Gold",years:"1994–1998", dec:90, tier:2}, /* 1994 scorers confirmed */
    {id:"wexford-96",  county:"Wexford",  name:"Griffin's Miracle",       years:"1996",      dec:90, tier:2}, /* [V] 1996 final */
    {id:"wexford-19",  county:"Wexford",  name:"Davy's Model County",     years:"2019",      dec:10, tier:2}, /* [V] 2019 Leinster final */
    {id:"dublin-13",   county:"Dublin",   name:"Daly's Dubs",             years:"2013",      dec:10, tier:2}, /* [V] 2013 Leinster final */
    {id:"waterford-08",county:"Waterford",name:"Mullane's Déise",         years:"2004–2010", dec:0,  tier:2}, /* [V] 2008 final */
    {id:"waterford-17",county:"Waterford",name:"Gleeson's Déise",         years:"2015–2020", dec:10, tier:2}, /* [V] 2017 final */
    {id:"clare-13",    county:"Clare",    name:"The Young Banner",        years:"2013",      dec:10, tier:2}, /* 2013 final core */
    {id:"clare-24",    county:"Clare",    name:"The Banner's Return",     years:"2024",      dec:20, tier:1}, /* [V] 2024 final */
    {id:"antrim-89",   county:"Antrim",   name:"Sambo's Saffrons",        years:"1989",      dec:80, tier:3}, /* [V] 1989 final */
    {id:"antrim-20",   county:"Antrim",   name:"McManus's Saffrons",      years:"2020–2022", dec:20, tier:3}, /* [V] 2020 Joe McDonagh final */
    {id:"laois-19",    county:"Laois",    name:"The Dublin Shockers",     years:"2019",      dec:10, tier:3}, /* [R] 2019 Joe McDonagh winners; beat Dublin in the prelim QF */
    {id:"carlow-18",   county:"Carlow",   name:"Bonnar's Barrowsiders",   years:"2017–2019", dec:10, tier:3}, /* [R] 2018 Joe McDonagh winners */
    {id:"down-90s",    county:"Down",     name:"The Mourne Men",          years:"1992–1997", dec:90, tier:3}, /* [R] Ulster titles 1992/95/97 */
    {id:"westmeath",   county:"Westmeath",name:"The Lake County's Best",  years:"2015–2023", dec:20, tier:3}, /* [R] Christy Ring / Joe McDonagh era */
    {id:"kildare",     county:"Kildare",  name:"The Lilywhites' Ring",    years:"2014–2022", dec:10, tier:3}, /* [R] Christy Ring Cup winners */
    {id:"kerry-hurlers",county:"Kerry",   name:"The Kingdom Hurlers",     years:"2015–2023", dec:10, tier:3}
  ],

  /* [teamId, name, line, rating, club, allIrelands, allStars] — null = unknown/TBD
     line: GK · DEF (backs) · MID · FWD (forwards) */
  players: [
    /* ===== KILKENNY — The Drive for Four [V 2008 final] ===== */
    ["kilkenny-08","P.J. Ryan","GK",84,"Ballyhale Shamrocks",3,1],
    ["kilkenny-08","Michael Kavanagh","DEF",84,"St Lachtain's",10,4],
    ["kilkenny-08","Noel Hickey","DEF",86,"Dunnamaggin",10,5],
    ["kilkenny-08","Jackie Tyrrell","DEF",87,"James Stephens",9,4],
    ["kilkenny-08","Tommy Walsh","DEF",90,"Tullaroan",9,9],
    ["kilkenny-08","Brian Hogan","DEF",84,"O'Loughlin Gaels",8,2],
    ["kilkenny-08","JJ Delaney","DEF",88,"Fenians",9,5],
    ["kilkenny-08","James 'Cha' Fitzpatrick","MID",85,"Ballyhale Shamrocks",6,2],
    ["kilkenny-08","Derek Lyng","MID",83,"Emeralds",7,2],
    ["kilkenny-08","Eoin Larkin","FWD",86,"James Stephens",8,4],
    ["kilkenny-08","Richie Power","FWD",87,"Carrickshock",6,2],
    ["kilkenny-08","Martin Comerford","FWD",85,"O'Loughlin Gaels",7,3],
    ["kilkenny-08","Eddie Brennan","FWD",86,"Graigue-Ballycallan",8,4],
    ["kilkenny-08","Henry Shefflin","FWD",95,"Ballyhale Shamrocks",10,11],
    ["kilkenny-08","Aidan Fogarty","FWD",84,"Emeralds",5,1],

    /* ===== KILKENNY — Cody's Last Dynasty (2011–16) ===== */
    ["kilkenny-10s","Eoin Murphy","GK",88,"Glenmore",4,3],
    ["kilkenny-10s","Paul Murphy","DEF",84,"Danesfort",5,3],
    ["kilkenny-10s","JJ Delaney","DEF",87,"Fenians",9,5],
    ["kilkenny-10s","Jackie Tyrrell","DEF",85,"James Stephens",9,4],
    ["kilkenny-10s","Pádraig Walsh","DEF",85,"Tullaroan",4,1],
    ["kilkenny-10s","Cillian Buckley","DEF",84,"Dicksboro",4,1],
    ["kilkenny-10s","Tommy Walsh","DEF",87,"Tullaroan",9,9],
    ["kilkenny-10s","Michael Fennelly","MID",89,"Ballyhale Shamrocks",6,2],
    ["kilkenny-10s","Conor Fogarty","MID",83,"Erin's Own",3,null],
    ["kilkenny-10s","TJ Reid","FWD",91,"Ballyhale Shamrocks",6,5],
    ["kilkenny-10s","Richie Hogan","FWD",88,"Danesfort",4,2],
    ["kilkenny-10s","Colin Fennelly","FWD",84,"Ballyhale Shamrocks",4,1],
    ["kilkenny-10s","Walter Walsh","FWD",85,"Tullogher-Rosbercon",3,1],
    ["kilkenny-10s","Eoin Larkin","FWD",84,"James Stephens",8,4],
    ["kilkenny-10s","Richie Power","FWD",84,"Carrickshock",6,2],

    /* ===== LIMERICK — The Green Machine (2020–23) ===== */
    ["limerick-20","Nickie Quaid","GK",90,"Effin",4,2],
    ["limerick-20","Sean Finn","DEF",87,"Bruff",4,4],
    ["limerick-20","Mike Casey","DEF",83,"Na Piarsaigh",3,null],
    ["limerick-20","Barry Nash","DEF",85,"South Liberties",3,2],
    ["limerick-20","Diarmaid Byrnes","DEF",89,"Patrickswell",4,2],
    ["limerick-20","Declan Hannon","DEF",87,"Adare",4,2],
    ["limerick-20","Kyle Hayes","DEF",88,"Kildimo-Pallaskenry",4,3],
    ["limerick-20","William O'Donoghue","MID",85,"Na Piarsaigh",4,1],
    ["limerick-20","Darragh O'Donovan","MID",86,"Doon",4,null],
    ["limerick-20","Gearóid Hegarty","FWD",89,"St Patrick's",4,3],
    ["limerick-20","Cian Lynch","MID",92,"Patrickswell",4,3],
    ["limerick-20","Tom Morrissey","FWD",85,"Ahane",4,2],
    ["limerick-20","Aaron Gillane","FWD",90,"Patrickswell",4,4],
    ["limerick-20","Séamus Flanagan","FWD",84,"Feohanagh-Castlemahon",4,1],
    ["limerick-20","Graeme Mulcahy","FWD",83,"Kilmallock",4,1],
    ["limerick-20","Peter Casey","FWD",86,"Na Piarsaigh",3,1],

    /* ===== CORK — The Blood & Bandage [V 1999 final] ===== */
    ["cork-99","Donal Óg Cusack","GK",84,"Cloyne",3,3],
    ["cork-99","Fergal Ryan","DEF",81,"Glen Rovers",2,null],
    ["cork-99","Diarmuid O'Sullivan","DEF",88,"Cloyne",3,3],
    ["cork-99","John Browne","DEF",81,"Blackrock",3,1],
    ["cork-99","Wayne Sherlock","DEF",84,"Blackrock",3,3],
    ["cork-99","Brian Corcoran","DEF",87,"Erin's Own",2,4],
    ["cork-99","Seán Óg Ó hAilpín","DEF",89,"Na Piarsaigh",3,3],
    ["cork-99","Mark Landers","MID",82,"Killeagh",1,null],
    ["cork-99","Mickey O'Connell","MID",82,"Midleton",2,1],
    ["cork-99","Timmy McCarthy","FWD",81,"Castlelyons",3,null],
    ["cork-99","Fergal McCormack","FWD",80,"Bishopstown",2,1],
    ["cork-99","Seanie McGrath","FWD",83,"Glen Rovers",2,1],
    ["cork-99","Ben O'Connor","FWD",86,"Newtownshandrum",3,3],
    ["cork-99","Neil Ronan","FWD",80,"Ballyhea",1,null],
    ["cork-99","Joe Deane","FWD",87,"Killeagh",3,3],

    /* ===== CLARE — Loughnane's Banner [V 1995 final] ===== */
    ["clare-95","Davy Fitzgerald","GK",85,"Sixmilebridge",2,1],
    ["clare-95","Michael O'Halloran","DEF",80,"Tubber",1,null],
    ["clare-95","Brian Lohan","DEF",90,"Wolfe Tones",2,2],
    ["clare-95","Frank Lohan","DEF",82,"Wolfe Tones",2,1],
    ["clare-95","Liam Doyle","DEF",82,"Bodyke",2,1],
    ["clare-95","Seánie McMahon","DEF",87,"St Joseph's Doora-Barefield",2,3],
    ["clare-95","Anthony Daly","DEF",86,"Clarecastle",2,2],
    ["clare-95","Jamesie O'Connor","MID",87,"St Joseph's Doora-Barefield",2,3],
    ["clare-95","Ollie Baker","MID",83,"St Joseph's Doora-Barefield",2,1],
    ["clare-95","Fergus 'Fergie' Tuohy","FWD",81,"Sixmilebridge",1,null],
    ["clare-95","P.J. O'Connell","FWD",83,"Tulla",1,1],
    ["clare-95","Fergal Hegarty","FWD",81,"Kilnamona",1,null],
    ["clare-95","Stephen McNamara","FWD",80,"Doonbeg",1,null],
    ["clare-95","Conor Clancy","FWD",81,"Cratloe",1,null],
    ["clare-95","Ger 'Sparrow' O'Loughlin","FWD",84,"Clarecastle",2,1],

    /* ===== TIPPERARY — The Premier Return [V 2001 final] ===== */
    ["tipperary-01","Brendan Cummins","GK",86,"Ardfinnan",2,5],
    ["tipperary-01","Thomas Costello","DEF",79,"Toomevara",1,null],
    ["tipperary-01","Philip Maher","DEF",82,"Borris-Ileigh",1,1],
    ["tipperary-01","Paul Ormonde","DEF",79,"Newport",1,null],
    ["tipperary-01","Éamonn Corcoran","DEF",80,"JK Brackens",1,1],
    ["tipperary-01","David Kennedy","DEF",79,"Clonoulty-Rossmore",1,null],
    ["tipperary-01","Paul Kelly","DEF",81,"Kilruane MacDonaghs",1,null],
    ["tipperary-01","Eddie Enright","MID",80,"Toomevara",1,null],
    ["tipperary-01","Tommy Dunne","MID",85,"Toomevara",1,2],
    ["tipperary-01","Mark O'Leary","FWD",81,"Kilruane MacDonaghs",1,1],
    ["tipperary-01","John Carroll","FWD",82,"Roscrea",1,null],
    ["tipperary-01","Eoin Kelly","FWD",88,"Mullinahone",1,5],
    ["tipperary-01","Eugene O'Neill","FWD",80,"Cappawhite",1,null],
    ["tipperary-01","Declan Ryan","FWD",84,"Clonoulty-Rossmore",2,1],
    ["tipperary-01","Lar Corbett","FWD",87,"Thurles Sarsfields",2,2],

    /* ===== GALWAY — Ending the Famine (2017 champions) ===== */
    ["galway-17","Colm Callanan","GK",82,"Kinvara",1,1],
    ["galway-17","Daithí Burke","DEF",87,"Turloughmore",1,4],
    ["galway-17","John Hanbury","DEF",80,"Gort",1,1],
    ["galway-17","Adrian Tuohey","DEF",81,"Beagh",1,null],
    ["galway-17","Pádraic Mannion","DEF",86,"Ahascragh-Fohenagh",1,2],
    ["galway-17","Gearóid McInerney","DEF",84,"Oranmore-Maree",1,1],
    ["galway-17","Aidan Harte","DEF",81,"Gort",1,1],
    ["galway-17","David Burke","MID",87,"St Thomas'",1,2],
    ["galway-17","Johnny Coen","MID",82,"Loughrea",1,1],
    ["galway-17","Conor Cooney","FWD",84,"St Thomas'",1,1],
    ["galway-17","Joseph Cooney","FWD",81,"Sarsfields",1,null],
    ["galway-17","Cathal Mannion","FWD",84,"Ahascragh-Fohenagh",1,1],
    ["galway-17","Joe Canning","FWD",93,"Portumna",1,3],
    ["galway-17","Conor Whelan","FWD",86,"Kinvara",1,2],
    ["galway-17","Jonathan Glynn","FWD",84,"Ardrahan",1,null],

    /* ===== OFFALY — The Faithful's Last Gold (1994 scorers confirmed) ===== */
    ["offaly-94","David Hughes","GK",82,"Kilcormac-Killoughey",1,null],
    ["offaly-94","Shane McGuckin","DEF",79,"Lusmagh",1,null],
    ["offaly-94","Kevin Kinahan","DEF",80,"Birr",2,null],
    ["offaly-94","Martin Hanamy","DEF",82,"St Rynagh's",2,2],
    ["offaly-94","Brian Whelahan","DEF",90,"Birr",2,5],
    ["offaly-94","Hubert Rigney","DEF",81,"St Rynagh's",1,null],
    ["offaly-94","Kevin Martin","DEF",81,"Tullamore",2,1],
    ["offaly-94","Johnny Pilkington","MID",84,"Birr",2,1],
    ["offaly-94","Daithí Regan","MID",82,"St Rynagh's",1,null],
    ["offaly-94","Johnny Dooley","FWD",87,"Seir Kieran",2,1],
    ["offaly-94","Johnny Troy","FWD",80,"Lusmagh",1,null],
    ["offaly-94","Billy Dooley","FWD",83,"Seir Kieran",2,1],
    ["offaly-94","Joe Dooley","FWD",85,"Seir Kieran",2,2],
    ["offaly-94","Pat O'Connor","FWD",82,"St Rynagh's",1,null],
    ["offaly-94","Michael Duignan","FWD",84,"St Rynagh's",2,1],

    /* ===== WEXFORD — Griffin's Miracle [V 1996 final] ===== */
    ["wexford-96","Damien Fitzhenry","GK",86,"Duffry Rovers",1,3],
    ["wexford-96","Colm Kehoe","DEF",78,"HWH-Bunclody",1,null],
    ["wexford-96","Ger Cushe","DEF",79,"Naomh Eanna",1,null],
    ["wexford-96","John O'Connor","DEF",80,"St Martin's",1,1],
    ["wexford-96","Rod Guiney","DEF",80,"Rathnure",1,null],
    ["wexford-96","Liam Dunne","DEF",88,"Oulart-the-Ballagh",1,3],
    ["wexford-96","Larry O'Gorman","DEF",83,"Faythe Harriers",1,1],
    ["wexford-96","Adrian Fenlon","MID",82,"Rapparees",1,1],
    ["wexford-96","George O'Connor","MID",81,"St Martin's",1,null],
    ["wexford-96","Rory McCarthy","FWD",80,"St Martin's",1,null],
    ["wexford-96","Martin Storey","FWD",87,"Oulart-the-Ballagh",1,2],
    ["wexford-96","Larry Murphy","FWD",82,"Cloughbawn",1,null],
    ["wexford-96","Éamonn Scallan","FWD",83,"Liam Mellows",1,null],
    ["wexford-96","Garry Laffan","FWD",80,"Glynn-Barntown",1,null],
    ["wexford-96","Tom Dempsey","FWD",84,"Buffers Alley",1,1],

    /* ===== WATERFORD — Mullane's Déise [V 2008 final] ===== */
    ["waterford-08","Clinton Hennessy","GK",80,"Dunhill",null,null],
    ["waterford-08","Eoin Murphy","DEF",81,"Tallow",null,1],
    ["waterford-08","Declan Prendergast","DEF",80,"Ardmore",null,null],
    ["waterford-08","Aidan Kearney","DEF",79,"Roanmore",null,null],
    ["waterford-08","Tony Browne","DEF",86,"Mount Sion",null,2],
    ["waterford-08","Ken McGrath","DEF",89,"Mount Sion",null,3],
    ["waterford-08","Kevin Moran","DEF",82,"De La Salle",null,1],
    ["waterford-08","Michael 'Brick' Walsh","MID",87,"Stradbally",null,1],
    ["waterford-08","Jamie Nagle","MID",80,"Roanmore",null,null],
    ["waterford-08","Dan Shanahan","FWD",88,"Lismore",null,2],
    ["waterford-08","Séamus Prendergast","FWD",81,"Ardmore",null,null],
    ["waterford-08","Stephen Molumphy","FWD",81,"Ballyduff Upper",null,1],
    ["waterford-08","Eoin McGrath","FWD",80,"Ballygunner",null,null],
    ["waterford-08","Eoin Kelly","FWD",87,"Passage",null,3],
    ["waterford-08","John Mullane","FWD",89,"De La Salle",null,4],

    /* ===== CLARE — The Young Banner (2013 champions) ===== */
    ["clare-13","Patrick Kelly","GK",81,"Inagh-Kilnamona",1,null],
    ["clare-13","Domhnall O'Donovan","DEF",81,"Clonlara",1,null],
    ["clare-13","David McInerney","DEF",84,"Tulla",1,1],
    ["clare-13","Cian Dillon","DEF",81,"Crusheen",1,1],
    ["clare-13","Patrick O'Connor","DEF",80,"Tubber",1,null],
    ["clare-13","Brendan Bugler","DEF",85,"Whitegate",1,1],
    ["clare-13","Conor Ryan","DEF",82,"Cratloe",1,1],
    ["clare-13","Tony Kelly","MID",90,"Ballyea",1,2],
    ["clare-13","Colm Galvin","MID",84,"Clonlara",1,1],
    ["clare-13","Podge Collins","FWD",86,"Cratloe",1,1],
    ["clare-13","Conor McGrath","FWD",85,"Cratloe",1,1],
    ["clare-13","John Conlon","FWD",84,"Clonlara",1,null],
    ["clare-13","Darach Honan","FWD",82,"Clonlara",1,null],
    ["clare-13","Shane O'Donnell","FWD",84,"Éire Óg Ennis",1,null],
    ["clare-13","Colin Ryan","FWD",82,"Newmarket-on-Fergus",1,1],

    /* ===== CLARE — The Banner's Return [V 2024 final] ===== */
    ["clare-24","Eibhear Quilligan","GK",81,"Feakle",1,null],
    ["clare-24","Adam Hogan","DEF",82,"Feakle",1,1],
    ["clare-24","Conor Cleary","DEF",83,"St Joseph's Miltown Malbay",1,null],
    ["clare-24","Conor Leen","DEF",81,null,1,null],
    ["clare-24","Diarmuid Ryan","DEF",83,"Cratloe",1,null],
    ["clare-24","John Conlon","DEF",85,"Clonlara",2,1],
    ["clare-24","David McInerney","DEF",84,"Tulla",2,1],
    ["clare-24","David Fitzgerald","MID",82,"Inagh-Kilnamona",1,null],
    ["clare-24","Cathal Malone","MID",82,"Sixmilebridge",1,null],
    ["clare-24","Tony Kelly","FWD",90,"Ballyea",2,3],
    ["clare-24","Mark Rodgers","FWD",84,"Scariff",1,1],
    ["clare-24","Peter Duggan","FWD",84,"Clooney-Quin",1,null],
    ["clare-24","Aidan McCarthy","FWD",83,"Inagh-Kilnamona",1,null],
    ["clare-24","Shane O'Donnell","FWD",88,"Éire Óg Ennis",2,1],
    ["clare-24","David Reidy","FWD",83,"Éire Óg Ennis",1,null],

    /* ===== ANTRIM — Sambo's Saffrons [V 1989 final] ===== */
    ["antrim-89","Niall Patterson","GK",78,"Ballycastle McQuillans",null,null],
    ["antrim-89","Gary O'Kane","DEF",76,"Dunloy",null,null],
    ["antrim-89","Terence Donnelly","DEF",75,"Ballycastle McQuillans",null,null],
    ["antrim-89","Dessie Donnelly","DEF",78,"Ballycastle McQuillans",null,1],
    ["antrim-89","James McNaughton","DEF",76,"Cushendall Ruairí Óg",null,null],
    ["antrim-89","Dominic McKinley","DEF",80,"Loughgiel Shamrocks",null,1],
    ["antrim-89","Leonard McKeegan","DEF",76,"Armoy",null,null],
    ["antrim-89","Paul McKillen","MID",78,"Ballycastle McQuillans",null,null],
    ["antrim-89","Declan McMullan","MID",76,"Ballycastle McQuillans",null,null],
    ["antrim-89","Ciaran Barr","FWD",83,"St John's",null,1],
    ["antrim-89","Aidan McCarry","FWD",78,"Glenariffe",null,null],
    ["antrim-89","Olcan 'Cloot' McFetridge","FWD",80,"Armoy",null,1],
    ["antrim-89","Donal Armstrong","FWD",77,"Cushendall Ruairí Óg",null,null],
    ["antrim-89","Brian Donnelly","FWD",77,"Ballycastle McQuillans",null,null],
    ["antrim-89","Terence 'Sambo' McNaughton","FWD",82,"Cushendall Ruairí Óg",null,1],

    /* ===== KERRY — The Kingdom Hurlers (modern, weaker county) ===== */
    ["kerry-hurlers","Stephen Murphy","GK",75,"Causeway",null,null],
    ["kerry-hurlers","Eoin Ross","DEF",75,"Ballyduff",null,null],
    ["kerry-hurlers","Paud Costelloe","DEF",76,"Lixnaw",null,null],
    ["kerry-hurlers","Jason Diggins","DEF",76,"Causeway",null,null],
    ["kerry-hurlers","Tomás O'Connor","DEF",77,"Crotta",null,null],
    ["kerry-hurlers","Bryan Murphy","DEF",75,"Cauesway",null,null],
    ["kerry-hurlers","Fionán Mackessy","DEF",81,"St Brendan's",null,null],
    ["kerry-hurlers","Michael O'Leary","MID",79,"Abbeydorney",null,null],
    ["kerry-hurlers","Jordan Conway","MID",77,"Crotta",null,null],
    ["kerry-hurlers","Pádraig Boyle","FWD",82,"Lixnaw",null,null],
    ["kerry-hurlers","Mikey Boyle","FWD",80,"Ballyduff",null,null],
    ["kerry-hurlers","Shane Conway","FWD",84,"Lixnaw",null,null],
    ["kerry-hurlers","Maurice O'Connor","FWD",77,"Kilmoyley",null,null],
    ["kerry-hurlers","Ronan Walsh","FWD",56,"Kilmoyley",null,null],
    ["kerry-hurlers","Daniel Collins","FWD",78,"Kilmoyley",null,null],

    /* ===== CORK — The Rebels' Double [V 2005 final] ===== */
    ["cork-05","Donal Óg Cusack","GK",85,"Cloyne",3,3],
    ["cork-05","Brian Murphy","DEF",81,"Bride Rovers",2,null],
    ["cork-05","Diarmuid O'Sullivan","DEF",84,"Cloyne",3,3],
    ["cork-05","Pat Mulcahy","DEF",81,"Newtownshandrum",2,null],
    ["cork-05","John Gardiner","DEF",85,"Na Piarsaigh",2,3],
    ["cork-05","Ronan Curran","DEF",85,"St Finbarr's",2,2],
    ["cork-05","Seán Óg Ó hAilpín","DEF",87,"Na Piarsaigh",3,3],
    ["cork-05","Tom Kenny","MID",83,"Grenagh",2,1],
    ["cork-05","Jerry O'Connor","MID",85,"Newtownshandrum",2,2],
    ["cork-05","Kieran Murphy","FWD",81,"Sarsfields",2,null],
    ["cork-05","Niall McCarthy","FWD",83,"Carrigtwohill",2,1],
    ["cork-05","Timmy McCarthy","FWD",82,"Castlelyons",3,null],
    ["cork-05","Ben O'Connor","FWD",85,"Newtownshandrum",3,3],
    ["cork-05","Brian Corcoran","FWD",86,"Erin's Own",2,4],
    ["cork-05","Joe Deane","FWD",87,"Killeagh",3,3],

    /* ===== TIPPERARY — Stopping the Five [V 2010 final] ===== */
    ["tipperary-10","Brendan Cummins","GK",86,"Ardfinnan",2,5],
    ["tipperary-10","Paddy Stapleton","DEF",82,"Borris-Ileigh",1,1],
    ["tipperary-10","Paul Curran","DEF",83,"Mullinahone",1,1],
    ["tipperary-10","Michael Cahill","DEF",81,"Thurles Sarsfields",1,null],
    ["tipperary-10","Declan Fanning","DEF",83,"Killenaule",1,1],
    ["tipperary-10","Conor O'Mahony","DEF",83,"Newport",1,1],
    ["tipperary-10","Pádraic Maher","DEF",87,"Thurles Sarsfields",1,5],
    ["tipperary-10","Brendan Maher","MID",85,"Borris-Ileigh",1,2],
    ["tipperary-10","Shane McGrath","MID",83,"Ballinahinch",1,1],
    ["tipperary-10","Gearóid Ryan","FWD",82,"Templederry Kenyons",1,null],
    ["tipperary-10","Patrick 'Bonner' Maher","FWD",83,"Lorrha-Dorrha",1,1],
    ["tipperary-10","John O'Brien","FWD",82,"Toomevara",1,null],
    ["tipperary-10","Noel McGrath","FWD",86,"Loughmore-Castleiney",1,3],
    ["tipperary-10","Eoin Kelly","FWD",88,"Mullinahone",1,5],
    ["tipperary-10","Lar Corbett","FWD",88,"Thurles Sarsfields",2,2],

    /* ===== GALWAY — Keady's Tribesmen [V 1988 final] ===== */
    ["galway-88","John Commins","GK",82,"Gort",2,1],
    ["galway-88","Sylvie Linnane","DEF",84,"Gort",2,2],
    ["galway-88","Conor Hayes","DEF",85,"Kiltormer",3,3],
    ["galway-88","Ollie Kilkenny","DEF",82,"Kiltormer",2,1],
    ["galway-88","Pete Finnerty","DEF",86,"Mullagh",2,4],
    ["galway-88","Tony Keady","DEF",87,"Killimordaly",2,2],
    ["galway-88","Gerry McInerney","DEF",84,"Kinvara",2,2],
    ["galway-88","Michael Coleman","MID",83,"Abbeyknockmoy",1,1],
    ["galway-88","Pat Malone","MID",82,"Oranmore-Maree",2,null],
    ["galway-88","Anthony Cunningham","FWD",83,"St Thomas'",2,null],
    ["galway-88","Joe Cooney","FWD",87,"Sarsfields",2,3],
    ["galway-88","Martin Naughton","FWD",84,"Turloughmore",2,2],
    ["galway-88","Michael McGrath","FWD",83,"Sarsfields",2,1],
    ["galway-88","Brendan Lynskey","FWD",83,"Meelick-Eyrecourt",2,null],
    ["galway-88","Éanna Ryan","FWD",84,"Killimordaly",2,2],

    /* ===== KILKENNY — DJ's Cats [V 2003 final] ===== */
    ["kilkenny-03","James McGarry","GK",82,"Danesfort",3,null],
    ["kilkenny-03","Michael Kavanagh","DEF",84,"St Lachtain's",10,4],
    ["kilkenny-03","Noel Hickey","DEF",86,"Dunnamaggin",10,5],
    ["kilkenny-03","James Ryall","DEF",81,"Graigue-Ballycallan",2,null],
    ["kilkenny-03","Seán Dowling","DEF",82,"Carrickshock",2,null],
    ["kilkenny-03","Peter Barry","DEF",84,"James Stephens",4,2],
    ["kilkenny-03","JJ Delaney","DEF",87,"Fenians",9,5],
    ["kilkenny-03","Derek Lyng","MID",83,"Emeralds",7,2],
    ["kilkenny-03","Paddy Mullally","MID",80,"Glenmore",1,null],
    ["kilkenny-03","Henry Shefflin","FWD",92,"Ballyhale Shamrocks",10,11],
    ["kilkenny-03","John Hoyne","FWD",82,"Graigue-Ballycallan",3,null],
    ["kilkenny-03","Tommy Walsh","FWD",86,"Tullaroan",9,9],
    ["kilkenny-03","DJ Carey","FWD",92,"Young Irelands",5,9],
    ["kilkenny-03","Martin Comerford","FWD",85,"O'Loughlin Gaels",7,3],
    ["kilkenny-03","Eddie Brennan","FWD",85,"Graigue-Ballycallan",8,4],

    /* ===== WEXFORD — Davy's Model County [V 2019 Leinster final] ===== */
    ["wexford-19","Mark Fanning","GK",82,"Glynn-Barntown",null,null],
    ["wexford-19","Shane Reck","DEF",80,"Oylegate-Glenbrien",null,null],
    ["wexford-19","Liam Ryan","DEF",82,"Rapparees",null,1],
    ["wexford-19","Simon Donohoe","DEF",80,"Shelmaliers",null,null],
    ["wexford-19","Paudie Foley","DEF",81,"Crossabeg-Ballymurn",null,null],
    ["wexford-19","Matthew O'Hanlon","DEF",82,"St James'",null,null],
    ["wexford-19","Shaun Murphy","DEF",81,"Oulart-the-Ballagh",null,null],
    ["wexford-19","Kevin Foley","MID",82,"Rapparees",null,null],
    ["wexford-19","Diarmuid O'Keeffe","MID",83,"St Anne's",null,null],
    ["wexford-19","Liam Óg McGovern","FWD",81,"St Anne's",null,null],
    ["wexford-19","Lee Chin","FWD",86,"Faythe Harriers",null,1],
    ["wexford-19","Conor McDonald","FWD",84,"Naomh Éanna",null,null],
    ["wexford-19","Jack O'Connor","FWD",82,"St Martin's",null,null],
    ["wexford-19","Rory O'Connor","FWD",83,"St Martin's",null,null],
    ["wexford-19","Paul Morris","FWD",81,"Ferns St Aidan's",null,null],

    /* ===== DUBLIN — Daly's Dubs [V 2013 Leinster final] ===== */
    ["dublin-13","Gary Maguire","GK",81,"Ballyboden St Enda's",null,null],
    ["dublin-13","Niall Corcoran","DEF",80,"Kilmacud Crokes",null,null],
    ["dublin-13","Peter Kelly","DEF",81,"Lucan Sarsfields",null,1],
    ["dublin-13","Paul Schutte","DEF",80,"Cuala",null,null],
    ["dublin-13","Stephen Hiney","DEF",81,"Ballyboden St Enda's",null,1],
    ["dublin-13","Liam Rushe","DEF",84,"St Patrick's Palmerstown",null,1],
    ["dublin-13","Michael Carton","DEF",80,"O'Toole's",null,null],
    ["dublin-13","Johnny McCaffrey","MID",81,"Lucan Sarsfields",null,null],
    ["dublin-13","Joey Boland","MID",80,"Na Fianna",null,null],
    ["dublin-13","Conal Keaney","FWD",83,"Ballyboden St Enda's",null,1],
    ["dublin-13","Ryan O'Dwyer","FWD",82,"Kilmacud Crokes",null,1],
    ["dublin-13","Danny Sutcliffe","FWD",83,"St Jude's",null,1],
    ["dublin-13","David 'Dotsy' O'Callaghan","FWD",82,"St Brigid's",null,null],
    ["dublin-13","David Treacy","FWD",81,"Cuala",null,null],
    ["dublin-13","Paul Ryan","FWD",82,"Ballyboden St Enda's",null,1],

    /* ===== CORK — Barry-Murphy's Three [V 1978 final] ===== */
    ["cork-78","Martin Coleman","GK",83,"Ballinhassig",3,1],
    ["cork-78","Brian Murphy","DEF",83,"Nemo Rangers",3,2],
    ["cork-78","Martin O'Doherty","DEF",83,"Glen Rovers",3,1],
    ["cork-78","John Horgan","DEF",84,"Blackrock",3,3],
    ["cork-78","Dermot McCurtain","DEF",83,"Blackrock",3,2],
    ["cork-78","Johnny Crowley","DEF",84,"Bishopstown",3,1],
    ["cork-78","Denis Coughlan","DEF",84,"Glen Rovers",3,1],
    ["cork-78","Tom Cashman","MID",85,"Blackrock",3,2],
    ["cork-78","Pat Moylan","MID",82,"Blackrock",3,1],
    ["cork-78","Jimmy Barry-Murphy","FWD",90,"St Finbarr's",5,4],
    ["cork-78","Gerald McCarthy","FWD",85,"St Finbarr's",5,2],
    ["cork-78","Tim Crowley","FWD",82,"Newcestown",3,1],
    ["cork-78","Charlie McCarthy","FWD",85,"St Finbarr's",4,3],
    ["cork-78","Ray Cummins","FWD",87,"Blackrock",4,3],
    ["cork-78","Seánie O'Leary","FWD",84,"Youghal",4,1],

    /* ===== CORK — Horgan's Nearly Men [V 2024 final] ===== */
    ["cork-24","Patrick Collins","GK",83,"Ballinhassig",null,1],
    ["cork-24","Niall O'Leary","DEF",81,"Castlelyons",null,null],
    ["cork-24","Eoin Downey","DEF",81,"Glen Rovers",null,null],
    ["cork-24","Seán O'Donoghue","DEF",82,"Inniscarra",null,1],
    ["cork-24","Ciarán Joyce","DEF",83,"Castlemartyr",null,1],
    ["cork-24","Robert Downey","DEF",82,"Glen Rovers",null,null],
    ["cork-24","Mark Coleman","DEF",84,"Blarney",null,2],
    ["cork-24","Tim O'Mahony","MID",82,"Newtownshandrum",null,null],
    ["cork-24","Darragh Fitzgibbon","MID",84,"Charleville",null,1],
    ["cork-24","Declan Dalton","FWD",81,"Fr O'Neill's",null,null],
    ["cork-24","Shane Barrett","FWD",83,"Blarney",null,1],
    ["cork-24","Séamus Harnedy","FWD",83,"St Ita's",null,2],
    ["cork-24","Patrick Horgan","FWD",86,"Glen Rovers",null,2],
    ["cork-24","Alan Connolly","FWD",83,"Blackrock",null,null],
    ["cork-24","Brian Hayes","FWD",84,"St Finbarr's",null,1],

    /* ===== TIPPERARY — English's Premier [V 1991 final] ===== */
    ["tipperary-91","Ken Hogan","GK",83,"Lorrha",2,1],
    ["tipperary-91","Paul Delaney","DEF",83,"Roscrea",2,2],
    ["tipperary-91","Noel Sheehy","DEF",82,"Silvermines",2,null],
    ["tipperary-91","Michael Ryan","DEF",82,"Upperchurch-Drombane",2,1],
    ["tipperary-91","Colm Bonnar","DEF",83,"Cashel King Cormacs",2,1],
    ["tipperary-91","Bobby Ryan","DEF",84,"Borris-Ileigh",2,1],
    ["tipperary-91","Conal Bonnar","DEF",83,"Cashel King Cormacs",2,1],
    ["tipperary-91","Declan Carr","MID",84,"Holycross-Ballycahill",2,1],
    ["tipperary-91","Aidan Ryan","MID",82,"Borris-Ileigh",2,null],
    ["tipperary-91","Michael Cleary","FWD",85,"Éire Óg Nenagh",2,2],
    ["tipperary-91","Declan Ryan","FWD",86,"Clonoulty-Rossmore",3,2],
    ["tipperary-91","John Leahy","FWD",85,"Mullinahone",2,1],
    ["tipperary-91","Pat Fox","FWD",87,"Éire Óg Annacarty",2,3],
    ["tipperary-91","Cormac Bonnar","FWD",84,"Cashel King Cormacs",2,2],
    ["tipperary-91","Nicky English","FWD",88,"Lattin-Cullen",2,4],

    /* ===== WATERFORD — Gleeson's Déise [V 2017 final] ===== */
    ["waterford-17","Stephen O'Keeffe","GK",82,"Ballygunner",null,1],
    ["waterford-17","Shane Fives","DEF",80,"Tourin",null,null],
    ["waterford-17","Barry Coughlan","DEF",80,"Ballygunner",null,null],
    ["waterford-17","Noel Connors","DEF",82,"Passage",null,2],
    ["waterford-17","Tadhg de Búrca","DEF",85,"Clashmore-Kinsalebeg",null,2],
    ["waterford-17","Austin Gleeson","DEF",87,"Mount Sion",null,2],
    ["waterford-17","Philip Mahony","DEF",81,"Ballygunner",null,null],
    ["waterford-17","Jamie Barron","MID",84,"Fourmilewater",null,1],
    ["waterford-17","Darragh Lyons","MID",79,"Dungarvan",null,null],
    ["waterford-17","Kevin Moran","FWD",83,"De La Salle",null,1],
    ["waterford-17","Pauric Mahony","FWD",84,"Ballygunner",null,1],
    ["waterford-17","Jake Dillon","FWD",79,"De La Salle",null,null],
    ["waterford-17","Shane Bennett","FWD",81,"Ballysaggart",null,null],
    ["waterford-17","Michael 'Brick' Walsh","FWD",82,"Stradbally",null,1],
    ["waterford-17","Darragh Fives","FWD",79,"Tourin",null,null],

    /* ===== OFFALY — The First Faithful [V 1981 final] ===== */
    ["offaly-81","Damien Martin","GK",84,"St Rynagh's",1,1],
    ["offaly-81","Tom Donoghue","DEF",80,"St Rynagh's",1,null],
    ["offaly-81","Eugene Coughlan","DEF",83,"Seir Kieran",2,1],
    ["offaly-81","Pat Fleury","DEF",82,"Drumcullen",2,1],
    ["offaly-81","Aidan Fogarty","DEF",81,"Kinnitty",1,1],
    ["offaly-81","Pat Delaney","DEF",83,"Kinnitty",2,1],
    ["offaly-81","Ger Coughlan","DEF",82,"Kinnitty",2,1],
    ["offaly-81","Joachim Kelly","MID",82,"Lusmagh",2,1],
    ["offaly-81","Liam Currams","MID",82,"Kilcormac-Killoughey",1,1],
    ["offaly-81","Paddy Kirwan","FWD",80,"Seir Kieran",1,null],
    ["offaly-81","Brendan Bermingham","FWD",80,"St Rynagh's",1,null],
    ["offaly-81","Mark Corrigan","FWD",83,"Coolderry",1,1],
    ["offaly-81","Pat Carroll","FWD",83,"Coolderry",1,1],
    ["offaly-81","Pádraig Horan","FWD",84,"St Rynagh's",2,1],
    ["offaly-81","Johnny Flaherty","FWD",83,"Kinnitty",1,1],

    /* ===== ANTRIM — McManus's Saffrons [V 2020 Joe McDonagh final] ===== */
    ["antrim-20","Ryan Elliott","GK",77,"Loughgiel Shamrocks",null,null],
    ["antrim-20","Phelim Duffin","DEF",76,null,null,null],
    ["antrim-20","Matthew Donnelly","DEF",77,null,null,null],
    ["antrim-20","Stephen Rooney","DEF",76,null,null,null],
    ["antrim-20","Joe Maskey","DEF",78,"Rossa",null,null],
    ["antrim-20","Paddy Burke","DEF",78,"Cushendall Ruairí Óg",null,null],
    ["antrim-20","Gerard Walsh","DEF",77,"St John's",null,null],
    ["antrim-20","Eoghan Campbell","MID",79,"Cushendall Ruairí Óg",null,null],
    ["antrim-20","Keelan Molloy","MID",78,"Dunloy Cúchullainn's",null,null],
    ["antrim-20","Niall McKenna","FWD",78,"Dunloy Cúchullainn's",null,null],
    ["antrim-20","James McNaughton","FWD",79,"Cushendall Ruairí Óg",null,null],
    ["antrim-20","Conor McCann","FWD",80,"St John's",null,null],
    ["antrim-20","Ciaran Clarke","FWD",81,"Ballycastle McQuillans",null,null],
    ["antrim-20","Neil McManus","FWD",82,"Cushendall Ruairí Óg",null,1],
    ["antrim-20","Daniel McCloskey","FWD",77,"Dunloy Cúchullainn's",null,null],

    /* ===== LAOIS — The Dublin Shockers [R] 2019 Joe McDonagh squad ===== */
    ["laois-19","Enda Rowland","GK",78,"Borris-Kilcotton",null,null],
    ["laois-19","Lee Cleere","DEF",76,null,null,null],
    ["laois-19","Joe Phelan","DEF",77,null,null,null],
    ["laois-19","Matthew Whelan","DEF",77,null,null,null],
    ["laois-19","Ryan Mullaney","DEF",78,"Rathdowney-Errill",null,null],
    ["laois-19","Jack Kelly","DEF",78,"Rathdowney-Errill",null,null],
    ["laois-19","Donnchadh Hartnett","DEF",75,null,null,null],
    ["laois-19","Paddy Purcell","MID",79,"Rathdowney-Errill",null,null],
    ["laois-19","John Lennon","MID",76,null,null,null],
    ["laois-19","Aaron Dunphy","FWD",80,"Borris-Kilcotton",null,null],
    ["laois-19","Ross King","FWD",81,"Rathdowney-Errill",null,null],
    ["laois-19","Willie Dunphy","FWD",80,"Clough-Ballacolla",null,null],
    ["laois-19","Charles 'Cha' Dwyer","FWD",78,null,null,null],
    ["laois-19","Stephen Maher","FWD",78,"Ballinakill",null,null],
    ["laois-19","PJ Scully","FWD",77,null,null,null],

    /* ===== CARLOW — Bonnar's Barrowsiders [R] 2018 Joe McDonagh squad ===== */
    ["carlow-18","Brian Tracey","GK",77,null,null,null],
    ["carlow-18","Michael Doyle","DEF",76,null,null,null],
    ["carlow-18","Alan Corcoran","DEF",77,null,null,null],
    ["carlow-18","David English","DEF",77,null,null,null],
    ["carlow-18","Diarmuid Byrne","DEF",76,null,null,null],
    ["carlow-18","Richard Coady","DEF",77,null,null,null],
    ["carlow-18","Paul Doyle","DEF",77,null,null,null],
    ["carlow-18","Eoin Nolan","MID",77,null,null,null],
    ["carlow-18","John Michael Nolan","MID",77,null,null,null],
    ["carlow-18","Ted Joyce","FWD",76,null,null,null],
    ["carlow-18","Séamus Murphy","FWD",77,null,null,null],
    ["carlow-18","Jack Kavanagh","FWD",77,null,null,null],
    ["carlow-18","Marty Kavanagh","FWD",81,"St Mullin's",null,null],
    ["carlow-18","Chris Nolan","FWD",80,"Mount Leinster Rangers",null,null],
    ["carlow-18","Denis Murphy","FWD",78,null,null,null],

    /* ===== DOWN — The Mourne Men [R] 1990s Ulster champions ===== */
    ["down-90s","Graham Clarke","GK",77,"Ballycran",null,null],
    ["down-90s","Paul Coleman","DEF",77,null,null,null],
    ["down-90s","Gary Savage","DEF",78,null,null,null],
    ["down-90s","John McGrattan","DEF",77,"Portaferry",null,null],
    ["down-90s","Marty Mallon","DEF",77,null,null,null],
    ["down-90s","Conor Arthurs","DEF",76,null,null,null],
    ["down-90s","Dermot Woods","DEF",75,null,null,null],
    ["down-90s","Danny Hughes","MID",79,null,null,null],
    ["down-90s","Noel Keith","MID",78,null,null,null],
    ["down-90s","Gerard McGrattan","FWD",82,"Portaferry",null,1],
    ["down-90s","Noel Sands","FWD",82,"Ballycran",null,null],
    ["down-90s","Hugh Gilmore","FWD",78,null,null,null],
    ["down-90s","Paul Branniff","FWD",78,null,null,null],
    ["down-90s","Michael Blaney","FWD",77,null,null,null],
    ["down-90s","Gareth Johnson","FWD",76,null,null,null],

    /* ===== WESTMEATH — The Lake County's Best [R] Christy Ring / Joe McDonagh era ===== */
    ["westmeath","Allan Devine","GK",77,null,null,null],
    ["westmeath","Tommy Doyle","DEF",78,null,null,null],
    ["westmeath","Cory Whelan","DEF",77,null,null,null],
    ["westmeath","Darragh Egerton","DEF",77,null,null,null],
    ["westmeath","Tommy Gallagher","DEF",76,null,null,null],
    ["westmeath","Aaron Craig","DEF",75,null,null,null],
    ["westmeath","John Gilligan","DEF",76,null,null,null],
    ["westmeath","Aonghus Clarke","MID",79,"Castlepollard",null,null],
    ["westmeath","Robbie Greville","MID",78,null,null,null],
    ["westmeath","Niall O'Brien","FWD",80,null,null,null],
    ["westmeath","Killian Doyle","FWD",80,"Raharney",null,null],
    ["westmeath","Brendan Murtagh","FWD",80,"Clonkill",null,null],
    ["westmeath","Derek McNicholas","FWD",78,null,null,null],
    ["westmeath","Eoin Price","FWD",76,null,null,null],
    ["westmeath","Conor Jordan","FWD",76,null,null,null],

    /* ===== KILDARE — The Lilywhites' Ring [R] Christy Ring Cup winners ===== */
    ["kildare","Paul Dolan","GK",76,null,null,null],
    ["kildare","David Slattery","DEF",76,null,null,null],
    ["kildare","Gerry Keegan","DEF",77,null,null,null],
    ["kildare","Mark Moloney","DEF",76,null,null,null],
    ["kildare","Cathal McCabe","DEF",75,null,null,null],
    ["kildare","Conan Boran","DEF",75,null,null,null],
    ["kildare","Simon Leacy","DEF",75,null,null,null],
    ["kildare","Niall Ó Muineacháin","MID",77,null,null,null],
    ["kildare","James Burke","MID",76,null,null,null],
    ["kildare","Paul Divilly","FWD",80,null,null,null],
    ["kildare","Jack Sheridan","FWD",80,"Naas",null,null],
    ["kildare","Brian Byrne","FWD",78,null,null,null],
    ["kildare","Martin Fitzgerald","FWD",76,null,null,null],
    ["kildare","Gerald Dempsey","FWD",75,null,null,null],
    ["kildare","Mark Grace","FWD",75,null,null,null],

    /* ===== TIPPERARY — Cahill's Champions [V 2025 final] ===== */
    ["tipperary-25","Rhys Shelly","GK",84,"Moycarkey-Borris",1,null],
    ["tipperary-25","Robert Doyle","DEF",82,null,1,null],
    ["tipperary-25","Eoghan Connolly","DEF",85,"Cashel King Cormacs",1,1],
    ["tipperary-25","Michael Breen","DEF",83,"Ballina",3,null],
    ["tipperary-25","Craig Morgan","DEF",83,"Kilruane MacDonaghs",1,null],
    ["tipperary-25","Ronan Maher","DEF",87,"Thurles Sarsfields",3,3],
    ["tipperary-25","Bryan O'Mara","DEF",83,"Holycross-Ballycahill",1,null],
    ["tipperary-25","Willie Connors","MID",83,"Kiladangan",2,null],
    ["tipperary-25","Conor Stakelum","MID",83,"Thurles Sarsfields",1,null],
    ["tipperary-25","Jake Morris","FWD",87,"Nenagh Éire Óg",2,1],
    ["tipperary-25","Andrew Ormond","FWD",84,"JK Brackens",1,null],
    ["tipperary-25","Sam O'Farrell","FWD",83,"Nenagh Éire Óg",1,null],
    ["tipperary-25","Darragh McCarthy","FWD",84,"Toomevara",1,1],
    ["tipperary-25","John McGrath","FWD",88,"Loughmore-Castleiney",3,1],
    ["tipperary-25","Jason Forde","FWD",84,"Silvermines",3,1],
  ],

  extras: {
    "tipperary-25|Ronan Maher":{captain:true,note:"Captained Tipp to the 2025 All-Ireland"},
    "tipperary-25|Darragh McCarthy":{note:"Sensational 2025 — 1-13 in the final; teenage Young Hurler of the Year"},
    "tipperary-25|John McGrath":{note:"Two goals in the 2025 final; brother of Noel & Brian McGrath",family:"brother of Noel & Brian McGrath"},
    "tipperary-25|Jake Morris":{note:"Pace and scores off the wing in the 2025 win"},
    "cork-05|Seán Óg Ó hAilpín":{captain:true,poty:1,note:"Hurler of the Year 2004; iconic 2005 acceptance speech"},
    "cork-05|Brian Corcoran":{note:"Came out of retirement; full-forward on the 2004–05 double team"},
    "cork-05|Ronan Curran":{note:"All-Star centre-back, the spine of the double"},
    "tipperary-10|Lar Corbett":{poty:1,note:"Scored 3-0 and Man of the Match in the 2010 final"},
    "tipperary-10|Eoin Kelly":{captain:true,note:"Captain who lifted Liam MacCarthy in 2010"},
    "tipperary-10|Pádraic Maher":{note:"5 All-Stars; one of the great modern defenders"},
    "tipperary-10|Noel McGrath":{note:"Playmaker; brother of John & Brian McGrath"},
    "galway-88|Tony Keady":{poty:1,note:"Hurler of the Year 1988; legendary centre-back"},
    "galway-88|Joe Cooney":{note:"Sublime forward of the 1987–88 back-to-back team"},
    "galway-88|Pete Finnerty":{note:"Regarded among the greatest wing-backs of all time"},
    "galway-88|Conor Hayes":{captain:true,note:"Lifted Liam MacCarthy in 1987 and 1988"},
    "kilkenny-03|DJ Carey":{captain:true,nickname:"The Dodger",note:"5 All-Irelands, 9 All-Stars; one of the all-time greats"},
    "kilkenny-03|Henry Shefflin":{note:"Already a two-time champion in 2003, on his way to 10"},
    "wexford-19|Lee Chin":{captain:true,note:"Talisman of Davy Fitzgerald's Wexford; scored 9 in the 2019 Leinster final"},
    "wexford-19|Rory O'Connor":{note:"Man of the Match in the 2019 Leinster final"},
    "wexford-19|Matthew O'Hanlon":{captain:true,note:"Joint-captain of the 2019 Leinster champions"},
    "dublin-13|Liam Rushe":{note:"All-Star; spine of Dublin's 2013 Leinster title"},
    "dublin-13|Johnny McCaffrey":{captain:true,note:"First Dublin captain to lift the Bob O'Keeffe Cup in 52 years"},
    "dublin-13|Conal Keaney":{note:"Dual star who returned to hurling; also a Dublin footballer",dual:"Dublin football"},
    "cork-78|Jimmy Barry-Murphy":{note:"All-time great; dual All-Ireland winner (hurling & football)",dual:"Cork football"},
    "cork-78|Ray Cummins":{note:"Legendary dual star; full-forward on the three-in-a-row",dual:"Cork football"},
    "cork-78|Charlie McCarthy":{captain:true},
    "tipperary-91|Nicky English":{poty:1,note:"One of hurling's greatest forwards; 2-12 in the 1989 final"},
    "tipperary-91|Pat Fox":{note:"Man of the Match in the 1991 final"},
    "tipperary-91|Declan Carr":{captain:true},
    "tipperary-91|Cormac Bonnar":{family:"brother of Colm & Conal Bonnar",nickname:"The Viking"},
    "waterford-17|Austin Gleeson":{poty:1,born:1995,note:"Hurler of the Year 2016"},
    "waterford-17|Kevin Moran":{captain:true},
    "cork-24|Patrick Horgan":{nickname:"Hoggy",note:"All-time top scorer in senior hurling championship history"},
    "cork-24|Seán O'Donoghue":{captain:true},
    "cork-24|Mark Coleman":{note:"Two-time All-Star half-back"},
    "offaly-81|Damien Martin":{note:"Won the first-ever All-Star (1971); iconic goalkeeper"},
    "offaly-81|Pádraig Horan":{captain:true,note:"Captain of Offaly's first All-Ireland in 1981"},
    "offaly-81|Johnny Flaherty":{note:"Scored the famous handpassed goal that won the 1981 final"},
    "offaly-81|Liam Currams":{dual:"also won an All-Ireland football medal with Offaly in 1982"},
    "antrim-20|Neil McManus":{note:"Antrim's long-serving talisman; was an injured sub on the 2020 final day but the heart of the team for over a decade"},
    "antrim-20|Conor McCann":{captain:true,note:"Captained Antrim to the 2020 Joe McDonagh Cup"},
    "antrim-20|Ciaran Clarke":{note:"Scored 0-11 in the 2020 Joe McDonagh final"},
    "antrim-20|James McNaughton":{family:"son of Sambo McNaughton of the 1989 team"},
    "laois-19|Ross King":{note:"Sharpshooter of Laois's 2019 Joe McDonagh win and famous defeat of Dublin"},
    "laois-19|Paddy Purcell":{captain:true},
    "carlow-18|Marty Kavanagh":{note:"Carlow's talisman free-taker; key to the 2018 Joe McDonagh title"},
    "carlow-18|Chris Nolan":{note:"Skilful Mount Leinster Rangers forward"},
    "down-90s|Gerard McGrattan":{note:"Down's only ever hurling All-Star (1992)"},
    "down-90s|Noel Sands":{note:"Down's favourite son; five-time All-Star nominee"},
    "westmeath|Brendan Murtagh":{note:"Long regarded as one of Westmeath's greatest hurlers"},
    "westmeath|Killian Doyle":{note:"Prolific free-taker for the Lake County"},
    "kildare|Paul Divilly":{note:"Christy Ring Cup top scorer; Kildare stalwart"},
    "kildare|Jack Sheridan":{note:"Modern Kildare sharpshooter"},
    "kilkenny-08|Henry Shefflin":{born:1979,poty:1,nickname:"King Henry",note:"11 All-Stars — a record; 10 All-Ireland medals"},
    "kilkenny-08|James 'Cha' Fitzpatrick":{captain:true},
    "kilkenny-08|Tommy Walsh":{note:"9 All-Stars in a row"},
    "kilkenny-10s|TJ Reid":{born:1987,poty:1},
    "kilkenny-10s|Michael Fennelly":{poty:1,born:1985},
    "limerick-20|Cian Lynch":{born:1996,poty:2,note:"Hurler of the Year 2018 & 2021"},
    "limerick-20|Aaron Gillane":{born:1996},
    "limerick-20|Gearóid Hegarty":{born:1994,poty:1,note:"Hurler of the Year 2020"},
    "limerick-20|Declan Hannon":{captain:true,note:"Lifted Liam MacCarthy 4 times as captain"},
    "cork-99|Brian Corcoran":{poty:1,note:"Hurler of the Year 1999 (also a Cork footballer)",dual:"Cork football"},
    "cork-99|Seán Óg Ó hAilpín":{born:1977,note:"Fiji-born; iconic 2005 acceptance speech as captain"},
    "cork-99|Joe Deane":{born:1977},
    "clare-95|Anthony Daly":{captain:true,born:1969,note:"Later managed Dublin to a Leinster title"},
    "clare-95|Brian Lohan":{note:"Iconic red helmet full-back"},
    "clare-95|Jamesie O'Connor":{poty:1,note:"Hurler of the Year 1998"},
    "tipperary-01|Tommy Dunne":{captain:true,poty:1,note:"Hurler of the Year 2001"},
    "tipperary-01|Eoin Kelly":{born:1982,note:"5 All-Stars; Mullinahone — not the Waterford Eoin Kelly"},
    "tipperary-01|Lar Corbett":{note:"Hat-trick of goals in the 2010 final"},
    "galway-17|Joe Canning":{born:1988,poty:1,note:"Hurler of the Year 2017; ended Galway's 29-year wait"},
    "galway-17|Daithí Burke":{note:"4 All-Stars at centre-back; also an All-Ireland club footballer with Corofin"},
    "galway-17|David Burke":{captain:true},
    "offaly-94|Brian Whelahan":{poty:1,note:"Named on the GAA Hurling Team of the Millennium; one of two from the modern era"},
    "offaly-94|Johnny Dooley":{family:"brother of Joe & Billy Dooley"},
    "offaly-94|Joe Dooley":{family:"brother of Johnny & Billy Dooley"},
    "offaly-94|Billy Dooley":{family:"brother of Johnny & Joe Dooley"},
    "wexford-96|Liam Dunne":{note:"Man of the Match in the 1996 final"},
    "wexford-96|Martin Storey":{captain:true},
    "wexford-96|Damien Fitzhenry":{note:"Long-serving goalkeeper; 3 All-Stars"},
    "waterford-08|John Mullane":{note:"4-time All-Star; Déise talisman"},
    "waterford-08|Ken McGrath":{note:"One of the great centre-backs never to win Liam MacCarthy"},
    "waterford-08|Dan Shanahan":{poty:1,note:"Hurler of the Year 2007"},
    "waterford-08|Michael 'Brick' Walsh":{captain:true,note:"GAA record for most championship appearances"},
    "clare-13|Tony Kelly":{born:1993,poty:1,note:"Hurler of the Year 2013 in his debut season"},
    "clare-13|Shane O'Donnell":{note:"Scored 3-3 from play in the 2013 final replay aged 19"},
    "clare-24|Tony Kelly":{captain:true,born:1993,note:"Talisman of Clare's 2024 All-Ireland win"},
    "clare-24|Shane O'Donnell":{note:"Man of the Match in the 2024 final after extra time"},
    "clare-24|Mark Rodgers":{note:"Breakout star of 2024; Young Hurler of the Year nominee"},
    "antrim-89|Terence 'Sambo' McNaughton":{captain:true,note:"Antrim's most iconic hurler; reached the 1989 final"},
    "antrim-89|Ciaran Barr":{note:"First Ulster hurler to win an All-Star (1988)"},
    "kerry-hurlers|Shane Conway":{note:"Kerry's all-time leading scorer; multiple Joe McDonagh Cup honours"},
    "kerry-hurlers|Pádraig Boyle":{note:"Prolific free-taker for the Kingdom"}
  },

  lists: {},
  groups: {},
  matches: {}
};

/* Transform raw rows → objects (mirrors gaa-db.js so games share one engine).
   zone stays null for now → a player can fill any slot in his line. */
HURLING_DB.players = HURLING_DB.players.map(p=>({
  id:(p[0]+"-"+p[1]).toLowerCase().replace(/[^a-z0-9]+/g,"-"),
  team:p[0], name:p[1], line:p[2], zone:null, rating:p[3], club:p[4],
  allIrelands:p[5], allStars:p[6]
}));

if(typeof module !== 'undefined' && module.exports) module.exports = HURLING_DB;
